<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Choice;
use App\Models\Quiz;
use App\Models\Term;
use Illuminate\Database\Seeder;

class AdditionalTermSeeder2 extends Seeder
{
    public function run(): void
    {
        $data = $this->networkTerms()
            + $this->securityTerms()
            + $this->databaseTerms()
            + $this->algorithmTerms()
            + $this->cloudTerms()
            + $this->webTerms()
            + $this->programmingTerms()
            + $this->osLinuxTerms();

        foreach ($data as $slug => $terms) {
            $cat = Category::where('slug', $slug)->first();
            if (!$cat) continue;
            foreach ($terms as $t) {
                $term = Term::updateOrCreate(
                    ['name' => $t['name'], 'category_id' => $cat->id],
                    [
                        'definition' => $t['definition'],
                        'example'    => $t['example'] ?? null,
                        'difficulty' => $t['difficulty'],
                    ]
                );
                if (!empty($t['quiz'])) {
                    $quiz = Quiz::updateOrCreate(
                        ['term_id' => $term->id, 'question' => $t['quiz']['question']],
                        ['explanation' => $t['quiz']['explanation']]
                    );
                    foreach ($t['quiz']['choices'] as $c) {
                        Choice::updateOrCreate(
                            ['quiz_id' => $quiz->id, 'body' => $c['body']],
                            ['is_correct' => $c['is_correct']]
                        );
                    }
                }
            }
        }
    }

    private function networkTerms(): array
    {
        return ['network' => [
            ['name'=>'スイッチ（L2スイッチ）','definition'=>'MACアドレステーブルを参照して同一ネットワーク内のフレームを適切なポートに転送する機器。ハブと違い全ポートにはフラッディングしない。','example'=>'部署ごとにスイッチでセグメントを分割し、不要なブロードキャストを閉じ込めてネットワークを効率化する。','difficulty'=>2,'quiz'=>['question'=>'L2スイッチがフレーム転送先を決定するために参照するものはどれか？','explanation'=>'L2スイッチはMACアドレステーブル（CAMテーブル）を参照して、宛先MACアドレスに対応するポートにフレームを転送する。','choices'=>[['body'=>'IPアドレステーブル','is_correct'=>false],['body'=>'MACアドレステーブル','is_correct'=>true],['body'=>'ルーティングテーブル','is_correct'=>false],['body'=>'ARPキャッシュ','is_correct'=>false]]]],
            ['name'=>'MTU（Maximum Transmission Unit）','definition'=>'1回の転送で送れる最大データ量（バイト）。イーサネットのデフォルトは1500バイト。これを超えるパケットはフラグメント化される。','example'=>'VPNトンネルを使うとオーバーヘッドが増えMTUを超えるため、MTUを1400バイトに下げてフラグメントを防ぐ。','difficulty'=>3,'quiz'=>['question'=>'イーサネットの標準的なMTUサイズはどれか？','explanation'=>'イーサネットのデフォルトMTUは1500バイト。ジャンボフレームを使うと最大9000バイトまで拡張できる。','choices'=>[['body'=>'512バイト','is_correct'=>false],['body'=>'1500バイト','is_correct'=>true],['body'=>'4096バイト','is_correct'=>false],['body'=>'65535バイト','is_correct'=>false]]]],
            ['name'=>'OSPF（Open Shortest Path First）','definition'=>'リンク状態型のルーティングプロトコル。ネットワーク全体のトポロジーをダイクストラ法で計算して最短経路を選択する。','example'=>'企業内ネットワークでOSPFを使い、複数ルーター間で自動的に最適ルートを計算・共有する。','difficulty'=>4,'quiz'=>['question'=>'OSPFが使用する経路計算アルゴリズムはどれか？','explanation'=>'OSPFはリンク状態データベース（LSDB）を基にダイクストラのSPF（Shortest Path First）アルゴリズムで最短経路を計算する。','choices'=>[['body'=>'ベルマン-フォード法','is_correct'=>false],['body'=>'ダイクストラ法（SPF）','is_correct'=>true],['body'=>'A*アルゴリズム','is_correct'=>false],['body'=>'貪欲法','is_correct'=>false]]]],
            ['name'=>'マルチキャスト','definition'=>'特定のグループに属する複数の受信者に同時にデータを送信する通信方式。1対多だがブロードキャストと異なり受信者を限定できる。','example'=>'動画ストリーミングや株価配信でマルチキャストを使い、1回の送信で複数クライアントに効率的に配信する。','difficulty'=>3,'quiz'=>['question'=>'マルチキャストとブロードキャストの主な違いはどれか？','explanation'=>'マルチキャストはグループ登録した特定ホストにのみ送信するが、ブロードキャストはサブネット内の全ホストに送信される。','choices'=>[['body'=>'マルチキャストはUDP専用','is_correct'=>false],['body'=>'マルチキャストはグループ登録した受信者のみに届く','is_correct'=>true],['body'=>'マルチキャストはルーターを越えられない','is_correct'=>false],['body'=>'マルチキャストは1対1通信','is_correct'=>false]]]],
            ['name'=>'ブロードキャスト','definition'=>'同一ネットワークセグメント内の全ホストに同時送信する通信方式。宛先アドレスにブロードキャストアドレス（例:255.255.255.255）を使う。','example'=>'ARPリクエストはブロードキャストで送られ、同一ネットワークの全ホストがリクエストを受信する。','difficulty'=>2,'quiz'=>['question'=>'192.168.1.0/24ネットワークのブロードキャストアドレスはどれか？','explanation'=>'ホスト部のビットをすべて1にしたアドレスがブロードキャストアドレス。/24の場合は最終オクテットが255になる。','choices'=>[['body'=>'192.168.1.0','is_correct'=>false],['body'=>'192.168.1.255','is_correct'=>true],['body'=>'192.168.0.255','is_correct'=>false],['body'=>'192.168.1.1','is_correct'=>false]]]],
            ['name'=>'SDN（Software-Defined Networking）','definition'=>'ネットワークの制御プレーンとデータプレーンを分離し、ソフトウェアで集中的にネットワーク制御を行うアーキテクチャ。','example'=>'OpenFlowを使うSDNコントローラーがフロールールをスイッチに配布し、ネットワーク全体を一元管理する。','difficulty'=>4,'quiz'=>['question'=>'SDNの主な特徴はどれか？','explanation'=>'SDNは制御プレーン（ルーティング決定）とデータプレーン（パケット転送）を分離し、コントローラーがネットワーク全体を集中制御する。','choices'=>[['body'=>'全ルーターが独立して経路決定を行う','is_correct'=>false],['body'=>'制御プレーンとデータプレーンを分離してソフトウェア制御する','is_correct'=>true],['body'=>'無線通信に特化した技術','is_correct'=>false],['body'=>'物理機器をなくす技術','is_correct'=>false]]]],
            ['name'=>'ゼロトラストネットワーク','definition'=>'「信頼しない、常に検証する」を原則とするセキュリティモデル。内部ネットワークも外部と同様に全アクセスを検証・認証する。','example'=>'社内ネットワークに繋がっていても全APIリクエストにJWT認証を要求し、位置情報・デバイス状態・ユーザー権限を都度確認する。','difficulty'=>4,'quiz'=>['question'=>'ゼロトラストの基本原則はどれか？','explanation'=>'ゼロトラストは「ネットワーク内だから安全」という前提を捨て、全アクセスを内外問わず認証・認可・検証するセキュリティモデル。','choices'=>[['body'=>'VPNに接続すれば全信頼を与える','is_correct'=>false],['body'=>'内外を問わず常に全アクセスを検証する','is_correct'=>true],['body'=>'ファイアウォールで内部は安全とみなす','is_correct'=>false],['body'=>'社内IPからのアクセスは無条件許可','is_correct'=>false]]]],
            ['name'=>'traceroute','definition'=>'パケットが宛先に到達するまでに経由するルーターを順番に表示するネットワーク診断コマンド。TTLを1から増やしICMPで経路を追跡する。','example'=>'traceroute google.com でパケットが通過するISPや中継ルーターを表示し、遅延が発生している区間を特定する。','difficulty'=>2,'quiz'=>['question'=>'tracerouteが経由ルーターを特定する仕組みはどれか？','explanation'=>'TTLを1から順に増やしてパケットを送り、各ルーターがTTL=0でICMP Time Exceededを返すことで経由ルーターのアドレスを収集する。','choices'=>[['body'=>'DNSの逆引きでルーターを特定する','is_correct'=>false],['body'=>'TTLを1ずつ増やしICMP Time Exceededで経路を追跡する','is_correct'=>true],['body'=>'ARPブロードキャストで経路を探索する','is_correct'=>false],['body'=>'BGPルーティングテーブルを参照する','is_correct'=>false]]]],
            ['name'=>'ネットワークトポロジー','definition'=>'ネットワーク機器の接続形態。バス型・スター型・リング型・メッシュ型などがある。現代のLANは主にスター型。','example'=>'企業LANは中央スイッチにPCを繋ぐスター型が一般的。インターネットの中核はメッシュ型で冗長性を持つ。','difficulty'=>2,'quiz'=>['question'=>'現在の企業LANで最も一般的なトポロジーはどれか？','explanation'=>'スター型トポロジーは中央スイッチに全端末を繋ぐ形式。1本の配線が切れても他に影響なく管理も容易なため主流。','choices'=>[['body'=>'バス型','is_correct'=>false],['body'=>'スター型','is_correct'=>true],['body'=>'リング型','is_correct'=>false],['body'=>'メッシュ型','is_correct'=>false]]]],
            ['name'=>'PPPoE（Point-to-Point Protocol over Ethernet）','definition'=>'イーサネット上でPPPを使い、ISPへの認証付き接続を実現するプロトコル。家庭用ブロードバンド接続でよく使われる。','example'=>'フレッツ光など日本のブロードバンドサービスでPPPoEを使いISPに認証後、グローバルIPが割り当てられる。','difficulty'=>3,'quiz'=>['question'=>'PPPoEが使われる主な場面はどれか？','explanation'=>'PPPoEは家庭・企業のブロードバンドルーターがISPに認証して接続するために使われるプロトコル。','choices'=>[['body'=>'企業内LANの通信','is_correct'=>false],['body'=>'ブロードバンドルーターからISPへの認証付き接続','is_correct'=>true],['body'=>'Wi-Fi接続の認証','is_correct'=>false],['body'=>'Bluetooth通信','is_correct'=>false]]]],
            ['name'=>'帯域幅（Bandwidth）','definition'=>'ネットワーク回線が単位時間あたりに転送できる最大データ量。bps（bits per second）で表す。スループットとは異なる。','example'=>'光回線の帯域幅は最大1Gbpsだが、実際のスループットは700Mbps程度になることが多い。','difficulty'=>1,'quiz'=>['question'=>'帯域幅とスループットの違いとして正しいものはどれか？','explanation'=>'帯域幅は理論上の最大転送速度。スループットは実際の転送速度で、オーバーヘッドや輻輳により帯域幅以下になる。','choices'=>[['body'=>'両者は常に等しい','is_correct'=>false],['body'=>'帯域幅は理論最大値、スループットは実際の転送速度','is_correct'=>true],['body'=>'スループットの方が常に大きい','is_correct'=>false],['body'=>'帯域幅はUDP専用の指標','is_correct'=>false]]]],
            ['name'=>'パケット','definition'=>'ネットワーク上で転送されるデータの基本単位。ヘッダー（宛先・送信元アドレスなど）とペイロード（データ本体）で構成される。','example'=>'1MBのファイルを送信するとき、数百〜数千個のパケットに分割されてそれぞれ独立して経路を通り宛先で再組立される。','difficulty'=>1,'quiz'=>['question'=>'パケットのヘッダーに含まれる情報として正しいものはどれか？','explanation'=>'パケットヘッダーには宛先・送信元IPアドレス・TTL・プロトコル種別などのルーティングに必要な情報が含まれる。','choices'=>[['body'=>'ファイルの中身（コンテンツ）','is_correct'=>false],['body'=>'宛先・送信元アドレスなどのルーティング情報','is_correct'=>true],['body'=>'ユーザーのパスワード','is_correct'=>false],['body'=>'アプリケーションのコード','is_correct'=>false]]]],
            ['name'=>'フレーム','definition'=>'データリンク層（第2層）のデータ転送単位。MACアドレスをヘッダーに持ち、同一ネットワークセグメント内でやり取りされる。','example'=>'PCが同じスイッチに繋がった別PCにデータを送るとき、イーサネットフレームとしてやり取りされる。','difficulty'=>2,'quiz'=>['question'=>'フレームとパケットの違いとして正しいものはどれか？','explanation'=>'フレームはL2（MACアドレスを使う）、パケットはL3（IPアドレスを使う）の転送単位。ルーターを越えるとフレームは更新されるがパケットは維持される。','choices'=>[['body'=>'フレームはL3、パケットはL2の転送単位','is_correct'=>false],['body'=>'フレームはL2（MAC使用）、パケットはL3（IP使用）の転送単位','is_correct'=>true],['body'=>'両者は同じもの','is_correct'=>false],['body'=>'フレームはUDP専用','is_correct'=>false]]]],
            ['name'=>'NTP（Network Time Protocol）','definition'=>'ネットワーク上の機器の時刻を同期するプロトコル。ログ分析・証明書検証・分散システムの一貫性に正確な時刻が必要。','example'=>'全サーバーをNTPサーバー（pool.ntp.org等）と同期させることで、ログの時刻ずれによる障害調査の混乱を防ぐ。','difficulty'=>2,'quiz'=>['question'=>'NTPが重要な理由として最も正しいものはどれか？','explanation'=>'NTPで時刻を同期することで、セキュリティ証明書の期限確認・ログの時系列分析・分散トランザクションの整合性が正確に保たれる。','choices'=>[['body'=>'ネットワーク速度を向上させる','is_correct'=>false],['body'=>'機器の時刻同期でログ整合性や証明書検証を正確にする','is_correct'=>true],['body'=>'IPアドレスを自動割り当てする','is_correct'=>false],['body'=>'ドメイン名を解決する','is_correct'=>false]]]],
            ['name'=>'RADIUS（Remote Authentication Dial-In User Service）','definition'=>'ネットワークアクセスの認証・認可・アカウンティング（AAA）を一元管理するプロトコル。802.1X認証やVPNで使われる。','example'=>'企業Wi-Fiに802.1X認証を導入し、RADIUSサーバーがAD（Active Directory）連携でユーザー認証を行う。','difficulty'=>4,'quiz'=>['question'=>'RADIUSが提供する主な機能の略称はどれか？','explanation'=>'RADIUSはAuthentication（認証）・Authorization（認可）・Accounting（アカウンティング/ログ）のAAAを提供するプロトコル。','choices'=>[['body'=>'VPN・NAT・DNS','is_correct'=>false],['body'=>'認証・認可・アカウンティング（AAA）','is_correct'=>true],['body'=>'暗号化・圧縮・転送','is_correct'=>false],['body'=>'IPアドレス割当・DNS解決・NTP同期','is_correct'=>false]]]],
        ]];
    }

    private function securityTerms(): array
    {
        return ['security' => [
            ['name'=>'トロイの木馬','definition'=>'有益なソフトウェアを装いながら、バックグラウンドで不正な操作（データ窃取・バックドア開設など）を行うマルウェア。','example'=>'「無料ゲーム」として配布されたファイルを実行すると、裏でRAT（遠隔操作ツール）がインストールされる。','difficulty'=>2,'quiz'=>['question'=>'トロイの木馬の特徴として正しいものはどれか？','explanation'=>'トロイの木馬は正規ソフトに見せかけてユーザーに実行させる。ウイルスと違い自己複製せず、ユーザーの操作によって感染する。','choices'=>[['body'=>'ネットワークを通じて自動拡散する','is_correct'=>false],['body'=>'正規ソフトを装いユーザー操作で実行される','is_correct'=>true],['body'=>'ファイルを暗号化して身代金を要求する','is_correct'=>false],['body'=>'ブラウザの広告表示を乗っ取る','is_correct'=>false]]]],
            ['name'=>'バックドア','definition'=>'攻撃者がシステムに将来いつでも侵入できるよう密かに設置する裏口。マルウェア感染後やシステム侵害時に仕込まれることが多い。','example'=>'サーバーに侵入した攻撃者がSSHデーモンを改ざんし、特定パスワードで認証不要にログインできるバックドアを設置する。','difficulty'=>3,'quiz'=>['question'=>'バックドアの検出方法として有効なものはどれか？','explanation'=>'バックドアはファイル整合性チェック（ハッシュ検証）・不審なプロセス/ポートの監視・ログ分析で検出できる。','choices'=>[['body'=>'ウイルス対策ソフトのみで100%検出できる','is_correct'=>false],['body'=>'ファイル整合性チェックや不審なポート/プロセスの監視','is_correct'=>true],['body'=>'パスワードを変更する','is_correct'=>false],['body'=>'ファイアウォールの設置だけで防げる','is_correct'=>false]]]],
            ['name'=>'ルートキット','definition'=>'システムへの不正侵入後に使われ、攻撃者の存在をOSレベルで隠蔽するツール群。プロセス・ファイル・ネットワーク接続を隠す。','example'=>'カーネルレベルのルートキットはOSのシステムコールを改ざんし、特定プロセスがpsコマンドで見えなくなる。','difficulty'=>5,'quiz'=>['question'=>'ルートキットの主な目的はどれか？','explanation'=>'ルートキットは攻撃者の侵入痕跡（マルウェア・バックドア・ログ）をOSレベルで隠蔽し、持続的な潜伏を可能にする。','choices'=>[['body'=>'パスワードを盗む','is_correct'=>false],['body'=>'攻撃者の存在とツールをOSレベルで隠蔽する','is_correct'=>true],['body'=>'ファイルを暗号化する','is_correct'=>false],['body'=>'ネットワークを遮断する','is_correct'=>false]]]],
            ['name'=>'ボットネット','definition'=>'マルウェアに感染し攻撃者（ボットハーダー）の指令に従う多数のコンピューター（ボット）のネットワーク。DDoS・スパム・仮想通貨採掘に使われる。','example'=>'数万台の家庭用ルーターがマルウェアに感染してボットネットを形成し、特定サービスへのDDoS攻撃の踏み台になる。','difficulty'=>3,'quiz'=>['question'=>'ボットネットが悪用される主な攻撃はどれか？','explanation'=>'ボットネットはDDoS攻撃（大量トラフィック）・スパムメール送信・クリック詐欺・クリプトマイニングなどに悪用される。','choices'=>[['body'=>'SQL文の改ざん','is_correct'=>false],['body'=>'DDoS攻撃・スパム送信・クリプトマイニングへの悪用','is_correct'=>true],['body'=>'Webサイトのデザイン改ざん','is_correct'=>false],['body'=>'ファイルシステムの暗号化のみ','is_correct'=>false]]]],
            ['name'=>'キーロガー','definition'=>'キーボード入力を秘密に記録するソフトウェアまたはハードウェア。パスワードやクレジットカード番号の窃取に使われる。','example'=>'オンラインバンキングのログイン情報がキーロガーで盗まれ、第三者に不正送金される被害が発生する。','difficulty'=>2,'quiz'=>['question'=>'キーロガーへの対策として有効なものはどれか？','explanation'=>'仮想キーボード（画面上のクリック入力）や二要素認証は、キーロガーによるパスワード窃取に対して有効な対策となる。','choices'=>[['body'=>'ファイアウォールの設置','is_correct'=>false],['body'=>'仮想キーボードや多要素認証の使用','is_correct'=>true],['body'=>'パスワードを短くする','is_correct'=>false],['body'=>'HTTPSを使用する','is_correct'=>false]]]],
            ['name'=>'バッファオーバーフロー','definition'=>'プログラムが確保したバッファ以上のデータを書き込むことで隣接メモリを上書きし、任意コード実行や異常終了を引き起こす脆弱性。','example'=>'入力値の長さ検証を怠った場合、攻撃者は長い文字列を送りスタックのリターンアドレスを書き換えて任意コードを実行できる。','difficulty'=>4,'quiz'=>['question'=>'バッファオーバーフロー対策として最も基本的なものはどれか？','explanation'=>'入力データの長さを厳密に検証してバッファサイズ以下に制限することが最も基本的な対策。スタック保護（ASLR, Canary）も有効。','choices'=>[['body'=>'HTTPSを使用する','is_correct'=>false],['body'=>'入力値の長さ検証を厳密に行う','is_correct'=>true],['body'=>'パスワードを暗号化する','is_correct'=>false],['body'=>'ファイアウォールで全ポートをブロックする','is_correct'=>false]]]],
            ['name'=>'セッションハイジャック','definition'=>'有効なセッションIDを盗みWebサービスにログイン済みユーザーとして不正アクセスする攻撃手法。','example'=>'非HTTPS通信でCookieが盗聴され、攻撃者が盗んだセッションIDを使い被害者のアカウントにアクセスする。','difficulty'=>3,'quiz'=>['question'=>'セッションハイジャック対策として最も有効なものはどれか？','explanation'=>'HTTPSで通信を暗号化することでセッションIDの盗聴を防ぐのが最も基本的な対策。加えてセッション固定攻撃対策も必要。','choices'=>[['body'=>'パスワードを長くする','is_correct'=>false],['body'=>'HTTPS通信でセッションIDの盗聴を防ぐ','is_correct'=>true],['body'=>'ファイアウォールを設置する','is_correct'=>false],['body'=>'JavaScriptを無効にする','is_correct'=>false]]]],
            ['name'=>'クリックジャッキング','definition'=>'透明なiframeなどを使いユーザーが意図しないボタン・リンクをクリックさせる攻撃。重要操作を気づかせずに実行させる。','example'=>'動画再生ボタンの上に透明な「送金確認」ボタンを重ね、ユーザーが意図せず送金を承認させる。','difficulty'=>3,'quiz'=>['question'=>'クリックジャッキング対策で使うHTTPヘッダーはどれか？','explanation'=>'X-Frame-Options（またはCSPのframe-ancestors）ヘッダーで自サイトのiframe埋め込みを禁止することでクリックジャッキングを防ぐ。','choices'=>[['body'=>'Content-Type','is_correct'=>false],['body'=>'X-Frame-Options','is_correct'=>true],['body'=>'Authorization','is_correct'=>false],['body'=>'Cache-Control','is_correct'=>false]]]],
            ['name'=>'SSRF（Server-Side Request Forgery）','definition'=>'サーバーを踏み台にして内部ネットワーク・クラウドメタデータ・外部サービスへの不正リクエストを送らせる攻撃。','example'=>'URLパラメーターに http://169.254.169.254/latest/meta-data/ を指定し、AWSのメタデータサービスから認証情報を窃取する。','difficulty'=>4,'quiz'=>['question'=>'SSRFが特にクラウド環境で危険な理由はどれか？','explanation'=>'クラウドのインスタンスメタデータサービス（169.254.169.254など）はデフォルトで認証不要なため、SSRFでIAMキーなど機密情報を取得できる。','choices'=>[['body'=>'データベースを改ざんできるから','is_correct'=>false],['body'=>'クラウドメタデータサービスから認証情報を窃取できるから','is_correct'=>true],['body'=>'DDoS攻撃に使えるから','is_correct'=>false],['body'=>'JavaScriptを注入できるから','is_correct'=>false]]]],
            ['name'=>'パストラバーサル','definition'=>'「../」などを含むファイルパスを操作してWebサーバーの意図しないディレクトリ・ファイルにアクセスする攻撃。','example'=>'ファイルダウンロードAPIに?file=../../../etc/passwdを指定してサーバーのパスワードファイルを取得しようとする攻撃。','difficulty'=>3,'quiz'=>['question'=>'パストラバーサル対策として最も適切なものはどれか？','explanation'=>'ユーザー入力のパスを正規化し、許可されたディレクトリ内に限定する（allowlist）ことが最も効果的。../のフィルタリングだけでは迂回される可能性がある。','choices'=>[['body'=>'../を含む入力を文字列で拒否する','is_correct'=>false],['body'=>'パスを正規化して許可ディレクトリ内に限定する','is_correct'=>true],['body'=>'HTTPSを使用する','is_correct'=>false],['body'=>'ファイアウォールで防ぐ','is_correct'=>false]]]],
            ['name'=>'DoS攻撃（Denial of Service）','definition'=>'単一の攻撃元からターゲットに大量リクエストや不正パケットを送り、サービスを使用不能にする攻撃。複数源の場合はDDoS。','example'=>'1台のPCからWebサーバーに数万req/secのHTTPリクエストを送り、サーバーのCPUを100%にして応答不能にする。','difficulty'=>2,'quiz'=>['question'=>'DoS攻撃とDDoS攻撃の違いはどれか？','explanation'=>'DoSは1つの攻撃元から行う。DDoSは複数（Distributed）の踏み台ホストを使うため、送信元IPをブロックしても防御が難しい。','choices'=>[['body'=>'DoSはデータを盗む攻撃','is_correct'=>false],['body'=>'DDoSは複数ホストから分散して攻撃する点がDoSと異なる','is_correct'=>true],['body'=>'DoSは物理的な攻撃','is_correct'=>false],['body'=>'両者は同じ攻撃','is_correct'=>false]]]],
            ['name'=>'RSA暗号','definition'=>'大きな数の素因数分解の困難性を安全性の根拠とする公開鍵暗号方式。鍵長は2048ビット以上が推奨される。','example'=>'TLS/SSLハンドシェイクでRSAを使い、クライアントがサーバーの公開鍵でセッション鍵を暗号化して安全に共有する。','difficulty'=>4,'quiz'=>['question'=>'RSA暗号の安全性の根拠はどれか？','explanation'=>'RSAは大きな数（例：2048ビット整数）の素因数分解が計算上困難であることを安全性の根拠とする公開鍵暗号アルゴリズム。','choices'=>[['body'=>'同じ鍵で暗号化・復号するため','is_correct'=>false],['body'=>'大きな数の素因数分解が計算上困難であること','is_correct'=>true],['body'=>'量子コンピューターを使うから','is_correct'=>false],['body'=>'ハッシュ関数が一方向性を持つから','is_correct'=>false]]]],
            ['name'=>'ポートスキャン','definition'=>'対象ホストのどのポートが開いているかを調べる技術。Nmapが代表的ツール。攻撃者の偵察にも、セキュリティ診断にも使われる。','example'=>'nmap -sV 192.168.1.1 でホストの開放ポートとサービスバージョンを調べ、脆弱なサービスがないか確認する。','difficulty'=>3,'quiz'=>['question'=>'ポートスキャンに使われる代表的なツールはどれか？','explanation'=>'Nmapはオープンソースのポートスキャン・ネットワーク探索ツール。セキュリティ診断と攻撃者の偵察の両方に広く使われる。','choices'=>[['body'=>'Wireshark','is_correct'=>false],['body'=>'Nmap','is_correct'=>true],['body'=>'Metasploit','is_correct'=>false],['body'=>'Burp Suite','is_correct'=>false]]]],
            ['name'=>'セキュアコーディング','definition'=>'セキュリティ上の欠陥を作り込まないようにするコーディング実践。入力検証・出力エスケープ・認証・エラーハンドリングなどの原則がある。','example'=>'ユーザー入力を必ずバリデーションし、DBへはプリペアドステートメントで渡し、エラーメッセージに内部情報を含めないなど。','difficulty'=>3,'quiz'=>['question'=>'セキュアコーディングの原則として誤っているものはどれか？','explanation'=>'エラーメッセージに詳細なスタックトレースやDB構造を含めると攻撃者のヒントになる。エラーはログに記録し、ユーザーには汎用メッセージを返す。','choices'=>[['body'=>'入力値を必ず検証する','is_correct'=>false],['body'=>'エラーメッセージに詳細な内部情報を含める','is_correct'=>true],['body'=>'DBアクセスにプリペアドステートメントを使う','is_correct'=>false],['body'=>'認証・認可を適切に実装する','is_correct'=>false]]]],
            ['name'=>'脅威インテリジェンス','definition'=>'既知の攻撃者・マルウェア・IoC（侵害の指標）などの脅威情報を収集・分析・共有してセキュリティ対策に活用すること。','example'=>'ISACやMISPを通じて他組織と脅威情報を共有し、新たな攻撃キャンペーンのIPアドレスをSIEMのルールに追加する。','difficulty'=>4,'quiz'=>['question'=>'脅威インテリジェンスにおけるIoC（Indicator of Compromise）の例はどれか？','explanation'=>'IoCは侵害の証拠となる指標で、マルウェアのハッシュ値・攻撃者の既知IPアドレス・悪意あるドメイン名などが該当する。','choices'=>[['body'=>'セキュリティポリシー文書','is_correct'=>false],['body'=>'マルウェアのハッシュ値や攻撃者の既知IPアドレス','is_correct'=>true],['body'=>'脆弱性スキャンレポート','is_correct'=>false],['body'=>'社員のアクセスログ','is_correct'=>false]]]],
            ['name'=>'エクスプロイト（Exploit）','definition'=>'脆弱性を悪用して不正なコードを実行したり権限昇格を行うコード・技術。PoC（概念実証）コードとして公開されることもある。','example'=>'CVE-2021-44228（Log4Shell）の公開翌日には、脆弱性を悪用するエクスプロイトコードがGitHubに多数公開された。','difficulty'=>4,'quiz'=>['question'=>'ゼロデイエクスプロイトとは何か？','explanation'=>'ゼロデイエクスプロイトはパッチが未公開の脆弱性（ゼロデイ）を悪用する攻撃コード。防御策がなく特に危険。','choices'=>[['body'=>'0行コードの攻撃手法','is_correct'=>false],['body'=>'修正パッチが未公開の脆弱性を悪用する攻撃コード','is_correct'=>true],['body'=>'0円で入手できる攻撃ツール','is_correct'=>false],['body'=>'深夜0時に実行される攻撃','is_correct'=>false]]]],
            ['name'=>'セキュリティ監査','definition'=>'組織のセキュリティポリシー・管理策・システムの実装状況を体系的に評価・検証するプロセス。コンプライアンス確認にも使われる。','example'=>'年次のセキュリティ監査でアクセス権の棚卸しを実施し、退職者のアカウントが残っていないか確認する。','difficulty'=>3,'quiz'=>['question'=>'セキュリティ監査の主な目的はどれか？','explanation'=>'セキュリティ監査はポリシー遵守状況・技術的管理策の有効性・リスクを客観的に評価してギャップや改善点を特定する。','choices'=>[['body'=>'新しいセキュリティ製品を販売する','is_correct'=>false],['body'=>'セキュリティポリシーの遵守状況とリスクを客観的に評価する','is_correct'=>true],['body'=>'ハッキングを実演する','is_correct'=>false],['body'=>'パスワードを自動生成する','is_correct'=>false]]]],
            ['name'=>'XXE（XML External Entity）攻撃','definition'=>'XML外部エンティティ参照を悪用し、サーバーのローカルファイル読み込みやSSRFを引き起こす攻撃手法。','example'=>'XMLパーサーが外部エンティティを処理する設定の場合、<!ENTITY xxe SYSTEM "file:///etc/passwd">でパスワードファイルを読み取られる。','difficulty'=>4,'quiz'=>['question'=>'XXE攻撃の対策として最も適切なものはどれか？','explanation'=>'XMLパーサーで外部エンティティとDTD処理を無効化（FEATURE_DISALLOW_DOCTYPE_DECL等）することがXXE対策の基本。','choices'=>[['body'=>'SQLプリペアドステートメントを使う','is_correct'=>false],['body'=>'XMLパーサーの外部エンティティ処理を無効化する','is_correct'=>true],['body'=>'HTTPSを使用する','is_correct'=>false],['body'=>'入力をHTMLエスケープする','is_correct'=>false]]]],
            ['name'=>'OSINTオープンソースインテリジェンス','definition'=>'公開情報（SNS・Webサイト・公的記録・技術文書等）を収集・分析して情報を得る情報収集手法。攻撃者の偵察やセキュリティ研究に使われる。','example'=>'ShodanでインターネットにさらされたDBサーバーを発見したり、LinkedInで企業の技術スタックや社員を調査する。','difficulty'=>3,'quiz'=>['question'=>'OSINTで使われる代表的なツールはどれか？','explanation'=>'Shodanはインターネットにさらされたデバイスやサービスを検索できるOSINTツール。ペネトレーションテストの偵察フェーズで使われる。','choices'=>[['body'=>'Metasploit','is_correct'=>false],['body'=>'Shodan','is_correct'=>true],['body'=>'Wireshark','is_correct'=>false],['body'=>'iptables','is_correct'=>false]]]],
            ['name'=>'スパイウェア','definition'=>'ユーザーの知らない間にインストールされ、個人情報・閲覧履歴・パスワードなどを収集して外部に送信するマルウェア。','example'=>'フリーソフトにバンドルされたスパイウェアがブラウザの履歴・フォーム入力を収集し広告業者に売却する。','difficulty'=>2,'quiz'=>['question'=>'スパイウェアとアドウェアの違いはどれか？','explanation'=>'スパイウェアは情報収集が目的。アドウェアは不要な広告を表示することが目的。両者がセットになることも多い。','choices'=>[['body'=>'スパイウェアはデータを暗号化する','is_correct'=>false],['body'=>'スパイウェアは情報収集、アドウェアは広告表示が主目的','is_correct'=>true],['body'=>'両者は全く同じマルウェア','is_correct'=>false],['body'=>'スパイウェアはネットワークを介して拡散する','is_correct'=>false]]]],
        ]];
    }

    private function databaseTerms(): array
    {
        return ['database' => [
            ['name'=>'ORDER BY','definition'=>'SELECT結果を指定した列の値で昇順（ASC）または降順（DESC）に並び替える句。複数列を指定した優先度ソートも可能。','example'=>'SELECT * FROM products ORDER BY price DESC, name ASC; で価格降順・同価格は名前昇順でソートする。','difficulty'=>1,'quiz'=>['question'=>'ORDER BY price DESCの意味はどれか？','explanation'=>'DESCはDescending（降順）を意味し、priceの高い順に並び替える。ASC（Ascending）は低い順（デフォルト）。','choices'=>[['body'=>'価格の低い順に並ぶ','is_correct'=>false],['body'=>'価格の高い順に並ぶ','is_correct'=>true],['body'=>'価格列を削除する','is_correct'=>false],['body'=>'重複を除外する','is_correct'=>false]]]],
            ['name'=>'HAVING句','definition'=>'GROUP BYでグループ化した結果に対して条件でフィルタリングする句。集計関数を条件に使えるWHEREの後処理版。','example'=>'SELECT category_id, COUNT(*) FROM products GROUP BY category_id HAVING COUNT(*) >= 5; で商品5件以上のカテゴリのみ取得。','difficulty'=>3,'quiz'=>['question'=>'HAVINGとWHEREの違いはどれか？','explanation'=>'WHERE はグループ化前の個別行のフィルタリング。HAVINGはGROUP BY後にグループ単位で集計値を条件にフィルタリングする。','choices'=>[['body'=>'HAVINGはJOIN後、WHEREはJOIN前に適用される','is_correct'=>false],['body'=>'WHEREは行単位、HAVINGはGROUP BY後のグループ単位のフィルタリング','is_correct'=>true],['body'=>'両者は全く同じ機能','is_correct'=>false],['body'=>'HAVINGはSELECT句にのみ使える','is_correct'=>false]]]],
            ['name'=>'NULL値','definition'=>'値が存在しない・不明であることを表すSQL上の特殊な状態。NULLとの比較にはIS NULL / IS NOT NULLを使う必要がある。','example'=>'WHERE email IS NULL でメール未登録のユーザーを検索する。「WHERE email = NULL」は常にFALSEになるため使えない。','difficulty'=>2,'quiz'=>['question'=>'NULLとの比較で正しい書き方はどれか？','explanation'=>'NULLは= や !=で比較できない（常にUNKNOWNになる）。IS NULL / IS NOT NULLを使うのが正しい。','choices'=>[['body'=>'WHERE col = NULL','is_correct'=>false],['body'=>'WHERE col IS NULL','is_correct'=>true],['body'=>'WHERE col == NULL','is_correct'=>false],['body'=>'WHERE NULL(col)','is_correct'=>false]]]],
            ['name'=>'AUTO_INCREMENT（自動採番）','definition'=>'INSERTのたびに列の値を自動的にインクリメントする機能。主に主キーの一意な整数ID生成に使われる。','example'=>'id INT AUTO_INCREMENT PRIMARY KEY と定義すると、INSERT時にidが1,2,3...と自動採番される。','difficulty'=>1,'quiz'=>['question'=>'AUTO_INCREMENTの主な用途はどれか？','explanation'=>'AUTO_INCREMENTは主キーの整数IDを自動連番で生成するために使われる。手動でIDを指定する必要がなくなる。','choices'=>[['body'=>'列の値を自動的に暗号化する','is_correct'=>false],['body'=>'主キーの整数IDを自動連番で生成する','is_correct'=>true],['body'=>'削除された行を自動的に補完する','is_correct'=>false],['body'=>'外部キー参照を自動設定する','is_correct'=>false]]]],
            ['name'=>'データ型（SQL）','definition'=>'DBの列に格納できる値の種類を定義する。INT・VARCHAR・TEXT・DATE・BOOLEAN・JSON・DECIMALなど多数ある。','example'=>'price DECIMAL(10,2) で最大10桁・小数2桁の金額を格納する。TEXTは可変長長文、VARCHARは最大長指定の可変長文字列。','difficulty'=>2,'quiz'=>['question'=>'金額（例:1234.56）を格納するのに最適なデータ型はどれか？','explanation'=>'DECIMALは固定精度小数点で丸め誤差がない。FLOATは浮動小数点なので金額計算で誤差が生じる場合がある。','choices'=>[['body'=>'FLOAT','is_correct'=>false],['body'=>'DECIMAL','is_correct'=>true],['body'=>'VARCHAR','is_correct'=>false],['body'=>'INT','is_correct'=>false]]]],
            ['name'=>'B木インデックス（B-Treeインデックス）','definition'=>'ほとんどのRDBMSで標準採用されるインデックス構造。バランス木で等値・範囲検索・ソートに効率的なO(log n)アクセスを実現する。','example'=>'usersテーブルのcreated_at列にB木インデックスを張ると、日付範囲での絞り込みが高速になる。','difficulty'=>4,'quiz'=>['question'=>'B木インデックスが効果的なクエリはどれか？','explanation'=>'B木インデックスは等値検索（=）・範囲検索（BETWEEN, >, <）・ORDER BYに効果的。LIKEの後方一致（%word）には効かない。','choices'=>[['body'=>'LIKE \'%検索語\'（後方一致）','is_correct'=>false],['body'=>'範囲検索（BETWEEN, >, <）や等値検索（=）','is_correct'=>true],['body'=>'集計関数SUM()/COUNT()のみ','is_correct'=>false],['body'=>'全文検索','is_correct'=>false]]]],
            ['name'=>'PostgreSQL','definition'=>'高機能なオープンソースのRDBMS。JSON・配列・地理情報などの高度なデータ型・ウィンドウ関数・CTE・全文検索などを持つ。','example'=>'Laravel + PostgreSQLでJSONB型を使い、構造化されたメタデータを格納してJSONPath演算子で効率的に検索する。','difficulty'=>2,'quiz'=>['question'=>'PostgreSQLが他のRDBMSと比べて優れている特徴の例はどれか？','explanation'=>'PostgreSQLはJSONB型（バイナリJSON）・配列型・地理情報（PostGIS）・高度なウィンドウ関数など豊富なデータ型と機能を持つ。','choices'=>[['body'=>'処理速度が常に最速','is_correct'=>false],['body'=>'JSONB・配列・地理情報など高度なデータ型をネイティブサポート','is_correct'=>true],['body'=>'インストールが不要','is_correct'=>false],['body'=>'SQLを使わない','is_correct'=>false]]]],
            ['name'=>'CRUD操作','definition'=>'データベースの基本4操作の略称。Create（INSERT）・Read（SELECT）・Update（UPDATE）・Delete（DELETE）。Webアプリの基本機能。','example'=>'ユーザー登録=Create、プロフィール表示=Read、情報更新=Update、退会=DeleteのCRUDでAPIを設計する。','difficulty'=>1,'quiz'=>['question'=>'CRUD操作のRに対応するSQLコマンドはどれか？','explanation'=>'R=Read（読み取り）はSELECT文に対応する。C=INSERT、U=UPDATE、D=DELETEに対応する。','choices'=>[['body'=>'INSERT','is_correct'=>false],['body'=>'SELECT','is_correct'=>true],['body'=>'UPDATE','is_correct'=>false],['body'=>'DELETE','is_correct'=>false]]]],
            ['name'=>'GRANT / REVOKE','definition'=>'DBユーザーに権限を付与（GRANT）・取り消す（REVOKE）SQL文。最小権限の原則を実現するアクセス制御の基本。','example'=>'GRANT SELECT, INSERT ON app.users TO app_user; でapp_userにusersテーブルのSELECTとINSERTのみ許可する。','difficulty'=>3,'quiz'=>['question'=>'GRANTの説明として正しいものはどれか？','explanation'=>'GRANTはDBユーザー/ロールに指定したオブジェクト（テーブル等）への権限（SELECT等）を付与するSQL文。REVOKEは逆の取り消し。','choices'=>[['body'=>'ユーザーをDBに作成する','is_correct'=>false],['body'=>'ユーザーに権限を付与する','is_correct'=>true],['body'=>'テーブルを削除する','is_correct'=>false],['body'=>'パスワードを変更する','is_correct'=>false]]]],
            ['name'=>'バックアップとリストア','definition'=>'DBのデータを定期的に保存（バックアップ）し、障害・誤操作時に復元（リストア）する手順。RTO・RPOを考慮して戦略を設計する。','example'=>'mysqldumpで日次バックアップを取りS3に保存。障害時は最新バックアップをリストアし、WALログで障害直前まで復旧する。','difficulty'=>2,'quiz'=>['question'=>'フルバックアップと差分バックアップの違いはどれか？','explanation'=>'フルバックアップは全データを毎回保存。差分バックアップは前回フルバックアップ以降の変更分のみ保存。差分の方がサイズが小さく高速だがリストアにフルと差分の両方が必要。','choices'=>[['body'=>'差分バックアップは全データを毎回保存する','is_correct'=>false],['body'=>'差分バックアップは前回フルバックアップ以降の変更分のみ保存','is_correct'=>true],['body'=>'両者はリストア手順が同じ','is_correct'=>false],['body'=>'フルバックアップは差分より容量が少ない','is_correct'=>false]]]],
            ['name'=>'行ロック（Row Lock）','definition'=>'トランザクションが特定行のみをロックする粒度の細かいロック。テーブルロックと比べて他トランザクションの待機を最小化できる。','example'=>'InnoDB（MySQL）はデフォルトで行ロックを使うため、同一テーブルの別行を同時に更新するトランザクションが並行実行できる。','difficulty'=>4,'quiz'=>['question'=>'行ロックがテーブルロックより優れている点はどれか？','explanation'=>'行ロックはロック粒度が細かいため、別行への同時アクセスを許可し並行性が高い。テーブルロックは対象行以外もロックするため競合が多い。','choices'=>[['body'=>'実装が簡単','is_correct'=>false],['body'=>'別行へのアクセスを許可し同時実行性が高い','is_correct'=>true],['body'=>'デッドロックが発生しない','is_correct'=>false],['body'=>'全てのDBMSに標準搭載されている','is_correct'=>false]]]],
            ['name'=>'UNION','definition'=>'複数のSELECT文の結果を縦に結合する演算子。UNION ALL は重複を含むすべての行を、UNION は重複を除いた結果を返す。','example'=>'SELECT name FROM employees UNION SELECT name FROM contractors; で社員と業務委託を一括取得する。','difficulty'=>2,'quiz'=>['question'=>'UNIONとUNION ALLの違いはどれか？','explanation'=>'UNIONは重複行を自動排除（DISTINCTと同等の処理をする）するためコストがかかる。UNION ALLは全行を結合して重複も保持し、高速。','choices'=>[['body'=>'UNIONは列を横方向に結合する','is_correct'=>false],['body'=>'UNIONは重複を除去、UNION ALLは重複も含む全行を返す','is_correct'=>true],['body'=>'UNION ALLの方が遅い','is_correct'=>false],['body'=>'両者はJOINと同じ動作','is_correct'=>false]]]],
            ['name'=>'CHECK制約','definition'=>'列の値が特定の条件を満たすことを強制するDB制約。条件を満たさないINSERT/UPDATEはエラーになる。','example'=>'age INT CHECK(age >= 0 AND age <= 150) で年齢が0〜150の範囲外の値を拒否する。','difficulty'=>2,'quiz'=>['question'=>'CHECK制約の目的はどれか？','explanation'=>'CHECK制約はビジネスルールをDB層で強制し、不正な値がテーブルに入らないことを保証する整合性制約の一種。','choices'=>[['body'=>'列の値を自動変換する','is_correct'=>false],['body'=>'列の値が指定した条件を満たすことを強制する','is_correct'=>true],['body'=>'外部テーブルへの参照を管理する','is_correct'=>false],['body'=>'インデックスを自動作成する','is_correct'=>false]]]],
            ['name'=>'カスケード削除（CASCADE）','definition'=>'外部キー制約でON DELETE CASCADEを設定すると、参照先の行が削除されたとき参照元の関連行も自動削除される。','example'=>'ユーザーを削除すると、ON DELETE CASCADEにより関連する注文・コメント・プロフィール行が自動的に全削除される。','difficulty'=>3,'quiz'=>['question'=>'ON DELETE CASCADE のリスクとして正しいものはどれか？','explanation'=>'CASCADEは便利だが誤って親レコードを削除すると、連鎖的に大量の子レコードが自動削除されてしまう危険がある。','choices'=>[['body'=>'外部キー制約が無効になる','is_correct'=>false],['body'=>'親行削除時に関連する子行も連鎖削除されるリスクがある','is_correct'=>true],['body'=>'削除処理が遅くなる','is_correct'=>false],['body'=>'カーソルが自動的に閉じる','is_correct'=>false]]]],
            ['name'=>'一時テーブル（Temporary Table）','definition'=>'セッション内またはトランザクション内のみ存在し、セッション終了時に自動削除されるテーブル。複雑な中間計算に使われる。','example'=>'長大な集計クエリを一時テーブルに格納してステップを分け、最終的にJOINで結果を取得してパフォーマンスを改善する。','difficulty'=>3,'quiz'=>['question'=>'一時テーブルが通常テーブルと異なる点はどれか？','explanation'=>'一時テーブルはセッション終了時（またはトランザクション終了時）に自動的に削除され、他のセッションからは見えない。','choices'=>[['body'=>'インデックスを作成できない','is_correct'=>false],['body'=>'セッション終了時に自動削除され他セッションからは見えない','is_correct'=>true],['body'=>'SELECT文しか使えない','is_correct'=>false],['body'=>'常にメモリ上に保存される','is_correct'=>false]]]],
            ['name'=>'フルテキスト検索（Full-Text Search）','definition'=>'テキストデータを単語（トークン）に分割してインデックス化し、LIKE検索より高速に全文一致・関連性スコアで検索する機能。','example'=>'MySQLのMATCH AGAINST でブログ記事の本文を全文検索し、関連度スコア順に結果を並べる。','difficulty'=>3,'quiz'=>['question'=>'フルテキスト検索がLIKE検索より優れている点はどれか？','explanation'=>'フルテキスト検索は事前にインデックス化されるため大量テキストでも高速。関連度スコア・形態素解析・ストップワード除去などの高度な検索も可能。','choices'=>[['body'=>'全てのデータ型に使える','is_correct'=>false],['body'=>'大量テキストでも高速・関連度スコアで検索できる','is_correct'=>true],['body'=>'JOINが不要になる','is_correct'=>false],['body'=>'外部キー制約なしに使える','is_correct'=>false]]]],
            ['name'=>'カーソル（DB）','definition'=>'SELECT結果セットの行を1行ずつ処理するためのDB機能。ストアドプロシージャ内でループ処理に使われるが、セット操作より低速。','example'=>'給与計算ストアドプロシージャ内でカーソルを使い、全社員レコードを1件ずつ処理して個別計算する。','difficulty'=>4,'quiz'=>['question'=>'DBカーソルの注意点として正しいものはどれか？','explanation'=>'カーソルは1行ずつ処理するためセット操作（JOINやサブクエリ）より一般的に低速。大量データ処理には非推奨。','choices'=>[['body'=>'カーソルはセット操作より常に高速','is_correct'=>false],['body'=>'1行ずつ処理するためセット操作より一般的に低速','is_correct'=>true],['body'=>'トランザクションの代替として使える','is_correct'=>false],['body'=>'読み取り専用でしか使えない','is_correct'=>false]]]],
            ['name'=>'SQLite','definition'=>'サーバー不要でファイル1つにDBを格納する組み込み型RDBMS。モバイルアプリ・テスト・小規模アプリに広く使われる。','example'=>'LaravelのローカルDevでDB_CONNECTION=sqliteを設定し、database.sqliteファイル1つで開発を進める。','difficulty'=>1,'quiz'=>['question'=>'SQLiteが他のRDBMS（MySQL, PostgreSQL）と大きく異なる点はどれか？','explanation'=>'SQLiteはサーバープロセスが不要でファイル1つでデータベースを実現する。インストール不要で組み込み用途に最適だが同時書き込み性能は低い。','choices'=>[['body'=>'SQLを使わないNoSQL','is_correct'=>false],['body'=>'サーバー不要でファイル1つでDBを実現する','is_correct'=>true],['body'=>'クラウドでのみ動作する','is_correct'=>false],['body'=>'トランザクションをサポートしない','is_correct'=>false]]]],
            ['name'=>'MySQL','definition'=>'世界で最も広く使われるOSSのRDBMSの1つ。WebアプリのLAMPスタックでDEFACTOスタンダード。MariaDBはMySQLのフォーク。','example'=>'WordPressはMySQLを標準DBとして使用。InnoDBストレージエンジンによりACID準拠のトランザクションをサポートする。','difficulty'=>1,'quiz'=>['question'=>'MySQLのデフォルトのストレージエンジンはどれか？','explanation'=>'MySQL 5.5以降のデフォルトはInnoDBで、外部キー・行ロック・MVCC・ACIDトランザクションをサポートする。MyISAMは旧デフォルトで読み取りが速いがトランザクション非対応。','choices'=>[['body'=>'MyISAM','is_correct'=>false],['body'=>'InnoDB','is_correct'=>true],['body'=>'Memory','is_correct'=>false],['body'=>'NDB','is_correct'=>false]]]],
            ['name'=>'データベース設計','definition'=>'要件に基づきER図・正規化・テーブル定義・インデックス設計などを行いデータモデルを構築するプロセス。','example'=>'ECサイトでユーザー・商品・注文・カテゴリのエンティティと関係を整理してER図を作成し、正規化してテーブルを設計する。','difficulty'=>3,'quiz'=>['question'=>'データベース設計において正規化を行う主な目的はどれか？','explanation'=>'正規化によりデータの冗長性を排除し、更新異常（挿入・削除・変更異常）を防ぎ、データ整合性を維持する。','choices'=>[['body'=>'クエリ速度を最大化する','is_correct'=>false],['body'=>'データの冗長性排除と更新異常の防止','is_correct'=>true],['body'=>'テーブル数を最大化する','is_correct'=>false],['body'=>'インデックスを自動生成する','is_correct'=>false]]]],
        ]];
    }

    private function algorithmTerms(): array
    {
        return ['algorithm' => [
            ['name'=>'選択ソート（Selection Sort）','definition'=>'未ソート部分から最小値を選んでソート済み末尾と交換する単純ソートアルゴリズム。常にO(n²)で少ないスワップ数が特徴。','example'=>'[5,3,1,4,2]→最小値1を先頭と交換→[1,3,5,4,2]→次の最小値2を交換…と繰り返す。','difficulty'=>2,'quiz'=>['question'=>'選択ソートの時間計算量はどれか？','explanation'=>'選択ソートは未ソート部分の最小値探索にO(n)×n回=常にO(n²)かかる。最良・最悪・平均すべてO(n²)。','choices'=>[['body'=>'O(n log n)','is_correct'=>false],['body'=>'O(n²)','is_correct'=>true],['body'=>'O(n)','is_correct'=>false],['body'=>'O(log n)','is_correct'=>false]]]],
            ['name'=>'挿入ソート（Insertion Sort）','definition'=>'各要素を正しい位置に挿入していく単純ソート。ほぼソート済みのデータに対してO(n)に近い高速性を示す安定ソート。','example'=>'トランプのカードを手に取るたびに正しい位置に差し込む操作が挿入ソートのイメージ。','difficulty'=>2,'quiz'=>['question'=>'挿入ソートがほぼソート済みデータに強い理由はどれか？','explanation'=>'ほぼソート済みの場合、各要素の挿入位置が近く比較・移動回数が少なくなるため、最良O(n)に近い性能を発揮する。','choices'=>[['body'=>'要素数に関係なく常にO(n)','is_correct'=>false],['body'=>'ほぼソート済みなら比較・移動回数が少なくO(n)に近くなる','is_correct'=>true],['body'=>'並列処理で実行するから','is_correct'=>false],['body'=>'ハッシュ値を使うから','is_correct'=>false]]]],
            ['name'=>'バブルソート（Bubble Sort）','definition'=>'隣接要素を比較して交換を繰り返す最も単純なソート。常にO(n²)で実用的ではないが教育目的でよく使われる。','example'=>'[5,3,1]→(5,3)比較→交換[3,5,1]→(5,1)比較→交換[3,1,5]→次のパス[1,3,5]で完了。','difficulty'=>2,'quiz'=>['question'=>'バブルソートが実際のシステムで使われにくい理由はどれか？','explanation'=>'バブルソートはO(n²)の時間計算量で大量データに対して非常に低速。実用ではO(n log n)のクイックソートやマージソートが使われる。','choices'=>[['body'=>'安定ソートでないから','is_correct'=>false],['body'=>'O(n²)で大量データに対して非常に低速だから','is_correct'=>true],['body'=>'整数データにしか使えないから','is_correct'=>false],['body'=>'再帰が必要だから','is_correct'=>false]]]],
            ['name'=>'ヒープソート（Heap Sort）','definition'=>'最大ヒープを構築しルートを末尾と交換しながらソートするアルゴリズム。常にO(n log n)かつO(1)の追加メモリで動作する。','example'=>'n個の要素でmax-heapを構築（O(n)）後、ルート取り出し→ヒープ再構成（O(log n)）をn回繰り返す。','difficulty'=>3,'quiz'=>['question'=>'ヒープソートがマージソートに比べて優れている点はどれか？','explanation'=>'ヒープソートは追加メモリがO(1)（インプレース）で動作する。マージソートはO(n)の追加メモリが必要。どちらもO(n log n)。','choices'=>[['body'=>'マージソートより常に速い','is_correct'=>false],['body'=>'追加メモリO(1)でインプレースソートできる','is_correct'=>true],['body'=>'安定ソートである','is_correct'=>false],['body'=>'ランダムデータで常に最速','is_correct'=>false]]]],
            ['name'=>'最小全域木（MST: Minimum Spanning Tree）','definition'=>'重み付き無向グラフの全ノードを連結する辺のうち、合計コストが最小となる木。クラスカル法やプリム法で求める。','example'=>'複数都市を光ファイバーで接続する最小コストの配線計画を最小全域木として求める。','difficulty'=>4,'quiz'=>['question'=>'最小全域木を求める代表的なアルゴリズムはどれか？','explanation'=>'クラスカル法（辺を重み順にソートして閉路を作らない辺を追加）とプリム法（始点から最短辺を貪欲に追加）がMSTの代表アルゴリズム。','choices'=>[['body'=>'ダイクストラ法とBFS','is_correct'=>false],['body'=>'クラスカル法とプリム法','is_correct'=>true],['body'=>'DFSとトポロジカルソート','is_correct'=>false],['body'=>'動的計画法と分割統治法','is_correct'=>false]]]],
            ['name'=>'クラスカル法','definition'=>'辺を重み昇順にソートし、閉路を作らない辺を順に追加して最小全域木を求める貪欲アルゴリズム。Union-Find構造で閉路判定する。','example'=>'6都市接続問題の5辺を重み順に試し、閉路を作る辺をスキップしながら4辺を選びMSTを完成させる。','difficulty'=>4,'quiz'=>['question'=>'クラスカル法で閉路を効率よく判定するデータ構造はどれか？','explanation'=>'クラスカル法はUnion-Find（素集合データ構造）を使い、各辺を追加する際に両端点が同じ集合（閉路を形成）でないかO(α(n))で判定する。','choices'=>[['body'=>'スタック','is_correct'=>false],['body'=>'Union-Find（素集合データ構造）','is_correct'=>true],['body'=>'ハッシュテーブル','is_correct'=>false],['body'=>'二分木','is_correct'=>false]]]],
            ['name'=>'ベルマン-フォード法','definition'=>'負の重みを持つ辺がある重み付きグラフでも単一始点最短経路を求められるアルゴリズム。O(VE)で負閉路も検出できる。','example'=>'通貨裁定取引で負の重みに相当する為替ルートを含むグラフの最短経路をベルマン-フォードで計算する。','difficulty'=>4,'quiz'=>['question'=>'ベルマン-フォード法がダイクストラ法と異なる点はどれか？','explanation'=>'ベルマン-フォードは負の重みの辺があるグラフでも正しく動作し、負閉路の検出も可能。ダイクストラは非負の重みが必要。','choices'=>[['body'=>'より高速（O(V log V)）で動作する','is_correct'=>false],['body'=>'負の重みがある辺でも正しく動作し負閉路を検出できる','is_correct'=>true],['body'=>'無向グラフ専用','is_correct'=>false],['body'=>'BFSを内部で使用する','is_correct'=>false]]]],
            ['name'=>'フロイド-ワーシャル法','definition'=>'全頂点ペア間の最短経路を動的計画法で求めるアルゴリズム。O(V³)で小〜中規模グラフに適する。負の重みにも対応。','example'=>'都市間の全移動コスト行列をフロイド-ワーシャルで計算し、どの2都市間でも最短経路を即座に参照できるようにする。','difficulty'=>5,'quiz'=>['question'=>'フロイド-ワーシャル法の時間計算量はどれか？','explanation'=>'フロイド-ワーシャルは三重ループ（i,j,kそれぞれV個）で全頂点ペアを処理するためO(V³)。全頂点ペアの最短経路を一度に求められる。','choices'=>[['body'=>'O(V²)','is_correct'=>false],['body'=>'O(V³)','is_correct'=>true],['body'=>'O(VE)','is_correct'=>false],['body'=>'O(V log V)','is_correct'=>false]]]],
            ['name'=>'最長共通部分列（LCS）','definition'=>'2つの文字列に共通する最も長い部分列（非連続でも可）の長さを求める動的計画法の典型問題。O(mn)で解ける。','example'=>'"ABCDE"と"ACE"のLCSは"ACE"（長さ3）。diffコマンドやDNA比較でLCSが使われる。','difficulty'=>4,'quiz'=>['question'=>'LCSの計算に使われるアルゴリズム技法はどれか？','explanation'=>'LCSはメモ化+再帰か動的計画法（DP表）でO(mn)（m,nが文字列長）で解く。分割統治単独では最適でない。','choices'=>[['body'=>'貪欲法','is_correct'=>false],['body'=>'動的計画法（DP）','is_correct'=>true],['body'=>'DFS','is_correct'=>false],['body'=>'二分探索','is_correct'=>false]]]],
            ['name'=>'ユークリッドの互除法','definition'=>'2つの整数の最大公約数（GCD）を求める効率的なアルゴリズム。gcd(a,b)=gcd(b, a mod b)で再帰的に計算する。','example'=>'gcd(48,18)=gcd(18,12)=gcd(12,6)=gcd(6,0)=6。最大公約数は6。','difficulty'=>2,'quiz'=>['question'=>'ユークリッドの互除法でgcd(56,42)の結果はどれか？','explanation'=>'gcd(56,42)=gcd(42,14)=gcd(14,0)=14。56と42の最大公約数は14。','choices'=>[['body'=>'7','is_correct'=>false],['body'=>'14','is_correct'=>true],['body'=>'6','is_correct'=>false],['body'=>'28','is_correct'=>false]]]],
            ['name'=>'エラトステネスの篩','definition'=>'素数を列挙する古典的なアルゴリズム。2から始め、各素数の倍数を消去することでn以下の素数をO(n log log n)で求める。','example'=>'1〜20の素数：2から始め2の倍数(4,6,8...)を消去→3の倍数消去→5...と続けると{2,3,5,7,11,13,17,19}が残る。','difficulty'=>3,'quiz'=>['question'=>'エラトステネスの篩の時間計算量はどれか？','explanation'=>'エラトステネスの篩はO(n log log n)で動作する。各素数pの倍数の消去にかかる時間の総和がlog log nになることによる。','choices'=>[['body'=>'O(n²)','is_correct'=>false],['body'=>'O(n log log n)','is_correct'=>true],['body'=>'O(n)','is_correct'=>false],['body'=>'O(n log n)','is_correct'=>false]]]],
            ['name'=>'ユニオンファインド（Union-Find）','definition'=>'要素をグループ（集合）に分類し、2要素が同じ集合か判定（Find）・2集合を統合（Union）する効率的なデータ構造。','example'=>'クラスカル法での閉路判定、グラフの連結成分数計算、SNSの友人グループ検出などに使われる。','difficulty'=>4,'quiz'=>['question'=>'Union-Findのを経路圧縮（Path Compression）を適用した時間計算量はどれか？','explanation'=>'経路圧縮とランク付きUnionを組み合わせるとFind/Union操作の償却計算量がほぼO(1)（正確にはO(α(n))、αはアッカーマン逆関数）になる。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'ほぼO(1)（アッカーマン逆関数α(n)）','is_correct'=>true],['body'=>'O(log n)','is_correct'=>false],['body'=>'O(n log n)','is_correct'=>false]]]],
            ['name'=>'グラフ（Graph）','definition'=>'頂点（ノード）と辺（エッジ）で構成されるデータ構造。有向/無向、重み付き/なし、巡回/非巡回などの種類がある。','example'=>'SNSの友人関係・Webページのリンク構造・地図の道路網などがグラフで表現される。','difficulty'=>2,'quiz'=>['question'=>'有向グラフと無向グラフの違いはどれか？','explanation'=>'有向グラフは辺に方向性がある（A→B はB→Aと異なる）。無向グラフは辺に方向がなく双方向に移動できる。','choices'=>[['body'=>'有向グラフは重みを持てない','is_correct'=>false],['body'=>'有向グラフは辺に方向があり、無向グラフは双方向移動が可能','is_correct'=>true],['body'=>'無向グラフはDFSに使えない','is_correct'=>false],['body'=>'両者に違いはない','is_correct'=>false]]]],
            ['name'=>'隣接行列 vs 隣接リスト','definition'=>'グラフの表現方法。隣接行列はV×V配列で辺の有無を管理（O(V²)空間）。隣接リストは各頂点の隣接頂点リスト（O(V+E)空間）。','example'=>'密なグラフには隣接行列、疎なグラフには隣接リストが適切。Webのリンクグラフは頂点数に比べ辺が少ない疎グラフ。','difficulty'=>3,'quiz'=>['question'=>'疎なグラフに適したグラフ表現はどれか？','explanation'=>'疎なグラフ（辺が少ない）では隣接リストがO(V+E)空間で効率的。隣接行列はO(V²)で辺が少なくても大量メモリを使う。','choices'=>[['body'=>'隣接行列','is_correct'=>false],['body'=>'隣接リスト','is_correct'=>true],['body'=>'両者は同等','is_correct'=>false],['body'=>'ハッシュテーブル','is_correct'=>false]]]],
            ['name'=>'フィボナッチ数列','definition'=>'前の2項の和が次の項になる数列（0,1,1,2,3,5,8,13,21...）。再帰・メモ化・DP・行列累乗など様々なアルゴリズムの学習素材。','example'=>'fib(n)を純粋再帰で実装するとO(2^n)だが、DPやメモ化を使えばO(n)に削減できる。','difficulty'=>1,'quiz'=>['question'=>'フィボナッチ数列をメモ化せずに再帰で実装した場合の時間計算量はどれか？','explanation'=>'メモ化なしの再帰はfib(n-1)とfib(n-2)が重複計算され、呼び出し数が指数関数的に増えてO(2^n)になる。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'O(2^n)','is_correct'=>true],['body'=>'O(n²)','is_correct'=>false],['body'=>'O(n log n)','is_correct'=>false]]]],
            ['name'=>'素数判定','definition'=>'与えられた整数が素数かどうかを判定するアルゴリズム。√nまでの試し割りでO(√n)で判定できる。大きな数にはミラー-ラビン法。','example'=>'97が素数かどうか確認するには、√97≒9.8以下の2,3,5,7で割り切れないかを確認するだけでよい。','difficulty'=>2,'quiz'=>['question'=>'n以下の全素数列挙の効率的な方法はどれか？','explanation'=>'個別の√n判定より、エラトステネスの篩がO(n log log n)で一括列挙できるため効率的。','choices'=>[['body'=>'各数について√n試し割りを繰り返す','is_correct'=>false],['body'=>'エラトステネスの篩で一括列挙する','is_correct'=>true],['body'=>'全数について割り算を試みる','is_correct'=>false],['body'=>'BFSで探索する','is_correct'=>false]]]],
            ['name'=>'ナップサック問題','definition'=>'重量制限のあるナップサックに価値と重量を持つアイテムを詰める最適化問題。0-1型はDPで解ける。NP完全問題の代表例。','example'=>'重量10以下で価値を最大化する。アイテム（重3価4）（重5価7）→DP表で最適組合せを求める。','difficulty'=>4,'quiz'=>['question'=>'0-1ナップサック問題を解くのに適したアルゴリズムはどれか？','explanation'=>'0-1ナップサック問題は貪欲法では最適解が保証されない。DPのdp[i][w]（i番目のアイテムを考慮したときの重量w以下の最大価値）で解く。','choices'=>[['body'=>'貪欲法','is_correct'=>false],['body'=>'動的計画法（DP）','is_correct'=>true],['body'=>'二分探索','is_correct'=>false],['body'=>'BFS','is_correct'=>false]]]],
            ['name'=>'AVL木','definition'=>'左右の高さ差が最大1になるよう自動的にバランスを取る二分探索木。挿入・削除・検索がすべてO(log n)を保証する。','example'=>'頻繁に挿入・削除が行われる辞書データの管理にAVL木を使うことで、検索を常にO(log n)で行える。','difficulty'=>4,'quiz'=>['question'=>'AVL木が通常の二分探索木より優れている点はどれか？','explanation'=>'通常のBSTは最悪O(n)（偏った木になる場合）になるが、AVL木は高さバランスを保つため常にO(log n)の操作を保証する。','choices'=>[['body'=>'メモリ使用量が少ない','is_correct'=>false],['body'=>'自動バランスで常にO(log n)の操作を保証する','is_correct'=>true],['body'=>'ソートされたデータの格納のみに特化する','is_correct'=>false],['body'=>'文字列専用のデータ構造','is_correct'=>false]]]],
            ['name'=>'トライ木（Trie）','definition'=>'文字列を効率的に格納・検索する木構造。各ノードが1文字を表し、共通プレフィックスを共有する。辞書・オートコンプリートに最適。','example'=>'["apple","app","apply"]をTrieに格納すると共通プレフィックス"app"を共有し、"app"から始まる全単語をO(prefix長)で取得できる。','difficulty'=>4,'quiz'=>['question'=>'トライ木の主な用途はどれか？','explanation'=>'TrieはO(L)（L=文字列長）で挿入・検索でき、共通プレフィックスを共有するため辞書・オートコンプリート・IP最長プレフィックスマッチに使われる。','choices'=>[['body'=>'数値のソート','is_correct'=>false],['body'=>'文字列の効率的な検索・オートコンプリート','is_correct'=>true],['body'=>'グラフの最短経路','is_correct'=>false],['body'=>'行列の計算','is_correct'=>false]]]],
            ['name'=>'空間計算量','definition'=>'アルゴリズムが使用するメモリ量の入力サイズnへの依存性。O(1)は定数メモリ、O(n)は入力に比例したメモリを使う。','example'=>'インプレースソート（ヒープソート）はO(1)追加空間。マージソートは配列コピーにO(n)追加空間が必要。','difficulty'=>3,'quiz'=>['question'=>'インプレースアルゴリズムの空間計算量はどれか？','explanation'=>'インプレースアルゴリズムは入力データを直接書き換えて追加メモリを最小限（O(1)）にするアルゴリズム。ヒープソートが代表例。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'O(1)','is_correct'=>true],['body'=>'O(n²)','is_correct'=>false],['body'=>'O(log n)','is_correct'=>false]]]],
            ['name'=>'NP問題','definition'=>'解の検証が多項式時間で可能な問題クラス。NP完全問題は最も難しいNP問題で、多項式時間アルゴリズムは現在未発見（P≠NP予想）。','example'=>'巡回セールスマン問題・ナップサック問題・充足可能性問題(SAT)がNP完全問題の代表例。','difficulty'=>5,'quiz'=>['question'=>'NP完全問題の特徴として正しいものはどれか？','explanation'=>'NP完全問題は与えられた解の正しさを多項式時間で検証できるが、効率的な解法（多項式時間アルゴリズム）がまだ見つかっていない問題群。','choices'=>[['body'=>'解が存在しない問題','is_correct'=>false],['body'=>'解の検証は多項式時間でできるが効率的な解法が未発見','is_correct'=>true],['body'=>'O(n log n)で解ける問題','is_correct'=>false],['body'=>'再帰でしか解けない問題','is_correct'=>false]]]],
            ['name'=>'ビット演算','definition'=>'整数の2進数表現でビット単位のAND・OR・XOR・NOT・シフト演算を行う。高速な集合演算・フラグ管理・暗号化に使われる。','example'=>'権限フラグをビットで管理：READ=001, WRITE=010, EXEC=100。ユーザー権限 = READ|WRITE = 011（3）。','difficulty'=>3,'quiz'=>['question'=>'0b1010 & 0b1100 の結果はどれか？（ANDビット演算）','explanation'=>'AND演算は両方が1のビットのみ1になる。1010 AND 1100 = 1000 = 8（十進数）。','choices'=>[['body'=>'0b1110（14）','is_correct'=>false],['body'=>'0b1000（8）','is_correct'=>true],['body'=>'0b0110（6）','is_correct'=>false],['body'=>'0b1010（10）','is_correct'=>false]]]],
            ['name'=>'プリム法','definition'=>'始点から出発し常に到達済み頂点から最小コストの辺を貪欲に追加して最小全域木を求めるアルゴリズム。密なグラフに適する。','example'=>'6ノードのネットワークで、始点AからA-B(2)→A-C(3)→B-D(1)...と最小コスト辺を順次追加してMSTを構築する。','difficulty'=>4,'quiz'=>['question'=>'プリム法とクラスカル法の違いとして正しいものはどれか？','explanation'=>'プリム法は到達済み集合から最小辺を追加する頂点ベース。クラスカル法は全辺をソートして閉路を避けながら追加する辺ベースのアルゴリズム。','choices'=>[['body'=>'プリム法は辺ソートを使い、クラスカル法は頂点から拡張する','is_correct'=>false],['body'=>'プリム法は頂点から拡張、クラスカル法は辺ソートベース','is_correct'=>true],['body'=>'両者はまったく同じアルゴリズム','is_correct'=>false],['body'=>'プリム法はDFSベース','is_correct'=>false]]]],
            ['name'=>'乱択アルゴリズム','definition'=>'アルゴリズムの実行中に乱数を利用して判断するアルゴリズム。ランダムクイックソートや素数判定のミラー-ラビン法が代表例。','example'=>'ランダムピボット選択のクイックソートは最悪ケースO(n²)になる確率が極めて低く、期待O(n log n)を保証する。','difficulty'=>4,'quiz'=>['question'=>'乱択アルゴリズムを使う主な目的はどれか？','explanation'=>'乱択により最悪ケースを確率的に避けたり、決定的アルゴリズムより単純に実装できる場合がある。期待値で性能を保証する。','choices'=>[['body'=>'常に正確な最適解を保証する','is_correct'=>false],['body'=>'最悪ケースを確率的に避け期待値での性能を保証する','is_correct'=>true],['body'=>'メモリ使用量を削減する','is_correct'=>false],['body'=>'並列処理を実現する','is_correct'=>false]]]],
        ]];
    }

    private function cloudTerms(): array
    {
        return ['cloud' => [
            ['name'=>'IaaS（Infrastructure as a Service）','definition'=>'仮想マシン・ストレージ・ネットワークなどのインフラをクラウドが提供するサービス形態。OSより上の管理はユーザーが行う。','example'=>'AWS EC2でLinux VMを起動し、OSとミドルウェアのセットアップ・セキュリティパッチ適用はユーザーが行う。','difficulty'=>2,'quiz'=>['question'=>'IaaSでユーザーが管理する範囲はどれか？','explanation'=>'IaaSはハードウェア・仮想化・ネットワークはクラウドが管理し、OS・ミドルウェア・アプリケーションはユーザーが管理する。','choices'=>[['body'=>'ハードウェアまで全て管理する','is_correct'=>false],['body'=>'OSより上（OS・ミドルウェア・アプリ）を管理する','is_correct'=>true],['body'=>'アプリケーションのみ管理する','is_correct'=>false],['body'=>'何も管理しない','is_correct'=>false]]]],
            ['name'=>'Docker','definition'=>'アプリとその依存関係をコンテナイメージとしてパッケージ化し、どこでも同じ環境で実行できるコンテナ化プラットフォーム。','example'=>'Dockerfileでアプリの環境を定義し、docker buildでイメージ作成、docker runで任意の環境で同一に起動できる。','difficulty'=>2,'quiz'=>['question'=>'DockerがVMと異なる主な点はどれか？','explanation'=>'Dockerコンテナはホストカーネルを共有しゲストOSが不要なためVMより起動が速く軽量。ただしOS種類の分離はVMより弱い。','choices'=>[['body'=>'Dockerはハードウェアを仮想化する','is_correct'=>false],['body'=>'コンテナはホストOSカーネルを共有しゲストOS不要で軽量','is_correct'=>true],['body'=>'DockerはWindowsのみで動作する','is_correct'=>false],['body'=>'コンテナはVMより強い隔離を提供する','is_correct'=>false]]]],
            ['name'=>'コンテナ','definition'=>'アプリとその依存ライブラリをOSと分離してパッケージ化した実行単位。軽量・ポータブルで環境差異を吸収できる。','example'=>'開発環境・CI環境・本番環境で同一のDockerコンテナを動かすことで「自分の環境では動く」問題を解消する。','difficulty'=>2,'quiz'=>['question'=>'コンテナの主なメリットはどれか？','explanation'=>'コンテナは依存関係をアプリと一緒にパッケージ化するため環境差異がなく、どこでも同じ動作を保証できる（ポータビリティ）。','choices'=>[['body'=>'ハードウェアに直接アクセスできる','is_correct'=>false],['body'=>'環境差異を吸収してどこでも同一の動作を保証する','is_correct'=>true],['body'=>'VPNを不要にする','is_correct'=>false],['body'=>'データベースを自動スケールする','is_correct'=>false]]]],
            ['name'=>'コンテナレジストリ（Docker Hub等）','definition'=>'コンテナイメージを保存・配布するリポジトリサービス。Docker Hub（公開）・ECR（AWS）・GCR（GCP）などがある。','example'=>'docker push myapp:1.0 でECRにイメージを保存し、本番サーバーがdocker pull でイメージを取得してデプロイする。','difficulty'=>2,'quiz'=>['question'=>'コンテナレジストリの役割はどれか？','explanation'=>'コンテナレジストリはDocker Imageを保存・バージョン管理・配布するサービス。CI/CDパイプラインでビルドしてレジストリにpushし、デプロイ時にpullして使う。','choices'=>[['body'=>'コンテナの実行環境を提供する','is_correct'=>false],['body'=>'コンテナイメージを保存・バージョン管理・配布する','is_correct'=>true],['body'=>'コンテナのネットワークを管理する','is_correct'=>false],['body'=>'Kubernetesのクラスター管理','is_correct'=>false]]]],
            ['name'=>'Helm（Kubernetesパッケージマネージャー）','definition'=>'Kubernetesアプリのデプロイをチャート（テンプレート集）で管理するパッケージマネージャー。複雑なK8sリソースを一括管理できる。','example'=>'helm install my-nginx bitnami/nginx でNginxのDeployment・Service・ConfigMapを一括デプロイする。','difficulty'=>4,'quiz'=>['question'=>'HelmのChart（チャート）とは何か？','explanation'=>'Chartは関連するKubernetesリソース（Deployment・Service・ConfigMapなど）の定義をまとめたテンプレートパッケージ。パラメータを変えて再利用できる。','choices'=>[['body'=>'コンテナイメージのビルド設定','is_correct'=>false],['body'=>'Kubernetesリソース定義をまとめたテンプレートパッケージ','is_correct'=>true],['body'=>'Kubernetesのネットワーク設定','is_correct'=>false],['body'=>'監視ダッシュボードの設定','is_correct'=>false]]]],
            ['name'=>'サービスメッシュ','definition'=>'マイクロサービス間の通信をサービス層ではなくインフラ層（サイドカープロキシ）で管理するアーキテクチャ。Istioが代表的。','example'=>'Istioがすべてのサービス通信をサイドカーコンテナ（Envoy）で制御し、相互TLS・サーキットブレーカー・分散トレーシングを透過的に提供する。','difficulty'=>5,'quiz'=>['question'=>'サービスメッシュが解決する主な課題はどれか？','explanation'=>'サービスメッシュはアプリコードを変えずに、サービス間通信の観測・セキュリティ（mTLS）・障害耐性（タイムアウト・リトライ）をインフラ層で実現する。','choices'=>[['body'=>'データベースのスケーリング','is_correct'=>false],['body'=>'アプリコード変更なしにサービス間通信の観測・セキュリティ・障害耐性を実現','is_correct'=>true],['body'=>'コンテナイメージのビルド高速化','is_correct'=>false],['body'=>'静的ファイルのCDN配信','is_correct'=>false]]]],
            ['name'=>'オブジェクトストレージ','definition'=>'データをオブジェクト（ファイル＋メタデータ＋ID）として格納する分散ストレージ。AWS S3が代表で、無制限スケール・高耐久性・HTTPアクセスが特徴。','example'=>'ユーザーがアップロードした画像をS3バケットに保存し、CloudFront経由で配信する構成が定番。','difficulty'=>2,'quiz'=>['question'=>'オブジェクトストレージがファイルシステムと異なる点はどれか？','explanation'=>'オブジェクトストレージはデータをキー（ID）とメタデータと共にフラットに格納する。階層型ディレクトリ構造を持たず、HTTPSでアクセスする。','choices'=>[['body'=>'階層的ディレクトリ構造を持つ','is_correct'=>false],['body'=>'データをフラットなキー・メタデータ・本体のセットで格納しHTTPSでアクセスする','is_correct'=>true],['body'=>'データベースの代替として使う','is_correct'=>false],['body'=>'CPUキャッシュの管理に使う','is_correct'=>false]]]],
            ['name'=>'AWS Lambda','definition'=>'コードをアップロードするだけで実行環境を管理なしに関数単位で実行できるAWSのFaaSサービス。実行時間単位の課金。','example'=>'S3に画像がアップロードされるとLambdaが自動トリガーされサムネイル生成処理を実行し結果を別バケットに保存する。','difficulty'=>3,'quiz'=>['question'=>'AWS Lambdaの課金モデルはどれか？','explanation'=>'Lambdaは実行回数×実行時間（100msごと）×メモリ量で課金される。サーバーが起動していない時間は課金されない。','choices'=>[['body'=>'月額固定料金','is_correct'=>false],['body'=>'実行回数と実行時間（100ms単位）で課金','is_correct'=>true],['body'=>'ストレージ量で課金','is_correct'=>false],['body'=>'無料（フルマネージドのため）','is_correct'=>false]]]],
            ['name'=>'SLO（Service Level Objective）','definition'=>'SLA内で設定するサービスレベルの具体的な目標値。エラーレート・レイテンシ・可用性など指標（SLI）の目標を定義する。','example'=>'「99.9%の可用性・p99レイテンシ200ms以下・エラーレート0.1%以下」をSLOとして定義して運用する。','difficulty'=>3,'quiz'=>['question'=>'SLI・SLO・SLAの関係として正しいものはどれか？','explanation'=>'SLIは実測指標（例:エラーレート）、SLOはその目標値（例:0.1%以下）、SLAはSLO未達時の補償を含む顧客との契約。','choices'=>[['body'=>'SLAは内部目標、SLOは顧客との契約','is_correct'=>false],['body'=>'SLIは指標の測定値、SLOはその目標、SLAは補償含む契約','is_correct'=>true],['body'=>'3つは同じ意味','is_correct'=>false],['body'=>'SLOはAWSのサービス名','is_correct'=>false]]]],
            ['name'=>'RTO / RPO','definition'=>'RTO（Recovery Time Objective）は障害からの目標復旧時間。RPO（Recovery Point Objective）は許容できる最大データ損失時間（バックアップ間隔など）。','example'=>'RTO=1時間・RPO=30分なら、「1時間以内に復旧し、直近30分のデータ損失は許容できる」設計となる。','difficulty'=>3,'quiz'=>['question'=>'RPO（Recovery Point Objective）の説明として正しいものはどれか？','explanation'=>'RPOはデータ損失の許容時間を定義する。RPO=30分なら最大30分前のバックアップから復旧できればよく、30分以内の変更は失ってもよいということ。','choices'=>[['body'=>'システム復旧までの目標時間','is_correct'=>false],['body'=>'許容できる最大データ損失時間（バックアップ間隔の上限）','is_correct'=>true],['body'=>'1日の最大ダウンタイム','is_correct'=>false],['body'=>'SLAの未達ペナルティ計算式','is_correct'=>false]]]],
            ['name'=>'カオスエンジニアリング','definition'=>'本番環境で意図的に障害を注入し、システムの耐障害性を事前に検証するエンジニアリング手法。Netflix発祥のChaos Monkeyが有名。','example'=>'Chaos Monkeyがランダムにサーバーを停止させ、システムが自動復旧できるかどうかを本番環境で継続的に検証する。','difficulty'=>4,'quiz'=>['question'=>'カオスエンジニアリングの目的はどれか？','explanation'=>'カオスエンジニアリングは「本番で起きる障害」を意図的に再現し、未知の弱点を発見してシステムの回復力を本番で継続的に検証する。','choices'=>[['body'=>'コストを最小化する','is_correct'=>false],['body'=>'意図的に障害を注入し未知の脆弱性と耐障害性を検証する','is_correct'=>true],['body'=>'開発速度を向上させる','is_correct'=>false],['body'=>'本番障害の原因を調査する','is_correct'=>false]]]],
            ['name'=>'フィーチャーフラグ（Feature Flag）','definition'=>'コードを変更せずに機能のON/OFFをフラグで切り替える手法。カナリアリリース・A/Bテスト・緊急時のロールバックに活用する。','example'=>'新決済フローをフィーチャーフラグで10%のユーザーにのみ公開し、問題なければ段階的に100%に拡大する。','difficulty'=>3,'quiz'=>['question'=>'フィーチャーフラグの主なメリットはどれか？','explanation'=>'フィーチャーフラグによりコードのデプロイと機能の公開を切り離せる。緊急時はデプロイなしに機能をOFFにできる。','choices'=>[['body'=>'テストが不要になる','is_correct'=>false],['body'=>'コードデプロイなしに機能のON/OFFを制御できる','is_correct'=>true],['body'=>'DBのマイグレーションを自動化する','is_correct'=>false],['body'=>'コンテナのビルドを高速化する','is_correct'=>false]]]],
            ['name'=>'DevSecOps','definition'=>'DevOpsのCI/CDパイプラインにセキュリティ（Sec）を組み込む文化・手法。「シフトレフト」で開発の早期段階からセキュリティを確保する。','example'=>'CI/CDパイプラインにSAST（静的解析）・依存関係の脆弱性スキャン・コンテナイメージスキャンを自動化して組み込む。','difficulty'=>3,'quiz'=>['question'=>'DevSecOpsの「シフトレフト」が意味することはどれか？','explanation'=>'シフトレフトは開発ライフサイクルの「右」（本番・リリース後）ではなく「左」（設計・開発・テスト段階）でセキュリティを対処することを意味する。','choices'=>[['body'=>'インフラをコードで管理すること','is_correct'=>false],['body'=>'開発の早期段階からセキュリティを組み込むこと','is_correct'=>true],['body'=>'セキュリティチームを左側のオフィスに移動すること','is_correct'=>false],['body'=>'本番後にセキュリティテストを行うこと','is_correct'=>false]]]],
            ['name'=>'AWS S3（Simple Storage Service）','definition'=>'AWSが提供する耐久性99.999999999%（イレブンナイン）のオブジェクトストレージ。静的Webサイト・バックアップ・データレイクに広く使われる。','example'=>'Webアプリの画像・動画をS3バケットに保存し、CloudFrontでCDN配信。S3の静的Webサイトホスティングで低コスト公開も可能。','difficulty'=>2,'quiz'=>['question'=>'AWS S3の主な特徴はどれか？','explanation'=>'S3は99.999999999%（イレブンナイン）の耐久性を持つオブジェクトストレージ。ストレージ容量の上限がなく、データをオブジェクトキーで管理する。','choices'=>[['body'=>'高速なSSDデータベース','is_correct'=>false],['body'=>'99.999999999%の耐久性を持つオブジェクトストレージ','is_correct'=>true],['body'=>'仮想マシンのストレージ','is_correct'=>false],['body'=>'インメモリキャッシュ','is_correct'=>false]]]],
            ['name'=>'マルチリージョン','definition'=>'地理的に離れた複数のデータセンターリージョンにサービスを展開する構成。DR（災害復旧）・レイテンシ低減・規制対応が目的。','example'=>'メインリージョン（東京）で障害が発生しても、バックアップリージョン（大阪）に自動フェイルオーバーする構成を組む。','difficulty'=>3,'quiz'=>['question'=>'マルチリージョン構成の主な目的はどれか？','explanation'=>'リージョン全体が利用不能になる大規模障害や自然災害に備え、別リージョンでサービスを継続できる高可用性・DR構成が主な目的。','choices'=>[['body'=>'コストを削減する','is_correct'=>false],['body'=>'リージョン障害に備えた高可用性・DR対策','is_correct'=>true],['body'=>'デプロイを高速化する','is_correct'=>false],['body'=>'セキュリティを向上させる','is_correct'=>false]]]],
            ['name'=>'APM（Application Performance Monitoring）','definition'=>'アプリケーションのパフォーマンスをリアルタイムに監視・分析するツール。NewRelic・Datadog・Dynatraceが代表的。','example'=>'DatadogのAPMでAPIのp95レイテンシが急上昇したことを検知し、特定のDBクエリがボトルネックであることを特定する。','difficulty'=>3,'quiz'=>['question'=>'APMが提供する主な機能はどれか？','explanation'=>'APMはトランザクション追跡・レイテンシ計測・エラー率監視・リソース使用状況可視化などアプリの性能全般をリアルタイムに把握できる。','choices'=>[['body'=>'ソースコードの静的解析','is_correct'=>false],['body'=>'アプリのレイテンシ・エラー率・リソース使用をリアルタイム監視','is_correct'=>true],['body'=>'データベースのバックアップ','is_correct'=>false],['body'=>'コンテナのビルド自動化','is_correct'=>false]]]],
            ['name'=>'FinOps','definition'=>'クラウドコストの最適化・可視化・管理を行う実践手法。開発・財務・ビジネス部門が協力してクラウド支出を管理する文化。','example'=>'FinOpsダッシュボードでサービス別・チーム別のAWSコストを可視化し、未使用リソースを特定して月額コストを30%削減する。','difficulty'=>3,'quiz'=>['question'=>'FinOpsの主な目的はどれか？','explanation'=>'FinOpsはクラウド費用を可視化・分析・最適化し、技術投資のビジネス価値を最大化しながらコスト効率を向上させる実践。','choices'=>[['body'=>'クラウドインフラのセキュリティ強化','is_correct'=>false],['body'=>'クラウドコストの可視化・最適化・管理','is_correct'=>true],['body'=>'CI/CDパイプラインの構築','is_correct'=>false],['body'=>'コンテナオーケストレーション','is_correct'=>false]]]],
            ['name'=>'ロールバック（クラウド）','definition'=>'デプロイした新バージョンで問題が発生した際に、前のバージョンに戻す操作。CI/CDパイプラインで自動化されることが多い。','example'=>'本番デプロイ後にエラー率が急上昇し、Kubernetesのkubectl rollout undoで5分で前バージョンに自動ロールバックした。','difficulty'=>2,'quiz'=>['question'=>'ロールバックを素早く行うために重要なことはどれか？','explanation'=>'以前のバージョンのアーティファクト（コンテナイメージ・デプロイパッケージ）を保持しておくことで、問題発生時に素早く前バージョンに戻せる。','choices'=>[['body'=>'全テストをスキップする','is_correct'=>false],['body'=>'以前のバージョンのアーティファクトを保持しておく','is_correct'=>true],['body'=>'本番DBを削除する','is_correct'=>false],['body'=>'コードを直接本番編集する','is_correct'=>false]]]],
            ['name'=>'クラウドネイティブ','definition'=>'クラウドの特性（スケーラビリティ・弾力性・マネージドサービス）を最大限活用するアーキテクチャ・開発手法の考え方。','example'=>'マイクロサービス・コンテナ・Kubernetes・CI/CD・宣言的APIを組み合わせたシステムがクラウドネイティブの典型例。','difficulty'=>3,'quiz'=>['question'=>'クラウドネイティブアーキテクチャの特徴として正しいものはどれか？','explanation'=>'クラウドネイティブはコンテナ・マイクロサービス・CI/CD・宣言的APIを柱とし、クラウドの弾力性・スケーラビリティを最大活用するアーキテクチャ。','choices'=>[['body'=>'モノリシックアプリをクラウドに移行するだけ','is_correct'=>false],['body'=>'コンテナ・マイクロサービス・CI/CDでクラウドの弾力性を最大活用する','is_correct'=>true],['body'=>'オンプレミスと同一の設計を使う','is_correct'=>false],['body'=>'サーバーを使わない','is_correct'=>false]]]],
            ['name'=>'Docker Compose','definition'=>'複数のDockerコンテナを定義・実行するためのツール。docker-compose.ymlでサービス・ネットワーク・ボリュームを一括管理できる。','example'=>'docker-compose.ymlにWebアプリ・MySQL・Redisを定義し、docker-compose upで3コンテナを同時に起動する。','difficulty'=>2,'quiz'=>['question'=>'Docker Composeの主な用途はどれか？','explanation'=>'Docker Composeは複数コンテナで構成されるアプリ（Webサーバー・DBなど）を1ファイルで定義して一括起動・停止できる開発ツール。','choices'=>[['body'=>'コンテナイメージをビルドする','is_correct'=>false],['body'=>'複数コンテナを一括定義・起動・管理する','is_correct'=>true],['body'=>'Kubernetesクラスターを管理する','is_correct'=>false],['body'=>'コンテナをレジストリにpushする','is_correct'=>false]]]],
            ['name'=>'AWS EC2（Elastic Compute Cloud）','definition'=>'AWSが提供する仮想サーバー（VM）サービス。インスタンスタイプ・OS・スペックを選んで数分で起動できる。IaaSの代表。','example'=>'t3.medium EC2インスタンスでLaravel APIサーバーを動かし、Auto ScalingでCPU使用率に応じてインスタンス数を自動調整する。','difficulty'=>2,'quiz'=>['question'=>'EC2のオンデマンドインスタンスとリザーブドインスタンスの違いはどれか？','explanation'=>'オンデマンドは必要な時だけ起動して使った分だけ課金。リザーブドインスタンスは1〜3年契約で最大72%割引になるが前払いが必要。','choices'=>[['body'=>'オンデマンドの方が常に安い','is_correct'=>false],['body'=>'リザーブドは1〜3年契約で大幅割引、オンデマンドは都度課金','is_correct'=>true],['body'=>'両者の性能は異なる','is_correct'=>false],['body'=>'リザーブドは常時起動し続ける必要がある','is_correct'=>false]]]],
            ['name'=>'クラウドセキュリティ','definition'=>'クラウド環境特有のセキュリティ課題（IAM誤設定・パブリックバケット公開・クレデンシャル漏洩など）に対応するセキュリティ対策。','example'=>'S3バケットのパブリックアクセスをブロック・IAMの過剰権限を修正・Secrets ManagerでAPI鍵を安全管理するなど。','difficulty'=>3,'quiz'=>['question'=>'クラウドセキュリティの最もよくある設定ミスはどれか？','explanation'=>'IAMポリシーの過剰権限（例:全サービスへのAdmin権限付与）やS3バケットの意図しないパブリック公開がクラウドセキュリティ事故の主な原因。','choices'=>[['body'=>'コンテナイメージが大きすぎる','is_correct'=>false],['body'=>'IAMポリシーの過剰権限やS3バケットの意図しない公開','is_correct'=>true],['body'=>'リージョンを1つしか使わない','is_correct'=>false],['body'=>'Auto Scalingを設定しない','is_correct'=>false]]]],
        ]];
    }

    private function webTerms(): array
    {
        return ['web' => [
            ['name'=>'Vue.js','definition'=>'HTMLテンプレート・リアクティブデータバインディング・コンポーネントシステムを持つプログレッシブJavaScriptフレームワーク。','example'=>'<template>でUI定義、<script setup>でロジック、<style>でCSS。SPAからサーバーサイドレンダリングまで対応する。','difficulty'=>2,'quiz'=>['question'=>'Vue.jsの主な特徴はどれか？','explanation'=>'Vue.jsはHTMLテンプレートベースのリアクティブシステムと単一ファイルコンポーネント（.vue）が特徴。プログレッシブに採用できる設計が特徴。','choices'=>[['body'=>'Node.jsのサーバーサイドフレームワーク','is_correct'=>false],['body'=>'リアクティブデータバインディングとコンポーネントを持つUIフレームワーク','is_correct'=>true],['body'=>'CSSフレームワーク','is_correct'=>false],['body'=>'TypeScript専用フレームワーク','is_correct'=>false]]]],
            ['name'=>'React','definition'=>'Facebookが開発したUIコンポーネントライブラリ。仮想DOMと関数コンポーネント・Hooksによる状態管理が特徴。','example'=>'useState・useEffect Hookを使い、APIからデータを取得してコンポーネントのstateに保持し自動再レンダリングする。','difficulty'=>2,'quiz'=>['question'=>'ReactのHookの説明として正しいものはどれか？','explanation'=>'Hooksは関数コンポーネントでstate・ライフサイクル・副作用などを扱うためのAPI。useStateで状態管理、useEffectで副作用処理を行う。','choices'=>[['body'=>'クラスコンポーネント専用の機能','is_correct'=>false],['body'=>'関数コンポーネントでstate・副作用などを扱うAPI','is_correct'=>true],['body'=>'CSSアニメーションを制御する機能','is_correct'=>false],['body'=>'サーバーサイドレンダリング専用機能','is_correct'=>false]]]],
            ['name'=>'Next.js','definition'=>'Reactベースのフルスタックフレームワーク。SSR・SSG・CSR・App Routerを選択でき、APIルートも実装できる。Vercelが開発。','example'=>'Next.jsのApp RouterでSSR・SSG・ISRを組み合わせ、ブログはSSG、商品詳細はISR、ユーザーページはCSRで実装する。','difficulty'=>3,'quiz'=>['question'=>'Next.jsがCreate React Appより優れている主な点はどれか？','explanation'=>'Next.jsはSSR・SSG・ISR・APIルートをビルトインで提供するため、SEO対応・初期表示速度向上・BFFを追加設定なしに実現できる。','choices'=>[['body'=>'Vueも使えること','is_correct'=>false],['body'=>'SSR・SSG・APIルートをビルトインで提供しSEO対応が容易','is_correct'=>true],['body'=>'TypeScriptが使えないこと','is_correct'=>false],['body'=>'データベースが内蔵されていること','is_correct'=>false]]]],
            ['name'=>'Nuxt.js','definition'=>'Vue.jsベースのフルスタックフレームワーク。Vue向けのSSR・SSG・ファイルベースルーティング・自動インポートを提供する。','example'=>'Nuxt 3でpages/index.vueを作成するだけでルーティングが自動設定される。useFetch()でAPIデータをSSRで取得できる。','difficulty'=>3,'quiz'=>['question'=>'Nuxt.jsがVue.jsを素のまま使う場合と比べた主なメリットはどれか？','explanation'=>'NuxtはファイルベースルーティングでVue Routerを手動設定不要にし、SSR・SSGとコンポーネント/APIの自動インポートも提供する。','choices'=>[['body'=>'VueコンポーネントをJSXで書けること','is_correct'=>false],['body'=>'SSR・ファイルベースルーティング・自動インポートなどをビルトイン提供','is_correct'=>true],['body'=>'ReactとVueを同時に使えること','is_correct'=>false],['body'=>'データベース接続機能を内蔵すること','is_correct'=>false]]]],
            ['name'=>'Vite（ビルドツール）','definition'=>'ES Modulesを利用した高速な開発サーバーとバンドラー。ColdStartが遅いwebpackの代替として開発され、HMRが非常に高速。','example'=>'Viteは開発時にファイルをバンドルせずES Modulesとして提供するため、大規模アプリでもdev server起動が数秒以内。','difficulty'=>2,'quiz'=>['question'=>'Viteが開発サーバーで高速な理由はどれか？','explanation'=>'ViteはES Modulesをブラウザが直接インポートする形で提供し、ファイルをバンドルしないため起動時間が大幅に削減される。変更時はHMRで変更ファイルだけ更新する。','choices'=>[['body'=>'コードをBabelで高速コンパイルするから','is_correct'=>false],['body'=>'バンドルせずES ModulesをブラウザにそのままHMRで提供するから','is_correct'=>true],['body'=>'Webpackより多くのCPUコアを使うから','is_correct'=>false],['body'=>'TypeScriptをランタイムで処理するから','is_correct'=>false]]]],
            ['name'=>'npm / yarn','definition'=>'Node.jsのパッケージマネージャー。npmはデフォルト付属、yarnはFacebook製の高速版。package.jsonで依存を管理しnode_modulesに格納。','example'=>'npm install axios で依存追加、npm run dev でdevスクリプト実行。package.jsonのscriptsでプロジェクト固有コマンドを定義する。','difficulty'=>1,'quiz'=>['question'=>'package.jsonのdependenciesとdevDependenciesの違いはどれか？','explanation'=>'dependenciesは本番環境で必要なライブラリ（Express, Reactなど）、devDependenciesは開発時のみ必要なもの（ESLint, TypeScriptなど）。','choices'=>[['body'=>'devDependenciesの方が本番に含まれる','is_correct'=>false],['body'=>'dependenciesは本番用、devDependenciesは開発時のみ必要','is_correct'=>true],['body'=>'両者は全く同じ意味','is_correct'=>false],['body'=>'devDependenciesはインストールされない','is_correct'=>false]]]],
            ['name'=>'Cookie','definition'=>'Webサーバーがブラウザに保存させる小さなデータ。セッション管理・ユーザー設定・トラッキングに使われる。HttpOnly・Secureフラグが重要。','example'=>'ログイン後にSet-Cookie: session_id=xxx; HttpOnly; Secure; SameSite=Strict でセッションCookieを安全に保存する。','difficulty'=>2,'quiz'=>['question'=>'CookieのHttpOnlyフラグの効果はどれか？','explanation'=>'HttpOnly フラグが設定されたCookieはJavaScriptのdocument.cookieから読めなくなるため、XSSでのセッション盗取を防げる。','choices'=>[['body'=>'HTTPS通信のみCookieを送信する','is_correct'=>false],['body'=>'JavaScriptからCookieへのアクセスを禁止しXSS盗取を防ぐ','is_correct'=>true],['body'=>'Cookieの有効期限を設定する','is_correct'=>false],['body'=>'Cookieをサードパーティサイトへのリクエストにもつけてよいかのフラグ','is_correct'=>false]]]],
            ['name'=>'DOM（Document Object Model）','definition'=>'HTMLドキュメントをツリー構造のオブジェクトとして表現するAPIインターフェース。JavaScriptからHTMLを操作するための基盤。','example'=>'document.getElementById("btn")でDOM要素を取得し、.textContent = "送信中..."でテキストを動的に変更する。','difficulty'=>2,'quiz'=>['question'=>'DOMを多用した直接操作がパフォーマンスに影響する理由はどれか？','explanation'=>'DOM変更はブラウザのレイアウト計算・ペイントを引き起こす（リフロー・リペイント）ため頻繁なDOM操作は重い。Virtual DOMはこれを最小化する。','choices'=>[['body'=>'DOM操作にはサーバー通信が必要だから','is_correct'=>false],['body'=>'DOM変更ごとにブラウザのリフロー・リペイントが発生するから','is_correct'=>true],['body'=>'DOMはJavaScriptで読み取り専用だから','is_correct'=>false],['body'=>'DOMはHTTPSでのみアクセスできるから','is_correct'=>false]]]],
            ['name'=>'AJAX（Asynchronous JavaScript And XML）','definition'=>'ページ全体をリロードせずにサーバーと非同期通信してページを部分更新する技術。現在はXMLでなくJSONが主流。','example'=>'フォーム送信ボタンをクリックするとAJAXでAPIを呼び、結果をページの一部分だけ更新する（従来はページ全体リロード）。','difficulty'=>2,'quiz'=>['question'=>'AJAXの主な特徴はどれか？','explanation'=>'AJAXはページ全体を再読み込みせずにサーバーと非同期通信してページの一部を動的に更新できる技術。UXを大幅に向上させる。','choices'=>[['body'=>'ページ全体を毎回再読み込みする','is_correct'=>false],['body'=>'ページリロードなしにサーバーと非同期通信してページを部分更新する','is_correct'=>true],['body'=>'XMLデータのみ扱える','is_correct'=>false],['body'=>'Javaで実装された技術','is_correct'=>false]]]],
            ['name'=>'Fetch API','definition'=>'ブラウザ標準のHTTPリクエスト非同期APIでPromiseを返す。XMLHttpRequestの後継でより簡潔に非同期HTTP通信を記述できる。','example'=>'const res = await fetch(\'/api/users\'); const data = await res.json(); で非同期にAPIデータを取得する。','difficulty'=>2,'quiz'=>['question'=>'Fetch APIとXMLHttpRequestの違いはどれか？','explanation'=>'Fetch APIはPromiseベースでasync/awaitと組み合わせやすく、コードが簡潔。XHRはコールバックベースで使いにくい。FetchはサービスワーカーなどモダンなWebAPIとの統合も優れる。','choices'=>[['body'=>'FetchはGETリクエストしかできない','is_correct'=>false],['body'=>'FetchはPromiseベースでasync/awaitと組み合わせやすい','is_correct'=>true],['body'=>'FetchはNode.jsのみで動作する','is_correct'=>false],['body'=>'FetchはXHRより低速','is_correct'=>false]]]],
            ['name'=>'CSSアニメーション','definition'=>'@keyframesとanimationプロパティを使いCSSだけでアニメーションを実装する機能。JavaScriptなしに滑らかな動きを実現できる。','example'=>'@keyframes fadeIn { from { opacity: 0 } to { opacity: 1 } } と定義し animation: fadeIn 0.5s ease でフェードイン効果を付ける。','difficulty'=>2,'quiz'=>['question'=>'CSSアニメーションでパフォーマンスを最適化するプロパティはどれか？','explanation'=>'transformとopacityはGPUが処理するコンポジット層での変更のため、リフロー・リペイントなしにアニメーションでき最もパフォーマンスが良い。','choices'=>[['body'=>'widthとheight','is_correct'=>false],['body'=>'transformとopacity','is_correct'=>true],['body'=>'marginとpadding','is_correct'=>false],['body'=>'font-sizeとcolor','is_correct'=>false]]]],
            ['name'=>'CSS変数（カスタムプロパティ）','definition'=>'--変数名で定義してvar()で参照できるCSS変数。テーマカラーや共通値を一元管理でき、JavaScriptからも操作できる。','example'=>':root { --color-primary: #0ea5e9; } を定義し .btn { color: var(--color-primary); } で参照する。テーマ切替も容易。','difficulty'=>2,'quiz'=>['question'=>'CSS変数（カスタムプロパティ）のメリットはどれか？','explanation'=>'CSS変数はCSS内で値を再利用でき、:rootで定義することでグローバルなテーマ管理が可能。JavaScriptから動的に変更してダークモードなど実装できる。','choices'=>[['body'=>'CSS変数はSassでのみ使える','is_correct'=>false],['body'=>'値を一元管理でき、JavaScriptから動的に変更してテーマ切替もできる','is_correct'=>true],['body'=>'コンパイルが必要','is_correct'=>false],['body'=>'IE11で完全サポートされている','is_correct'=>false]]]],
            ['name'=>'SEO（Search Engine Optimization）','definition'=>'検索エンジンで上位表示されるようWebサイトを最適化する手法。テクニカルSEO・コンテンツSEO・被リンクが三本柱。','example'=>'適切なメタタグ設定・構造化データ・ページ速度改善・モバイル対応・高品質コンテンツでGoogleの検索順位を上げる。','difficulty'=>2,'quiz'=>['question'=>'SPAがSEO対策で課題になる理由はどれか？','explanation'=>'SPAはJavaScriptでコンテンツをレンダリングするため、JSを実行しないクローラーにはコンテンツが見えない場合がある。SSRやSSGでHTMLを事前生成することで解決する。','choices'=>[['body'=>'SPAはHTTPSを使えないから','is_correct'=>false],['body'=>'JSでレンダリングされるためJSを実行しないクローラーにコンテンツが見えない場合がある','is_correct'=>true],['body'=>'SPAはモバイルで動作しないから','is_correct'=>false],['body'=>'SPAはGoogleに登録できないから','is_correct'=>false]]]],
            ['name'=>'OGP（Open Graph Protocol）','definition'=>'Webページをソーシャルメディアでシェアされたときに表示されるタイトル・説明・画像を指定するメタデータ仕様。Facebookが策定。','example'=>'<meta property="og:title" content="記事タイトル"> などをHTMLのheadに設定し、Twitterカードやリッチプレビューで表示する。','difficulty'=>2,'quiz'=>['question'=>'OGPのog:imageが設定されている場合の効果はどれか？','explanation'=>'og:imageにSNSシェア時のサムネイル画像URLを指定することで、リンクシェア時にカード形式で画像プレビューが表示されクリック率が向上する。','choices'=>[['body'=>'Webサイトのファビコンを設定する','is_correct'=>false],['body'=>'SNSシェア時にリッチプレビューで画像サムネイルを表示する','is_correct'=>true],['body'=>'検索結果に画像を表示する','is_correct'=>false],['body'=>'Webサイトのロゴを設定する','is_correct'=>false]]]],
            ['name'=>'HTTPキャッシュ（Cache-Control）','definition'=>'サーバーがCache-Controlヘッダーで指示するブラウザ・CDNのキャッシュ戦略。max-age・no-cache・no-store・s-maxageなどを指定する。','example'=>'Cache-Control: max-age=3600 で1時間キャッシュ、Cache-Control: no-cache で毎回サーバー確認、静的ファイルはmax-age=31536000 immutable。','difficulty'=>3,'quiz'=>['question'=>'Cache-Control: no-cacheとno-storeの違いはどれか？','explanation'=>'no-cacheはキャッシュするが再利用前にサーバー確認（条件付きリクエスト）が必要。no-storeはキャッシュ自体を禁止する（機密情報に使用）。','choices'=>[['body'=>'no-cacheはキャッシュしない、no-storeは再検証が必要','is_correct'=>false],['body'=>'no-cacheは再利用前にサーバー確認が必要、no-storeはキャッシュを完全禁止','is_correct'=>true],['body'=>'両者は同じ動作','is_correct'=>false],['body'=>'no-storeはCDNのみに適用される','is_correct'=>false]]]],
            ['name'=>'HTMLセマンティクス','definition'=>'意味的に正しいHTML要素を使いコンテンツの構造を機械可読にする手法。header・nav・main・article・sectionなどが意味のある要素。','example'=>'divだけでなく<nav>でナビゲーション、<main>でメインコンテンツ、<article>で記事を表すとアクセシビリティとSEOが向上する。','difficulty'=>2,'quiz'=>['question'=>'セマンティックHTMLを使うメリットはどれか？','explanation'=>'セマンティックHTMLはスクリーンリーダーがコンテンツ構造を正確に解釈でき（アクセシビリティ向上）、検索エンジンもコンテンツの意味を理解しやすくなる（SEO向上）。','choices'=>[['body'=>'ページの表示速度が向上する','is_correct'=>false],['body'=>'アクセシビリティとSEOが向上する','is_correct'=>true],['body'=>'CSSが不要になる','is_correct'=>false],['body'=>'JavaScriptのコード量が減る','is_correct'=>false]]]],
            ['name'=>'Lighthouse','definition'=>'GoogleのWebアプリ品質監査ツール。パフォーマンス・SEO・アクセシビリティ・ベストプラクティスをスコアリングして改善点を提示する。','example'=>'Chrome DevToolsのLighthouseでサイトを計測し、LCP・TTI・Cumulative Layout Shiftのスコアを確認して最適化する。','difficulty'=>2,'quiz'=>['question'=>'Lighthouseが計測する主なカテゴリはどれか？','explanation'=>'Lighthouseはパフォーマンス・アクセシビリティ・ベストプラクティス・SEO・PWAの5カテゴリを100点満点で採点する。','choices'=>[['body'=>'セキュリティ・価格・ユーザー数','is_correct'=>false],['body'=>'パフォーマンス・アクセシビリティ・SEO・PWA等','is_correct'=>true],['body'=>'JavaScriptエラー数のみ','is_correct'=>false],['body'=>'サーバーの応答時間のみ','is_correct'=>false]]]],
            ['name'=>'URLとURI','definition'=>'URI（Uniform Resource Identifier）はリソースを識別する文字列の総称。URL（Locator）はURIのサブセットでリソースの場所も示す。','example'=>'https://example.com/users?page=1#section はURL。スキーム・ドメイン・パス・クエリ・フラグメントで構成される。','difficulty'=>2,'quiz'=>['question'=>'URLのクエリパラメーター（?key=value）の役割はどれか？','explanation'=>'クエリパラメーターはURLでサーバーに追加情報を渡す仕組み。検索キーワード・ページ番号・フィルター条件の渡し方として広く使われる。','choices'=>[['body'=>'HTMLの特定要素にスクロールする','is_correct'=>false],['body'=>'サーバーに追加情報（フィルター・ページ番号等）を渡す','is_correct'=>true],['body'=>'URLの見た目を変える','is_correct'=>false],['body'=>'ユーザー認証情報を送る','is_correct'=>false]]]],
            ['name'=>'HTTPステータスコード','definition'=>'HTTPレスポンスでサーバーがリクエストの結果を示す3桁コード。2xx=成功、3xx=リダイレクト、4xx=クライアントエラー、5xx=サーバーエラー。','example'=>'200=OK、201=Created、301=Moved Permanently、400=Bad Request、401=Unauthorized、404=Not Found、500=Internal Server Error。','difficulty'=>1,'quiz'=>['question'=>'HTTPステータスコード401と403の違いはどれか？','explanation'=>'401 Unauthorizedは認証が必要なのに認証されていない状態。403 Forbiddenは認証済みだがリソースへのアクセス権限がない状態。','choices'=>[['body'=>'401はページが見つからない、403はサーバーエラー','is_correct'=>false],['body'=>'401は未認証、403は認証済みだが権限なし','is_correct'=>true],['body'=>'両者は同じ意味','is_correct'=>false],['body'=>'401はリダイレクト、403はキャッシュ','is_correct'=>false]]]],
            ['name'=>'Web Components','definition'=>'カスタムHTML要素を作成するためのWebプラットフォーム標準技術。Custom Elements・Shadow DOM・HTML Templatesの3技術で構成される。','example'=>'<my-button>タグをCustom Elementsで定義するとフレームワーク非依存のUIコンポーネントとして任意のWebアプリで使える。','difficulty'=>4,'quiz'=>['question'=>'Web ComponentsのShadow DOMの主な役割はどれか？','explanation'=>'Shadow DOMはコンポーネント内部のDOMとCSSをホストドキュメントから隔離（カプセル化）する。外のCSSが内部に影響を与えない。','choices'=>[['body'=>'コンポーネントのHTMLテンプレートを定義する','is_correct'=>false],['body'=>'コンポーネントのDOMとCSSを外部から隔離しカプセル化する','is_correct'=>true],['body'=>'カスタムHTMLタグ名を登録する','is_correct'=>false],['body'=>'データバインディングを実現する','is_correct'=>false]]]],
        ]];
    }

    private function programmingTerms(): array
    {
        return ['programming' => [
            ['name'=>'ジェネリクス（Generics）','definition'=>'型をパラメーター化して様々な型で再利用できる汎用のコード（関数・クラス・インターフェース）を記述する機能。型安全を保ちながら汎用化できる。','example'=>'function identity<T>(arg: T): T { return arg; } でstring・number・任意型で型安全に使える汎用関数を定義する。','difficulty'=>3,'quiz'=>['question'=>'ジェネリクスを使う主な目的はどれか？','explanation'=>'ジェネリクスにより型をパラメーターとして受け取ることで、型安全を維持しながら異なる型で動作する汎用コードを書ける。anyを使うより型チェックが機能する。','choices'=>[['body'=>'コードを高速化する','is_correct'=>false],['body'=>'型安全を維持しながら異なる型で動作する汎用コードを書く','is_correct'=>true],['body'=>'ガベージコレクションを制御する','is_correct'=>false],['body'=>'非同期処理を簡略化する','is_correct'=>false]]]],
            ['name'=>'ラムダ式','definition'=>'名前を持たない無名の関数リテラル。短く書けてコールバックや関数型プログラミングに活用される。多くの言語でサポート。','example'=>'JavaScript: (x, y) => x + y。Python: lambda x, y: x + y。Java: (x, y) -> x + y の構文で表現する。','difficulty'=>2,'quiz'=>['question'=>'ラムダ式の主な用途はどれか？','explanation'=>'ラムダ式はmap・filterなどの高階関数に渡す短い無名関数を簡潔に書くために使われる。','choices'=>[['body'=>'クラスを定義する','is_correct'=>false],['body'=>'高階関数に渡す短い無名関数を簡潔に記述する','is_correct'=>true],['body'=>'例外処理を行う','is_correct'=>false],['body'=>'メモリを手動管理する','is_correct'=>false]]]],
            ['name'=>'モック（Mock）','definition'=>'テストで本物の依存（DB・外部API等）を模倣するオブジェクト。呼び出し検証・戻り値の設定ができ、テストを高速・独立させる。','example'=>'ユーザーサービスのテストでDBアクセスをモックに置き換え、DB不要で「ユーザーが存在しないとき404を返す」ロジックをテストする。','difficulty'=>3,'quiz'=>['question'=>'テストでモックを使う主な理由はどれか？','explanation'=>'モックにより外部依存（DB・APIなど）を本物から切り離し、テストを高速かつ独立して実行でき、特定のシナリオ（エラー等）も簡単に再現できる。','choices'=>[['body'=>'本番コードの速度を向上させる','is_correct'=>false],['body'=>'外部依存を本物から切り離し、テストを高速・独立させる','is_correct'=>true],['body'=>'コードのバグを自動修正する','is_correct'=>false],['body'=>'メモリ使用量を削減する','is_correct'=>false]]]],
            ['name'=>'E2Eテスト（End-to-End Test）','definition'=>'ユーザーの操作を実際のブラウザや環境でシミュレーションするテスト。PlaywrightやCypressが代表的ツール。','example'=>'Playwrightで「ログインページでメール・パスワード入力→ボタンクリック→ダッシュボード表示」を自動化してブラウザでテストする。','difficulty'=>3,'quiz'=>['question'=>'E2Eテストの特徴として正しいものはどれか？','explanation'=>'E2Eテストはユーザーが実際に行う操作フロー全体をブラウザで再現するためリアルな動作確認が可能。ただしユニットテストより実行が遅い。','choices'=>[['body'=>'個々の関数を独立してテストする','is_correct'=>false],['body'=>'ユーザー操作フロー全体をブラウザで自動再現してテストする','is_correct'=>true],['body'=>'DBのCRUD操作をテストする','is_correct'=>false],['body'=>'コードの静的解析を行う','is_correct'=>false]]]],
            ['name'=>'統合テスト（Integration Test）','definition'=>'複数のコンポーネントやモジュールを組み合わせて動作を検証するテスト。ユニットテストと異なり依存関係込みでテストする。','example'=>'Userサービス + Repositoryを組み合わせてDBへの実際のCRUDが正しく動くかを確認する統合テスト。','difficulty'=>2,'quiz'=>['question'=>'統合テストがユニットテストと異なる点はどれか？','explanation'=>'ユニットテストは依存をモックにして単体を孤立テスト。統合テストは実際の依存（DB等）を使い複数コンポーネントの連携をテストする。','choices'=>[['body'=>'統合テストはモックのみを使う','is_correct'=>false],['body'=>'実際の依存を使い複数コンポーネントの連携を検証する','is_correct'=>true],['body'=>'UIのみをテストする','is_correct'=>false],['body'=>'ユニットテストより高速に実行される','is_correct'=>false]]]],
            ['name'=>'コードレビュー','definition'=>'他の開発者がコードを読んで品質・設計・バグ・セキュリティを確認するプロセス。GitHubのPull Request上で行うのが一般的。','example'=>'PRを出すとチームメンバーがコメント・承認・変更要求を行い、CIの通過＋承認を得てからメインブランチにマージする。','difficulty'=>1,'quiz'=>['question'=>'コードレビューの主な目的はどれか？','explanation'=>'コードレビューはバグや設計問題の早期発見・知識共有・コードの一貫性維持・セキュリティ確認が主な目的。','choices'=>[['body'=>'コードを自動的に修正する','is_correct'=>false],['body'=>'バグ・設計問題の早期発見と知識共有','is_correct'=>true],['body'=>'デプロイを自動化する','is_correct'=>false],['body'=>'テストを代替する','is_correct'=>false]]]],
            ['name'=>'Gitブランチ戦略（Git Flow）','definition'=>'main・develop・feature・release・hotfixブランチを使い分けるGitのワークフロー。大規模プロジェクトのリリース管理に適している。','example'=>'feature/login-page ブランチを切り開発→develop マージ→release/1.0 ブランチでQA→main マージ・タグ付けでリリース。','difficulty'=>2,'quiz'=>['question'=>'Git Flowのmainブランチの役割はどれか？','explanation'=>'Git Flowのmainはリリースされたコードのみがマージされる本番ブランチ。開発はdevelopブランチで行い、リリース準備時にmainにマージする。','choices'=>[['body'=>'日常的な開発を行うブランチ','is_correct'=>false],['body'=>'リリース済みの本番コードを管理するブランチ','is_correct'=>true],['body'=>'機能開発ごとに作るブランチ','is_correct'=>false],['body'=>'緊急修正専用のブランチ','is_correct'=>false]]]],
            ['name'=>'マージ vs リベース','definition'=>'Gitでブランチの変更を統合する2つの方法。mergeはコミット履歴を保持、rebaseは一直線の履歴を作る。どちらも一長一短。','example'=>'featureブランチをgit mergeするとマージコミットが残る。git rebase mainでfeatureのコミットをmainの先頭に移植して履歴を整理する。','difficulty'=>3,'quiz'=>['question'=>'git rebaseの説明として正しいものはどれか？','explanation'=>'rebaseは一方のブランチのコミットを別のブランチの先頭に移植してコミット履歴を一本化する。mergeコミットは作られないが履歴が書き換えられる。','choices'=>[['body'=>'2ブランチをマージしてマージコミットを作る','is_correct'=>false],['body'=>'コミットを別ブランチの先頭に移植して履歴を一本化する','is_correct'=>true],['body'=>'コミットを削除する','is_correct'=>false],['body'=>'プッシュと同じ操作','is_correct'=>false]]]],
            ['name'=>'コンパイラ vs インタープリタ','definition'=>'コンパイラはソースコード全体を事前に機械語に変換してから実行。インタープリタはコードを1行ずつ読み込みながら実行する。','example'=>'C/RustはコンパイラでOS依存の実行ファイルを生成。PythonはCPythonインタープリタが1行ずつ実行するため移植性が高い。','difficulty'=>2,'quiz'=>['question'=>'コンパイル型言語がインタープリタ型より一般的に速い理由はどれか？','explanation'=>'コンパイル型言語は実行前に最適化された機械語を生成するため実行時の変換処理が不要。インタープリタは実行時に逐次翻訳するためオーバーヘッドがある。','choices'=>[['body'=>'コンパイラの方がデバッグが簡単だから','is_correct'=>false],['body'=>'事前に最適化された機械語を生成し実行時の変換処理が不要だから','is_correct'=>true],['body'=>'コンパイル型はメモリを使わないから','is_correct'=>false],['body'=>'インタープリタは並列処理ができないから','is_correct'=>false]]]],
            ['name'=>'静的型付け vs 動的型付け','definition'=>'静的型付け（Java,TypeScript,Rust）はコンパイル時に型を検証。動的型付け（Python,JavaScript,Ruby）は実行時に型が決まる。','example'=>'静的型付けのTypeScriptでstring変数にnumberを代入するとコンパイルエラー。PythonはRuntimeまでエラーが出ない。','difficulty'=>2,'quiz'=>['question'=>'静的型付けのメリットとして正しいものはどれか？','explanation'=>'静的型付けはコンパイル時に型エラーを検出できるためバグを早期発見でき、IDEの補完・リファクタリングも充実する。','choices'=>[['body'=>'コードを短く書ける','is_correct'=>false],['body'=>'コンパイル時に型エラーを検出でき早期バグ発見・IDE補完が充実','is_correct'=>true],['body'=>'実行が速い（常に）','is_correct'=>false],['body'=>'型宣言が不要','is_correct'=>false]]]],
            ['name'=>'デコレータ（Decorator/Annotation）','definition'=>'クラス・メソッド・プロパティに付与するメタデータ。実装を変えずに機能を追加・変更できる。Pythonの@・Javaの@Override・TypeScriptの@が代表。','example'=>'@LogExecutionTime デコレータをメソッドに付与すると、自動的に実行時間をログ記録する機能が追加される。','difficulty'=>3,'quiz'=>['question'=>'デコレータパターンとデコレータ構文の共通点はどれか？','explanation'=>'どちらも元のクラス・関数のコードを変更せずに振る舞いを追加（ラップ）する点が共通。Pythonのデコレータ構文はデコレータパターンをシンタックスシュガーで表現している。','choices'=>[['body'=>'全く関係ない概念','is_correct'=>false],['body'=>'元のコードを変えずに振る舞いを追加（ラップ）する点が共通','is_correct'=>true],['body'=>'どちらも継承の一形態','is_correct'=>false],['body'=>'どちらも例外処理専用','is_correct'=>false]]]],
            ['name'=>'シリアライゼーション','definition'=>'オブジェクトをJSON・XML・バイナリなどの形式に変換（シリアライズ）・復元（デシリアライズ）するプロセス。データの永続化・通信に使われる。','example'=>'LaravelのAPIでEloquentモデルをJSON文字列にシリアライズしてHTTPレスポンスとして返し、フロントのaxiosがデシリアライズしてオブジェクトで使う。','difficulty'=>2,'quiz'=>['question'=>'シリアライゼーションの主な用途はどれか？','explanation'=>'シリアライゼーションはオブジェクトをファイル保存・ネットワーク送信・DBへの保存に適した形式に変換するために使われる。デシリアライズで元のオブジェクトに復元できる。','choices'=>[['body'=>'コードを圧縮する','is_correct'=>false],['body'=>'オブジェクトを保存・送信可能な形式に変換する','is_correct'=>true],['body'=>'データを暗号化する','is_correct'=>false],['body'=>'テストを自動化する','is_correct'=>false]]]],
            ['name'=>'ドメイン駆動設計（DDD）','definition'=>'ビジネスドメインの知識をソフトウェアモデルに反映させる設計アプローチ。エンティティ・バリューオブジェクト・集約・リポジトリなどの概念がある。','example'=>'ECサイトで「注文（Order）」をルート集約として定義し、注文明細・配送先をその内部オブジェクトとして管理するDDD設計。','difficulty'=>5,'quiz'=>['question'=>'DDDの「ユビキタス言語」が意味することはどれか？','explanation'=>'ユビキタス言語はドメインの専門家と開発者が共通して使う用語・概念の語彙。会話・コード・ドキュメントで同じ言葉を使うことでドメイン知識をコードに正確に反映する。','choices'=>[['body'=>'多言語対応の実装手法','is_correct'=>false],['body'=>'ドメイン専門家と開発者が共通で使うビジネス用語の語彙','is_correct'=>true],['body'=>'ユニバーサルなプログラミング言語','is_correct'=>false],['body'=>'自動翻訳機能','is_correct'=>false]]]],
            ['name'=>'正規表現（RegExp）','definition'=>'文字列のパターンを記述する構文。バリデーション・検索・置換に広く使われる。メタ文字（.  * + ? [] {} | ^ $ \\）で柔軟なパターンを定義する。','example'=>'/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/ でメールアドレスフォーマットを検証する正規表現。','difficulty'=>3,'quiz'=>['question'=>'正規表現の ^ が文字クラス[] の外で使われる場合の意味はどれか？','explanation'=>'^は文字クラス外では「文字列の先頭」を意味する。/^hello/は文字列がhelloで始まるものにマッチする。文字クラス内の[^abc]は「abc以外」の意味。','choices'=>[['body'=>'任意の1文字','is_correct'=>false],['body'=>'文字列の先頭','is_correct'=>true],['body'=>'前の要素の0回以上の繰り返し','is_correct'=>false],['body'=>'文字列の末尾','is_correct'=>false]]]],
            ['name'=>'文字エンコーディング（UTF-8）','definition'=>'文字をバイト列に変換する規則。UTF-8は世界中の文字をUnicodeで1〜4バイトで表現するエンコーディングでWebの標準。','example'=>'HTMLのhead に <meta charset="UTF-8"> を設定しないと日本語が文字化けする。ファイルの保存形式もUTF-8に統一する。','difficulty'=>2,'quiz'=>['question'=>'UTF-8がASCIIと後方互換である理由はどれか？','explanation'=>'UTF-8はASCII文字（0-127）を同じ1バイトで表現する設計のため、ASCII文字のみのテキストはUTF-8でも問題なく読める。','choices'=>[['body'=>'UTF-8はASCIIの拡張規格だから','is_correct'=>false],['body'=>'ASCII文字（0-127）を同じ1バイトで表現するため','is_correct'=>true],['body'=>'両者はまったく同じエンコーディング','is_correct'=>false],['body'=>'UTF-8はASCIIより文字を少なく使うから','is_correct'=>false]]]],
            ['name'=>'メモリリーク','definition'=>'使用済みメモリが解放されずに蓄積し続けるバグ。GC言語でもイベントリスナー解除忘れ・クロージャによるオブジェクト保持でも発生する。','example'=>'Vue.jsのコンポーネント内でdocument.addEventListener を追加したがonUnmounted でremoveEventListenerを忘れるとメモリリークする。','difficulty'=>3,'quiz'=>['question'=>'JavaScriptでメモリリークが起きやすい原因はどれか？','explanation'=>'解除されていないイベントリスナー・クロージャによるDOM参照保持・グローバル変数への蓄積がJSでのメモリリークの主な原因。GCがあっても参照が残れば回収されない。','choices'=>[['body'=>'変数を多く使いすぎる','is_correct'=>false],['body'=>'解除されていないイベントリスナーやクロージャのDOM参照保持','is_correct'=>true],['body'=>'非同期処理を使う','is_correct'=>false],['body'=>'関数を多く定義する','is_correct'=>false]]]],
            ['name'=>'スレッドセーフ','definition'=>'複数スレッドから同時にアクセスされても正しく動作するプログラム・データ構造の性質。競合状態（Race Condition）を防ぐ設計が重要。','example'=>'カウンター変数を複数スレッドが同時インクリメントする場合、ロック（Mutex）や原子的操作を使わないと競合状態でカウントが狂う。','difficulty'=>3,'quiz'=>['question'=>'スレッドセーフでないコードで起きる問題はどれか？','explanation'=>'複数スレッドが同一メモリを保護なしに読み書きすると、タイミングによって結果が変わる競合状態（Race Condition）が発生しデータが破損する可能性がある。','choices'=>[['body'=>'コンパイルエラー','is_correct'=>false],['body'=>'競合状態（Race Condition）によるデータの不整合','is_correct'=>true],['body'=>'メモリリーク','is_correct'=>false],['body'=>'スタックオーバーフロー','is_correct'=>false]]]],
            ['name'=>'技術的負債（Technical Debt）','definition'=>'将来の開発コストを増大させる設計上の欠陥・近道・先送りの蓄積。短期的な素早さと長期的な品質のトレードオフ。','example'=>'テストなしで急ぎで実装した機能が増え、変更のたびに予期しないバグが発生して修正コストが高くなる状態が技術的負債。','difficulty'=>2,'quiz'=>['question'=>'技術的負債を放置した場合の影響はどれか？','explanation'=>'技術的負債は蓄積するほど新機能追加・バグ修正コストが増大し、開発スピードが低下する。定期的なリファクタリングで返済が必要。','choices'=>[['body'=>'自動的に解消される','is_correct'=>false],['body'=>'開発コスト・スピードが悪化し続ける','is_correct'=>true],['body'=>'セキュリティのみに影響する','is_correct'=>false],['body'=>'ユーザー体験には影響しない','is_correct'=>false]]]],
            ['name'=>'末尾再帰最適化（TCO）','definition'=>'再帰呼び出しが関数の最後の操作のとき、スタックフレームを追加せずにループに変換するコンパイラ最適化。スタックオーバーフローを防ぐ。','example'=>'Schemeや一部のHaskell処理系ではTCOにより深い再帰でもスタックを消費せず実行できる。JavaScriptのV8はTCOをサポートしない。','difficulty'=>5,'quiz'=>['question'=>'末尾再帰最適化が適用される条件はどれか？','explanation'=>'TCOは再帰呼び出しが関数内の最後の処理（戻り値を直接返す）である末尾再帰の形式のときのみ適用可能。計算結果を使って何かを行う再帰には適用できない。','choices'=>[['body'=>'任意の再帰関数に適用できる','is_correct'=>false],['body'=>'再帰呼び出しが関数の最後の操作（末尾位置）のとき','is_correct'=>true],['body'=>'再帰の深さが100以上のとき','is_correct'=>false],['body'=>'コンパイラが判断し常に自動適用される','is_correct'=>false]]]],
            ['name'=>'APIファースト開発','definition'=>'UIよりAPIの設計・実装を先行させる開発アプローチ。OpenAPI仕様でAPIを先に定義しフロントとバックエンドが並行開発できる。','example'=>'OpenAPI YAMLでエンドポイントを先に定義→フロントはモックサーバー・バックは実装を並行して進め、統合テストで接続確認する。','difficulty'=>3,'quiz'=>['question'=>'APIファースト開発のメリットはどれか？','explanation'=>'APIを先に定義することでフロント・バックが並行開発でき、モックサーバーですぐ開発を開始できる。APIの一貫性・ドキュメントの整備も自然と促進される。','choices'=>[['body'=>'DBの設計が不要になる','is_correct'=>false],['body'=>'フロント・バックエンドの並行開発と一貫性のあるAPI設計が実現できる','is_correct'=>true],['body'=>'テストが不要になる','is_correct'=>false],['body'=>'コストが半減する','is_correct'=>false]]]],
            ['name'=>'循環参照','definition'=>'AがBを参照しBがAを参照する（または間接的に循環する）参照の閉路。GC言語でもメモリリークや無限ループの原因になる。','example'=>'ParentコンポーネントがChildを持ち、ChildがParentへの参照を持つ相互参照。GCがマーク&スイープでなくリファレンスカウントならリークする。','difficulty'=>4,'quiz'=>['question'=>'循環参照の問題として正しいものはどれか？','explanation'=>'参照カウント方式GCでは循環参照するオブジェクト群の参照カウントが0にならずメモリが回収されないメモリリークが発生する。マーク&スイープは循環参照を検出できる。','choices'=>[['body'=>'コンパイルエラーになる','is_correct'=>false],['body'=>'参照カウント方式のGCでメモリリークが発生する','is_correct'=>true],['body'=>'実行時間が短くなる','is_correct'=>false],['body'=>'型エラーになる','is_correct'=>false]]]],
            ['name'=>'クリーンアーキテクチャ','definition'=>'Robertマーチンが提唱するアーキテクチャ。依存関係を内側（ドメイン）→外側（インフラ）の一方向にし、ビジネスルールをフレームワーク等に依存させない設計。','example'=>'UserRepositoryインターフェースをdomainに定義し、LaravelのEloquent実装はinfra層に置く。テスト時はインメモリ実装を注入する。','difficulty'=>5,'quiz'=>['question'=>'クリーンアーキテクチャの依存関係の方向として正しいものはどれか？','explanation'=>'クリーンアーキテクチャでは外側のレイヤー（UI・DB・フレームワーク）が内側（ドメイン・ビジネスルール）に依存する。逆は禁止（依存性逆転の原則）。','choices'=>[['body'=>'内側（ドメイン）が外側（インフラ）に依存する','is_correct'=>false],['body'=>'外側（インフラ）が内側（ドメイン）に依存する','is_correct'=>true],['body'=>'全レイヤーが相互依存する','is_correct'=>false],['body'=>'依存関係は存在しない','is_correct'=>false]]]],
        ]];
    }

    private function osLinuxTerms(): array
    {
        return ['os-linux' => [
            ['name'=>'ファイルシステム（ext4/xfs）','definition'=>'ディスク上のデータをファイル・ディレクトリとして管理する構造。LinuxはExt4がデフォルト、XFSは大容量向け。NTFS(Windows)・APFS(Mac)など。','example'=>'sudo mkfs.ext4 /dev/sdb1 で新しいディスクパーティションをExt4でフォーマットしてマウントして使う。','difficulty'=>3,'quiz'=>['question'=>'Linuxで最も広く使われるファイルシステムはどれか？','explanation'=>'Ext4（Fourth Extended Filesystem）は信頼性とパフォーマンスのバランスが良く、多くのLinuxディストリビューションのデフォルトとして採用されている。','choices'=>[['body'=>'NTFS','is_correct'=>false],['body'=>'Ext4','is_correct'=>true],['body'=>'FAT32','is_correct'=>false],['body'=>'APFS','is_correct'=>false]]]],
            ['name'=>'マウント（mount）','definition'=>'ストレージデバイス・パーティション・ネットワーク共有をファイルシステムの特定ディレクトリに接続する操作。','example'=>'sudo mount /dev/sdb1 /mnt/data でUSBメモリを/mnt/dataにマウントし、そこでファイルにアクセスできるようになる。','difficulty'=>2,'quiz'=>['question'=>'LinuxでUSBメモリなどを/mnt/usbにマウントするコマンドはどれか？','explanation'=>'mountコマンドでデバイスファイル（/dev/sdb1等）をディレクトリに関連付ける。umountでアンマウント（取り外し）する。','choices'=>[['body'=>'sudo attach /dev/sdb1 /mnt/usb','is_correct'=>false],['body'=>'sudo mount /dev/sdb1 /mnt/usb','is_correct'=>true],['body'=>'sudo connect /dev/sdb1 /mnt/usb','is_correct'=>false],['body'=>'sudo link /dev/sdb1 /mnt/usb','is_correct'=>false]]]],
            ['name'=>'LVM（Logical Volume Manager）','definition'=>'物理ボリューム（PV）→ボリュームグループ（VG）→論理ボリューム（LV）の階層で柔軟なディスク管理を実現する技術。ディスク追加・サイズ変更が容易。','example'=>'LVMでルートパーティションが足りなくなったとき、新しいディスクをVGに追加してLVを拡張することで無停止でディスクを増やせる。','difficulty'=>4,'quiz'=>['question'=>'LVMを使う主なメリットはどれか？','explanation'=>'LVMにより物理ディスクの境界を超えた論理ボリュームを作成でき、動的なサイズ変更・スナップショット・複数ディスクの統合が容易になる。','choices'=>[['body'=>'ディスクの読み書き速度が向上する','is_correct'=>false],['body'=>'物理ディスクに依存せず柔軟にボリュームサイズを変更できる','is_correct'=>true],['body'=>'自動的にRAIDを構成する','is_correct'=>false],['body'=>'ファイルシステムの種類を変更できる','is_correct'=>false]]]],
            ['name'=>'RAID（Redundant Array of Inexpensive Disks）','definition'=>'複数のディスクを組み合わせて冗長性やパフォーマンスを向上させる技術。RAID0（ストライピング）・RAID1（ミラーリング）・RAID5・RAID6など。','example'=>'RAID1でディスク2台を同じデータでミラーリングし、1台故障しても残りから復旧できる可用性を確保する。','difficulty'=>3,'quiz'=>['question'=>'RAID1（ミラーリング）の特徴はどれか？','explanation'=>'RAID1は同一データを2台以上のディスクに書き込む。1台故障しても他のディスクからデータを復旧できる高可用性を提供するがストレージ効率は50%。','choices'=>[['body'=>'データを分散して高速読み書きする','is_correct'=>false],['body'=>'同一データを複数ディスクにコピーして耐障害性を確保する','is_correct'=>true],['body'=>'パリティ情報で1台故障から復旧できる','is_correct'=>false],['body'=>'データを圧縮して保存する','is_correct'=>false]]]],
            ['name'=>'awk','definition'=>'パターンマッチングとフィールド処理に特化したテキスト処理プログラミング言語/コマンド。CSVや空白区切りデータの加工に最適。','example'=>'ps aux | awk \'{print $1, $2, $11}\' でプロセス一覧からユーザー名・PID・コマンドを抽出して表示する。','difficulty'=>3,'quiz'=>['question'=>'awkのフィールド区切り変数はどれか？','explanation'=>'awkではデフォルトで空白・タブがフィールド区切りで、$1が1番目のフィールド、$2が2番目...、$0が行全体を表す。FSで区切り文字を変更できる。','choices'=>[['body'=>'$col と $row','is_correct'=>false],['body'=>'$1, $2...（番号で各フィールド、$0は行全体）','is_correct'=>true],['body'=>'[1], [2]','is_correct'=>false],['body'=>'%1, %2','is_correct'=>false]]]],
            ['name'=>'sed（Stream Editor）','definition'=>'テキストの置換・削除・挿入・抽出をストリームで行うコマンド。スクリプトで大量のファイルを一括変換するのに使われる。','example'=>'sed -i "s/localhost/production.example.com/g" config.txt でconfig.txt内のlocalhostを全て置換する。','difficulty'=>3,'quiz'=>['question'=>'sed \'s/foo/bar/g\' の意味はどれか？','explanation'=>'sはsubstitute（置換）コマンド、/foo/bar/はfooをbarに置換するパターン、gフラグは行内の全マッチを置換（デフォルトは最初の1つのみ）。','choices'=>[['body'=>'fooを削除してbarを表示する','is_correct'=>false],['body'=>'行内のfooを全てbarに置換する','is_correct'=>true],['body'=>'fooとbarの行を入れ替える','is_correct'=>false],['body'=>'fooを含む行を削除する','is_correct'=>false]]]],
            ['name'=>'find','definition'=>'ファイル・ディレクトリを名前・種類・サイズ・更新日時などの条件で検索するコマンド。-execオプションでマッチしたファイルに処理を適用できる。','example'=>'find /var/log -name "*.log" -mtime +30 -exec rm {} \\; で30日以上前の.logファイルを自動削除する。','difficulty'=>2,'quiz'=>['question'=>'find . -name "*.py" -type f コマンドが検索するものはどれか？','explanation'=>'-type fはファイル（directoryでない）に限定し、-name "*.py"はPythonファイルのみを対象にする。合わせてカレントディレクトリ以下のPythonファイルを検索。','choices'=>[['body'=>'pyという名前のディレクトリ','is_correct'=>false],['body'=>'カレントディレクトリ以下の.pyファイル','is_correct'=>true],['body'=>'Pythonがインストールされているパス','is_correct'=>false],['body'=>'.pyで終わるシンボリックリンク','is_correct'=>false]]]],
            ['name'=>'xargs','definition'=>'標準入力や別コマンドの出力を引数として別コマンドに渡すコマンド。パイプと組み合わせて大量のファイルを一括処理するのに使われる。','example'=>'find . -name "*.tmp" | xargs rm でfindで見つかった全tmpファイルをrmコマンドで削除する。','difficulty'=>3,'quiz'=>['question'=>'xargsを使う主な理由はどれか？','explanation'=>'パイプは出力を次コマンドの「標準入力」に渡すが、rmなど引数として受け取る必要があるコマンドにはxargsを使い標準入力を「引数」として渡す。','choices'=>[['body'=>'コマンドを並列実行するため','is_correct'=>false],['body'=>'標準入力を別コマンドの引数として渡すため','is_correct'=>true],['body'=>'テキストを置換するため','is_correct'=>false],['body'=>'ファイルを圧縮するため','is_correct'=>false]]]],
            ['name'=>'tar（アーカイブ）','definition'=>'複数ファイルを1つのアーカイブファイルにまとめるコマンド。gzip/bzip2/xzと組み合わせて圧縮もできる。','example'=>'tar -czf backup.tar.gz /var/www で/var/wwwをgzip圧縮したアーカイブを作成。tar -xzf backup.tar.gz で解凍。','difficulty'=>1,'quiz'=>['question'=>'tar -xzf archive.tar.gz の各オプションの意味はどれか？','explanation'=>'x=extract（解凍）、z=gzip圧縮/解凍を経由、f=ファイル名を指定。合わせてgzip圧縮されたtarアーカイブを解凍するオプション。','choices'=>[['body'=>'x=削除 z=zip圧縮 f=強制実行','is_correct'=>false],['body'=>'x=解凍 z=gzip処理 f=ファイル指定','is_correct'=>true],['body'=>'x=実行 z=サイズ表示 f=ファイル検索','is_correct'=>false],['body'=>'x=暗号化 z=圧縮率 f=フォルダ指定','is_correct'=>false]]]],
            ['name'=>'rsync','definition'=>'差分のみを転送する効率的なファイル同期・バックアップコマンド。ローカル/リモート間の同期とSSHを使った安全な転送が可能。','example'=>'rsync -avz /local/data/ user@remote:/backup/data/ でローカルファイルをリモートサーバーに差分同期する。','difficulty'=>2,'quiz'=>['question'=>'rsyncがscpより優れている主な点はどれか？','explanation'=>'rsyncは差分のみを転送するため2回目以降のバックアップが高速。scpは毎回ファイル全体を転送するため大量ファイルの同期に非効率。','choices'=>[['body'=>'暗号化が強力','is_correct'=>false],['body'=>'差分のみ転送して2回目以降のバックアップが高速','is_correct'=>true],['body'=>'GUIで操作できる','is_correct'=>false],['body'=>'FTPより使いやすい','is_correct'=>false]]]],
            ['name'=>'ssh-keygen（鍵管理）','definition'=>'SSH接続で使う公開鍵・秘密鍵ペアを生成するコマンド。パスワード認証より安全なSSH公開鍵認証を実現する。','example'=>'ssh-keygen -t ed25519 -C "mail@example.com" で鍵ペアを生成し、公開鍵（id_ed25519.pub）をサーバーの~/.ssh/authorized_keysに登録する。','difficulty'=>2,'quiz'=>['question'=>'SSH公開鍵認証でサーバーに登録するのはどちらの鍵か？','explanation'=>'公開鍵（id_rsa.pub, id_ed25519.pub）をサーバーのauthorized_keysに登録する。秘密鍵はクライアントに保管し絶対にサーバーに送らない。','choices'=>[['body'=>'秘密鍵（id_rsa）','is_correct'=>false],['body'=>'公開鍵（id_rsa.pub）','is_correct'=>true],['body'=>'両方の鍵','is_correct'=>false],['body'=>'パスフレーズ','is_correct'=>false]]]],
            ['name'=>'ネットワーク設定（ipコマンド）','definition'=>'Linuxネットワークの設定・確認を行うコマンド。旧来のifconfigに代わるiproute2のipコマンドが現在の標準。','example'=>'ip addr show でネットワークインターフェースとIPアドレス確認。ip route show でルーティングテーブル表示。','difficulty'=>2,'quiz'=>['question'=>'LinuxでIPアドレスを確認する現代的なコマンドはどれか？','explanation'=>'現代のLinuxではipコマンド（iproute2パッケージ）が標準。ip addr はifconfigの代替、ip route はnetstatのroute機能の代替。','choices'=>[['body'=>'ipconfig','is_correct'=>false],['body'=>'ip addr show','is_correct'=>true],['body'=>'netcfg','is_correct'=>false],['body'=>'net show addr','is_correct'=>false]]]],
            ['name'=>'netstat / ss','definition'=>'ネットワーク接続・ルーティングテーブル・インターフェース統計・リスニングポートを表示するコマンド。ssはnetstatの高速版。','example'=>'ss -tulpn で現在リスニング中の全TCP/UDPポートとそれを使うプロセスを表示する。','difficulty'=>2,'quiz'=>['question'=>'ss -tulpn で確認できる情報はどれか？','explanation'=>'-t=TCP、-u=UDP、-l=LISTENのみ、-p=プロセス名、-n=数値表示。組み合わせでリスニング中のポートとプロセスを表示できる。','choices'=>[['body'=>'ディスク使用量','is_correct'=>false],['body'=>'リスニング中のTCP/UDPポートとプロセス名','is_correct'=>true],['body'=>'CPUの使用率','is_correct'=>false],['body'=>'実行中のDockerコンテナ一覧','is_correct'=>false]]]],
            ['name'=>'lsof（List Open Files）','definition'=>'システム上のプロセスが開いているファイル・ポート・ソケットを一覧表示するコマンド。特定ポートを使うプロセスの特定などに使われる。','example'=>'lsof -i :8080 でポート8080を使用しているプロセスを確認。lsof -u username でユーザーが開いているファイルを一覧表示。','difficulty'=>3,'quiz'=>['question'=>'ポート80を使用しているプロセスを確認するコマンドはどれか？','explanation'=>'lsof -i :80 でポート80を使用しているプロセスのPID・プロセス名・接続状態を表示する。ssやnetstatでも同様の確認が可能。','choices'=>[['body'=>'ps aux | grep 80','is_correct'=>false],['body'=>'lsof -i :80','is_correct'=>true],['body'=>'find / -name 80','is_correct'=>false],['body'=>'cat /proc/80','is_correct'=>false]]]],
            ['name'=>'ファイルディスクリプタ','definition'=>'Linuxでファイル・ソケット・パイプなどのI/Oリソースを表す整数値。0=標準入力、1=標準出力、2=標準エラー出力がデフォルト。','example'=>'コマンドを実行すると3, 4, 5...のFDが割り当てられる。cat /proc/PID/fd でプロセスが開いているFDを確認できる。','difficulty'=>3,'quiz'=>['question'=>'LinuxでFD 2（ファイルディスクリプタ2）が表すものはどれか？','explanation'=>'fd0=標準入力（stdin）、fd1=標準出力（stdout）、fd2=標準エラー出力（stderr）がデフォルトで割り当てられる。','choices'=>[['body'=>'標準入力（stdin）','is_correct'=>false],['body'=>'標準エラー出力（stderr）','is_correct'=>true],['body'=>'標準出力（stdout）','is_correct'=>false],['body'=>'最初に開いたファイル','is_correct'=>false]]]],
            ['name'=>'ulimit','definition'=>'プロセスが使用できるリソース（開けるファイル数・メモリ・プロセス数・ファイルサイズ）の上限を設定するコマンド。','example'=>'ulimit -n 65536 でセッションのopenfile数上限を65536に増やす。高接続数のNginxやDB設定で必要になる。','difficulty'=>3,'quiz'=>['question'=>'ulimit -n が制御するリソースはどれか？','explanation'=>'-n（files）は1プロセスが同時に開けるファイルディスクリプタの最大数を制御する。Webサーバーの同時接続数に影響する重要パラメータ。','choices'=>[['body'=>'最大プロセス数','is_correct'=>false],['body'=>'同時に開けるファイルディスクリプタの最大数','is_correct'=>true],['body'=>'最大メモリ使用量','is_correct'=>false],['body'=>'CPUコア数の割り当て','is_correct'=>false]]]],
            ['name'=>'ジョブ制御（jobs, fg, bg）','definition'=>'シェルでコマンドをバックグラウンドで実行したり（&）、フォアグラウンドとバックグラウンドを切り替えるシェルの機能。','example'=>'command & でバックグラウンド実行、Ctrl+Zで一時停止、bg %1 でバックグラウンド再開、fg %1 でフォアグラウンドに戻す。','difficulty'=>2,'quiz'=>['question'=>'コマンドをバックグラウンドで実行する方法はどれか？','explanation'=>'コマンドの末尾に & を付けるとバックグラウンドで実行され、ターミナルがすぐ戻る。[1] 12345 のようにジョブ番号とPIDが表示される。','choices'=>[['body'=>'sudo command','is_correct'=>false],['body'=>'command &','is_correct'=>true],['body'=>'bg command','is_correct'=>false],['body'=>'nohup command','is_correct'=>false]]]],
            ['name'=>'alias（エイリアス）','definition'=>'長いコマンドや頻繁に使うコマンドに短い別名を定義する機能。~/.bashrcに記述して永続化する。','example'=>'alias ll="ls -la --color" と定義すると、以降 ll と入力するだけで ls -la --color が実行される。','difficulty'=>1,'quiz'=>['question'=>'aliasを永続化（ログイン後も有効）させるには何に記述するか？','explanation'=>'aliasをターミナルで設定しても、セッションが終わると消える。~/.bashrc（Bash）や~/.zshrc（Zsh）に記述してsource ~/.bashrcで読み込み直すと永続化される。','choices'=>[['body'=>'/etc/passwd','is_correct'=>false],['body'=>'~/.bashrc（または~/.zshrc）','is_correct'=>true],['body'=>'/proc/alias','is_correct'=>false],['body'=>'/bin/alias','is_correct'=>false]]]],
            ['name'=>'historyコマンド','definition'=>'過去に実行したコマンドの履歴を表示するコマンド。!番号で履歴の再実行、!!で直前のコマンド、Ctrl+Rで逆検索ができる。','example'=>'history | grep "docker" で過去に実行したdockerコマンドを絞り込み。!234 でhistory番号234のコマンドを再実行。','difficulty'=>1,'quiz'=>['question'=>'Ctrl+R の機能はどれか？','explanation'=>'Ctrl+Rはreverse-i-searchで、過去のコマンド履歴をインクリメンタルに逆検索する機能。文字を入力するたびに一致するコマンドが絞り込まれる。','choices'=>[['body'=>'コマンドを中断する','is_correct'=>false],['body'=>'コマンド履歴を逆検索する','is_correct'=>true],['body'=>'新しいターミナルを開く','is_correct'=>false],['body'=>'前のコマンドをキャンセルする','is_correct'=>false]]]],
            ['name'=>'ハードリンク','definition'=>'同一ファイルのinodeを指す別の名前（ディレクトリエントリ）。元ファイルを削除してもハードリンクが残ればデータは消えない。','example'=>'ln original.txt hardlink.txt でハードリンクを作成。ls -li で両ファイルが同じinode番号を持つことを確認できる。','difficulty'=>3,'quiz'=>['question'=>'ハードリンクの特性として正しいものはどれか？','explanation'=>'ハードリンクは同一inodeを共有するため、元のファイルを削除してもハードリンクが残ればデータは削除されない（inodeの参照カウントが0になるまで保持）。','choices'=>[['body'=>'シンボリックリンクと同じ仕組み','is_correct'=>false],['body'=>'元ファイル削除後もハードリンクでデータにアクセスできる','is_correct'=>true],['body'=>'異なるファイルシステムをまたいで作成できる','is_correct'=>false],['body'=>'ディレクトリにも作成できる（通常ユーザーでも）','is_correct'=>false]]]],
            ['name'=>'strace','definition'=>'プロセスが行うシステムコールとシグナルをリアルタイムに追跡するデバッグツール。障害調査・パフォーマンス分析に使われる。','example'=>'strace -p 1234 で実行中のプロセス(PID=1234)のシステムコールをリアルタイム表示し、どのファイルにアクセスしているか追跡する。','difficulty'=>4,'quiz'=>['question'=>'straceが主に使われる場面はどれか？','explanation'=>'straceはプロセスが実行するシステムコール（open・read・write・connect等）を逐一表示するため、アプリの動作不明時やパフォーマンス調査に有用。','choices'=>[['body'=>'ネットワークパケットを解析する','is_correct'=>false],['body'=>'プロセスのシステムコールを追跡してデバッグする','is_correct'=>true],['body'=>'ディスクのI/O速度を計測する','is_correct'=>false],['body'=>'CPUのキャッシュミスを計測する','is_correct'=>false]]]],
            ['name'=>'カーネルモジュール','definition'=>'実行中のLinuxカーネルに動的にロード・アンロードできるドライバー・機能の単位。lsmod・modprobe・rmmodで管理する。','example'=>'modprobe nf_conntrack でファイアウォール用カーネルモジュールをロード。lsmod でロード済みモジュール一覧を表示する。','difficulty'=>4,'quiz'=>['question'=>'Linuxカーネルモジュールを手動でロードするコマンドはどれか？','explanation'=>'modprobeは依存するモジュールも自動的にロードする推奨コマンド。insmodは単体ファイルを直接ロードするがdep解決なし。','choices'=>[['body'=>'apt install module-name','is_correct'=>false],['body'=>'modprobe module-name','is_correct'=>true],['body'=>'systemctl start module-name','is_correct'=>false],['body'=>'load kernel module-name','is_correct'=>false]]]],
            ['name'=>'プロセス間通信（IPC）','definition'=>'同一システム上の異なるプロセスがデータを交換する仕組み。パイプ・ソケット・共有メモリ・メッセージキュー・シグナル等がある。','example'=>'名前付きパイプ（FIFO）でWebサーバーとバックエンドプロセスを接続し、高速なIPC通信を実現する。','difficulty'=>4,'quiz'=>['question'=>'同一ホスト上のプロセス間通信で最速の手段はどれか？','explanation'=>'共有メモリはメモリをプロセス間で直接共有するためデータのコピーが不要で最速。ただし競合管理のためミューテックス等が必要。','choices'=>[['body'=>'TCPソケット','is_correct'=>false],['body'=>'共有メモリ（Shared Memory）','is_correct'=>true],['body'=>'名前付きパイプ','is_correct'=>false],['body'=>'シグナル','is_correct'=>false]]]],
        ]];
    }
}
