<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Choice;
use App\Models\Quiz;
use App\Models\Term;
use Illuminate\Database\Seeder;

class AdditionalTermSeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->networkTerms()
            + $this->securityTerms()
            + $this->databaseTerms()
            + $this->algorithmTerms()
            + $this->cloudTerms()
            + $this->webTerms()
            + $this->programmingTerms()
            + $this->osLinuxTerms();

        foreach ($data as $slug => $terms) {
            $cat = Category::where('slug', $slug)->first();
            if (!$cat) continue;
            foreach ($terms as $t) {
                $term = Term::updateOrCreate(
                    ['name' => $t['name'], 'category_id' => $cat->id],
                    [
                        'definition' => $t['definition'],
                        'example'    => $t['example'] ?? null,
                        'difficulty' => $t['difficulty'],
                    ]
                );
                if (!empty($t['quiz'])) {
                    $quiz = Quiz::updateOrCreate(
                        ['term_id' => $term->id, 'question' => $t['quiz']['question']],
                        ['explanation' => $t['quiz']['explanation']]
                    );
                    foreach ($t['quiz']['choices'] as $c) {
                        Choice::updateOrCreate(
                            ['quiz_id' => $quiz->id, 'body' => $c['body']],
                            ['is_correct' => $c['is_correct']]
                        );
                    }
                }
            }
        }
    }

    private function networkTerms(): array
    {
        return ['network' => [
            ['name'=>'UDP（User Datagram Protocol）','definition'=>'コネクションレスで軽量なトランスポート層プロトコル。信頼性より速度を優先する。','example'=>'動画ストリーミングやDNSクエリ、VoIPで使われる。','difficulty'=>2,'quiz'=>['question'=>'UDPの特徴として正しいものはどれか？','explanation'=>'UDPはコネクションを確立せず、パケットの順序保証や再送制御を行わないため高速。','choices'=>[['body'=>'コネクション確立後に通信する','is_correct'=>false],['body'=>'再送制御を行わず高速に送信する','is_correct'=>true],['body'=>'データの順序を保証する','is_correct'=>false],['body'=>'TCPより信頼性が高い','is_correct'=>false]]]],
            ['name'=>'DHCP（Dynamic Host Configuration Protocol）','definition'=>'ネットワーク機器にIPアドレスなどの設定を自動的に割り当てるプロトコル。','example'=>'PCをWi-Fiに接続すると、DHCPサーバーから自動でIPアドレスが付与される。','difficulty'=>2,'quiz'=>['question'=>'DHCPの役割として正しいものはどれか？','explanation'=>'DHCPはクライアントに対してIPアドレス・サブネットマスク・デフォルトゲートウェイなどを自動配布する。','choices'=>[['body'=>'ドメイン名をIPに変換する','is_correct'=>false],['body'=>'IPアドレスを自動割り当てする','is_correct'=>true],['body'=>'データを暗号化する','is_correct'=>false],['body'=>'パケットを転送する','is_correct'=>false]]]],
            ['name'=>'NAT（Network Address Translation）','definition'=>'プライベートIPアドレスとグローバルIPアドレスを相互変換する技術。IPv4アドレスの枯渇対策でも使われる。','example'=>'家庭内の複数PCが1つのグローバルIPでインターネットに接続するために使われる。','difficulty'=>3,'quiz'=>['question'=>'NATの主な目的はどれか？','explanation'=>'NATにより複数のプライベートIPを1つのグローバルIPに変換することで、IPv4アドレス消費を節約できる。','choices'=>[['body'=>'通信を暗号化する','is_correct'=>false],['body'=>'プライベートIPとグローバルIPを変換する','is_correct'=>true],['body'=>'MACアドレスを変換する','is_correct'=>false],['body'=>'パケットを圧縮する','is_correct'=>false]]]],
            ['name'=>'VPN（Virtual Private Network）','definition'=>'公衆回線上に暗号化された仮想専用回線を構築する技術。リモートワークや拠点間接続に使われる。','example'=>'在宅勤務者がVPNクライアントで社内LANに安全に接続する。','difficulty'=>2,'quiz'=>['question'=>'VPNの主な目的はどれか？','explanation'=>'VPNは暗号化トンネリングにより、インターネット上に安全な仮想専用回線を実現する。','choices'=>[['body'=>'通信速度を高速化する','is_correct'=>false],['body'=>'インターネット上に安全な仮想専用回線を作る','is_correct'=>true],['body'=>'IPアドレスを自動割当する','is_correct'=>false],['body'=>'DNSを高速化する','is_correct'=>false]]]],
            ['name'=>'ファイアウォール','definition'=>'ネットワークの境界で通信を監視・制御し、不正アクセスを遮断するセキュリティ機器またはソフトウェア。','example'=>'企業ネットワークの出入口にファイアウォールを配置し、許可されたポートのみ通信を許可する。','difficulty'=>2,'quiz'=>['question'=>'ファイアウォールが通信制御で主に参照するものはどれか？','explanation'=>'パケットフィルタリング型ファイアウォールはIPアドレス・ポート番号・プロトコルを基に通信を許可/拒否する。','choices'=>[['body'=>'ファイルの内容','is_correct'=>false],['body'=>'IPアドレスとポート番号','is_correct'=>true],['body'=>'ユーザー名','is_correct'=>false],['body'=>'URLのパス','is_correct'=>false]]]],
            ['name'=>'MACアドレス','definition'=>'ネットワークインターフェースカードに製造時に割り当てられる48ビットの物理アドレス。データリンク層で使用。','example'=>'スイッチはMACアドレステーブルを参照して、正しいポートにフレームを転送する。','difficulty'=>2,'quiz'=>['question'=>'MACアドレスは何層で使用されるか？','explanation'=>'MACアドレスはOSI参照モデルのデータリンク層（第2層）で使用される物理アドレス。','choices'=>[['body'=>'ネットワーク層（第3層）','is_correct'=>false],['body'=>'データリンク層（第2層）','is_correct'=>true],['body'=>'トランスポート層（第4層）','is_correct'=>false],['body'=>'アプリケーション層（第7層）','is_correct'=>false]]]],
            ['name'=>'サブネットマスク','definition'=>'IPアドレスのネットワーク部とホスト部を区別するための値。CIDRとセットで使われる。','example'=>'255.255.255.0（/24）はホスト部8ビット、最大254台のホストを収容できる。','difficulty'=>3,'quiz'=>['question'=>'サブネットマスク255.255.255.0の場合、同一サブネット内に収容できる最大ホスト数はどれか？','explanation'=>'ホスト部8ビットの場合、2の8乗=256からネットワーク/ブロードキャストアドレスの2を引き254台。','choices'=>[['body'=>'253台','is_correct'=>false],['body'=>'254台','is_correct'=>true],['body'=>'256台','is_correct'=>false],['body'=>'255台','is_correct'=>false]]]],
            ['name'=>'OSI参照モデル','definition'=>'ネットワーク通信を7つの層（物理・データリンク・ネットワーク・トランスポート・セッション・プレゼンテーション・アプリケーション）に分けたモデル。','example'=>'HTTPはアプリケーション層（第7層）、TCPはトランスポート層（第4層）で動作する。','difficulty'=>3,'quiz'=>['question'=>'OSI参照モデルのトランスポート層（第4層）のプロトコルはどれか？','explanation'=>'TCPとUDPはOSI参照モデルのトランスポート層（第4層）に位置する。','choices'=>[['body'=>'HTTP','is_correct'=>false],['body'=>'TCP','is_correct'=>true],['body'=>'IP','is_correct'=>false],['body'=>'Ethernet','is_correct'=>false]]]],
            ['name'=>'IPv6','definition'=>'128ビットのIPアドレス体系。IPv4のアドレス枯渇問題を解決するために策定された次世代プロトコル。','example'=>'2001:db8::1のようにコロン区切りの16進数で表記される。','difficulty'=>3,'quiz'=>['question'=>'IPv6アドレスは何ビットか？','explanation'=>'IPv6は128ビットで構成され、理論上340澗個のアドレスを提供できる。','choices'=>[['body'=>'32ビット','is_correct'=>false],['body'=>'64ビット','is_correct'=>false],['body'=>'128ビット','is_correct'=>true],['body'=>'256ビット','is_correct'=>false]]]],
            ['name'=>'SSH（Secure Shell）','definition'=>'ネットワーク越しに安全に遠隔操作を行うためのプロトコル。通信が暗号化されている。','example'=>'サーバー管理者が「ssh user@192.168.1.10」でリモートサーバーにログインする。','difficulty'=>2,'quiz'=>['question'=>'SSHがTelnetより優れている主な点はどれか？','explanation'=>'SSHは通信を暗号化するため、パスワードやコマンドが盗聴されない。Telnetは平文通信。','choices'=>[['body'=>'転送速度が速い','is_correct'=>false],['body'=>'通信を暗号化する','is_correct'=>true],['body'=>'グラフィカルUIが使える','is_correct'=>false],['body'=>'UDPを使用する','is_correct'=>false]]]],
            ['name'=>'FTP（File Transfer Protocol）','definition'=>'ファイルを転送するためのプロトコル。認証情報が平文で流れるため、現在はSFTPやSCPが推奨される。','example'=>'Webサイトの更新ファイルをFTPクライアントでサーバーにアップロードする。','difficulty'=>2,'quiz'=>['question'=>'FTPのセキュリティ上の問題点はどれか？','explanation'=>'FTPはパスワードを含む通信が平文で行われるため、盗聴リスクがある。SFTPやFTPSが代替手段。','choices'=>[['body'=>'転送速度が遅い','is_correct'=>false],['body'=>'認証情報が平文で送信される','is_correct'=>true],['body'=>'ファイルサイズに制限がある','is_correct'=>false],['body'=>'TCPを使用しない','is_correct'=>false]]]],
            ['name'=>'ICMP（Internet Control Message Protocol）','definition'=>'ネットワークの診断や制御に使うプロトコル。pingやtracerouteの基盤となる。','example'=>'「ping 8.8.8.8」コマンドでICMPエコー要求を送り、応答時間でネットワーク疎通を確認する。','difficulty'=>3,'quiz'=>['question'=>'pingコマンドが使用するプロトコルはどれか？','explanation'=>'pingはICMPのエコー要求/応答を使ってホストの疎通確認と応答時間を測定する。','choices'=>[['body'=>'TCP','is_correct'=>false],['body'=>'UDP','is_correct'=>false],['body'=>'ICMP','is_correct'=>true],['body'=>'ARP','is_correct'=>false]]]],
            ['name'=>'ARP（Address Resolution Protocol）','definition'=>'IPアドレスからMACアドレスを解決するプロトコル。同一LAN内の通信で使われる。','example'=>'192.168.1.1宛に通信する際、ARPブロードキャストで対応するMACアドレスを取得する。','difficulty'=>3,'quiz'=>['question'=>'ARPの役割として正しいものはどれか？','explanation'=>'ARPはIPアドレスに対応するMACアドレスを調べる（名前解決とは別）。','choices'=>[['body'=>'ドメイン名をIPに変換する','is_correct'=>false],['body'=>'IPアドレスからMACアドレスを解決する','is_correct'=>true],['body'=>'プライベートIPをグローバルIPに変換する','is_correct'=>false],['body'=>'パケットをフィルタリングする','is_correct'=>false]]]],
            ['name'=>'VLAN（Virtual LAN）','definition'=>'物理的なネットワーク構成に依存せず、論理的にLANを分割する技術。セキュリティや管理効率向上に有効。','example'=>'1台のスイッチでVLAN 10（営業部）とVLAN 20（開発部）を論理的に分離する。','difficulty'=>3,'quiz'=>['question'=>'VLANの主な目的はどれか？','explanation'=>'VLANにより物理スイッチを論理的に複数のネットワークに分割でき、セキュリティとトラフィック分離が実現できる。','choices'=>[['body'=>'通信速度を向上させる','is_correct'=>false],['body'=>'物理ネットワークを論理的に分割する','is_correct'=>true],['body'=>'IPアドレスを節約する','is_correct'=>false],['body'=>'ファイルを転送する','is_correct'=>false]]]],
            ['name'=>'ポート番号','definition'=>'TCPやUDPでアプリケーションを識別する0〜65535の番号。HTTP:80、HTTPS:443、SSH:22、FTP:21など。','example'=>'Webサーバーはポート80でHTTP通信を待ち受ける（HTTPS は443）。','difficulty'=>1,'quiz'=>['question'=>'HTTPS通信のデフォルトポート番号はどれか？','explanation'=>'HTTPSはSSL/TLSによる暗号化通信でポート443を使用。HTTPのデフォルトは80。','choices'=>[['body'=>'80','is_correct'=>false],['body'=>'443','is_correct'=>true],['body'=>'22','is_correct'=>false],['body'=>'21','is_correct'=>false]]]],
            ['name'=>'3ウェイハンドシェイク','definition'=>'TCP接続確立時に行われる3段階のやり取り（SYN→SYN-ACK→ACK）。確実な接続確立を保証する。','example'=>'WebブラウザがサーバーにHTTPリクエストを送る前に3ウェイハンドシェイクでTCP接続を確立する。','difficulty'=>3,'quiz'=>['question'=>'3ウェイハンドシェイクの順序として正しいものはどれか？','explanation'=>'クライアントがSYNを送り、サーバーがSYN-ACKで応答し、クライアントがACKを返してTCP接続が確立される。','choices'=>[['body'=>'ACK→SYN→SYN-ACK','is_correct'=>false],['body'=>'SYN→SYN-ACK→ACK','is_correct'=>true],['body'=>'SYN-ACK→SYN→ACK','is_correct'=>false],['body'=>'SYN→ACK→SYN-ACK','is_correct'=>false]]]],
            ['name'=>'CIDR（Classless Inter-Domain Routing）','definition'=>'IPアドレスにプレフィックス長（/24など）を付けてネットワーク範囲を表す方式。クラスフルアドレッシングに代わる標準。','example'=>'192.168.1.0/24はホストアドレス範囲192.168.1.1〜192.168.1.254を表す。','difficulty'=>3,'quiz'=>['question'=>'/25のサブネットに収容できる最大ホスト数はどれか？','explanation'=>'ホスト部7ビット：2の7乗=128からネットワーク/ブロードキャストの2を引いて126台。','choices'=>[['body'=>'62台','is_correct'=>false],['body'=>'126台','is_correct'=>true],['body'=>'254台','is_correct'=>false],['body'=>'128台','is_correct'=>false]]]],
            ['name'=>'プロキシサーバー','definition'=>'クライアントとサーバーの間に入り代理として通信を中継するサーバー。キャッシュ・アクセス制御・匿名化などに使われる。','example'=>'企業ネットワークでプロキシを通してWebアクセスを制御し、不適切サイトをブロックする。','difficulty'=>2,'quiz'=>['question'=>'フォワードプロキシの主な用途として正しいものはどれか？','explanation'=>'フォワードプロキシはクライアント側に置かれ、インターネットへのアクセス制御やキャッシュに使われる。','choices'=>[['body'=>'サーバーの負荷分散','is_correct'=>false],['body'=>'クライアントのWebアクセス制御・キャッシュ','is_correct'=>true],['body'=>'DNSの名前解決','is_correct'=>false],['body'=>'IPアドレスの自動割当','is_correct'=>false]]]],
            ['name'=>'ロードバランサー','definition'=>'複数のサーバーにトラフィックを分散させて可用性とパフォーマンスを向上させる機器・ソフトウェア。','example'=>'ECサイトの入口にロードバランサーを置き、3台のWebサーバーへリクエストを均等に振り分ける。','difficulty'=>3,'quiz'=>['question'=>'ロードバランサーの主な役割はどれか？','explanation'=>'ロードバランサーは複数のサーバーにリクエストを分散し、単一サーバーへの集中を防いで可用性を高める。','choices'=>[['body'=>'通信を暗号化する','is_correct'=>false],['body'=>'複数サーバーへリクエストを分散する','is_correct'=>true],['body'=>'DNSを解決する','is_correct'=>false],['body'=>'ファイアウォールとして機能する','is_correct'=>false]]]],
            ['name'=>'CDN（Content Delivery Network）','definition'=>'世界中に分散したエッジサーバーにコンテンツをキャッシュし、ユーザーに近い場所から配信するネットワーク。','example'=>'CloudflareやAmazon CloudFrontを使うことでグローバルユーザーへの画像・動画配信を高速化する。','difficulty'=>3,'quiz'=>['question'=>'CDNを使う主な目的はどれか？','explanation'=>'CDNはユーザーに地理的に近いサーバーからコンテンツを配信し、レイテンシを削減しオリジンサーバーの負荷を軽減する。','choices'=>[['body'=>'データベースのクエリを高速化する','is_correct'=>false],['body'=>'ユーザー近くからコンテンツを配信して遅延を減らす','is_correct'=>true],['body'=>'ネットワークを暗号化する','is_correct'=>false],['body'=>'IPアドレスを動的に割り当てる','is_correct'=>false]]]],
            ['name'=>'BGP（Border Gateway Protocol）','definition'=>'インターネットの基幹を支えるルーティングプロトコル。AS（自律システム）間の経路情報を交換する。','example'=>'ISP同士がBGPで経路情報を交換し、インターネット全体の到達可能性を維持する。','difficulty'=>4,'quiz'=>['question'=>'BGPが使用されるのはどの場面か？','explanation'=>'BGPはAS（自律システム）間の経路制御に使うEGP（外部ゲートウェイプロトコル）であり、インターネットの骨格を支える。','choices'=>[['body'=>'同一LAN内の通信','is_correct'=>false],['body'=>'自律システム間の経路制御','is_correct'=>true],['body'=>'ホストへのIPアドレス配布','is_correct'=>false],['body'=>'ドメイン名の解決','is_correct'=>false]]]],
            ['name'=>'HTTP/2','definition'=>'HTTPの改良版。ヘッダー圧縮・多重化（マルチプレキシング）・サーバープッシュにより大幅なパフォーマンス向上を実現。','example'=>'HTTP/2により1つのTCP接続で複数リソースを並行取得でき、Webページ表示が高速になる。','difficulty'=>3,'quiz'=>['question'=>'HTTP/2がHTTP/1.1より優れている主な特徴はどれか？','explanation'=>'HTTP/2のマルチプレキシングにより1接続で複数リクエストを並行処理でき、HOL（Head-of-Line）ブロッキングを解消する。','choices'=>[['body'=>'UDPを使用する','is_correct'=>false],['body'=>'1接続で複数リクエストを多重化できる','is_correct'=>true],['body'=>'HTTPSが不要になる','is_correct'=>false],['body'=>'サーバーが不要になる','is_correct'=>false]]]],
            ['name'=>'TTL（Time To Live）','definition'=>'パケットやDNSレコードの有効期限。IPパケットではルーターを通過するたびに1減り、0になると破棄される。','example'=>'DNSのAレコードにTTL=3600を設定すると、1時間キャッシュされる。','difficulty'=>3,'quiz'=>['question'=>'IPパケットのTTLが0になるとどうなるか？','explanation'=>'TTLが0になったパケットはルーターが破棄し、送信元にICMP Time Exceededを返す。これによりルーティングループを防ぐ。','choices'=>[['body'=>'送信元に戻される','is_correct'=>false],['body'=>'ルーターが破棄しICMPエラーを返す','is_correct'=>true],['body'=>'宛先に強制送信される','is_correct'=>false],['body'=>'TTLがリセットされ転送が続く','is_correct'=>false]]]],
            ['name'=>'QoS（Quality of Service）','definition'=>'ネットワーク上のトラフィックに優先度を付け、重要な通信（音声・動画）の品質を保証する仕組み。','example'=>'VoIP通話トラフィックに最高優先度を与え、大容量ファイル転送より優先して送信する。','difficulty'=>4,'quiz'=>['question'=>'QoSの主な目的はどれか？','explanation'=>'QoSは帯域幅の割り当てや優先制御により、リアルタイム通信など重要トラフィックの品質を保証する。','choices'=>[['body'=>'通信を暗号化する','is_correct'=>false],['body'=>'トラフィックに優先度を付けて品質を保証する','is_correct'=>true],['body'=>'IPアドレスを変換する','is_correct'=>false],['body'=>'DNSを高速化する','is_correct'=>false]]]],
            ['name'=>'DMZ（DeMilitarized Zone）','definition'=>'ファイアウォールで内部ネットワークと外部ネットワークの間に設ける中間ネットワーク領域。公開サーバーを配置する。','example'=>'WebサーバーやメールサーバーをDMZに配置し、外部からのアクセスを受けつつ内部LANを保護する。','difficulty'=>4,'quiz'=>['question'=>'DMZにサーバーを配置する主な目的はどれか？','explanation'=>'DMZに公開サーバーを置くことで、サーバーが侵害されても内部ネットワークへの被害を最小化できる。','choices'=>[['body'=>'通信速度を向上させる','is_correct'=>false],['body'=>'公開サーバーを分離し内部ネットワークを保護する','is_correct'=>true],['body'=>'IPアドレスを節約する','is_correct'=>false],['body'=>'ファイルを共有する','is_correct'=>false]]]],
            ['name'=>'スループット','definition'=>'単位時間あたりに実際に転送されるデータ量。帯域幅（最大値）とは異なり、実際の通信性能を表す。','example'=>'100Mbpsの回線でもオーバーヘッドや輻輳があると実効スループットは70Mbps程度になることがある。','difficulty'=>3,'quiz'=>['question'=>'スループットと帯域幅の関係として正しいものはどれか？','explanation'=>'スループットは実際の転送速度で、オーバーヘッドや障害により常に帯域幅（理論最大値）以下になる。','choices'=>[['body'=>'スループットは帯域幅より常に大きい','is_correct'=>false],['body'=>'スループットは帯域幅以下の実効速度','is_correct'=>true],['body'=>'両者は常に等しい','is_correct'=>false],['body'=>'帯域幅はスループットの半分','is_correct'=>false]]]],
            ['name'=>'レイテンシ','definition'=>'データが送信元から宛先に届くまでの遅延時間。ミリ秒（ms）単位で測定され、通信品質の重要指標。','example'=>'日本からアメリカへのpingは約120ms、国内サーバーなら数ms以下になることが多い。','difficulty'=>2,'quiz'=>['question'=>'レイテンシを悪化させる主な要因はどれか？','explanation'=>'物理的な距離が長いほど電気信号の伝播遅延が増加し、レイテンシが大きくなる。また中継機器での処理遅延も影響する。','choices'=>[['body'=>'帯域幅が広い','is_correct'=>false],['body'=>'物理的な距離が長い','is_correct'=>true],['body'=>'パケットサイズが小さい','is_correct'=>false],['body'=>'TCPを使用する','is_correct'=>false]]]],
            ['name'=>'WebSocket','definition'=>'1つのTCP接続を使ってサーバーとクライアントが双方向リアルタイム通信を行うプロトコル。HTTP接続をアップグレードして使用。','example'=>'チャットアプリやリアルタイム通知にWebSocketを使い、ポーリングなしでメッセージをプッシュ配信する。','difficulty'=>3,'quiz'=>['question'=>'WebSocketの特徴として正しいものはどれか？','explanation'=>'WebSocketは一度接続を確立するとサーバー・クライアント双方からいつでもデータを送れる全二重通信を実現する。','choices'=>[['body'=>'毎回HTTPリクエストを送る必要がある','is_correct'=>false],['body'=>'サーバー・クライアント間で双方向通信が可能','is_correct'=>true],['body'=>'UDPを使用する','is_correct'=>false],['body'=>'暗号化できない','is_correct'=>false]]]],
            ['name'=>'SNMP（Simple Network Management Protocol）','definition'=>'ネットワーク機器の監視・管理を行うためのプロトコル。ルーターやスイッチの状態取得に使われる。','example'=>'NMS（ネットワーク管理システム）がSNMPでスイッチのCPU使用率やポートのトラフィック量を収集する。','difficulty'=>4,'quiz'=>['question'=>'SNMPの主な用途はどれか？','explanation'=>'SNMPはネットワーク機器のMIB（管理情報ベース）を読み書きして、機器の状態監視や設定管理を行う。','choices'=>[['body'=>'ファイル転送','is_correct'=>false],['body'=>'ネットワーク機器の監視・管理','is_correct'=>true],['body'=>'メールの送受信','is_correct'=>false],['body'=>'DNS解決','is_correct'=>false]]]],
            ['name'=>'Wi-Fi（無線LAN）','definition'=>'IEEE 802.11規格に基づく無線ネットワーク技術。2.4GHz帯や5GHz帯の電波を使用してデータを送受信する。','example'=>'スマートフォンやノートPCがWi-Fiアクセスポイントに接続してインターネットを利用する。','difficulty'=>1,'quiz'=>['question'=>'Wi-Fi 6（IEEE 802.11ax）が対応する主な周波数帯はどれか？','explanation'=>'Wi-Fi 6は2.4GHz帯と5GHz帯の両方をサポートし、Wi-Fi 6Eでは6GHz帯にも対応する。','choices'=>[['body'=>'2.4GHz帯のみ','is_correct'=>false],['body'=>'2.4GHz帯と5GHz帯の両方','is_correct'=>true],['body'=>'5GHz帯のみ','is_correct'=>false],['body'=>'60GHz帯のみ','is_correct'=>false]]]],
        ]];
    }

    private function securityTerms(): array
    {
        return ['security' => [
            ['name'=>'CSRF（クロスサイトリクエストフォージェリ）','definition'=>'ユーザーが意図しないリクエストを悪意あるサイトから送信させる攻撃。ログイン中のセッションを悪用する。','example'=>'悪意あるサイトを閲覧したユーザーが、知らないうちに銀行振込リクエストを送信させられる。','difficulty'=>3,'quiz'=>['question'=>'CSRF対策として最も有効なものはどれか？','explanation'=>'CSRFトークン（ランダムな値をフォームに埋め込みサーバーで検証）により、外部サイトからの偽リクエストを防ぐ。','choices'=>[['body'=>'入力値をHTMLエスケープする','is_correct'=>false],['body'=>'CSRFトークンを使用する','is_correct'=>true],['body'=>'HTTPSを使用する','is_correct'=>false],['body'=>'パスワードを長くする','is_correct'=>false]]]],
            ['name'=>'ハッシュ関数','definition'=>'任意長の入力データを固定長のハッシュ値に変換する一方向関数。同じ入力からは常に同じ出力が得られる。','example'=>'パスワードをbcryptでハッシュ化してDBに保存し、ログイン時は入力値をハッシュ化して比較する。','difficulty'=>2,'quiz'=>['question'=>'ハッシュ関数の特性として正しいものはどれか？','explanation'=>'ハッシュ関数は一方向性を持ち、ハッシュ値から元のデータを復元することは計算上不可能。','choices'=>[['body'=>'ハッシュ値から元データを復元できる','is_correct'=>false],['body'=>'一方向性を持ち元データを復元できない','is_correct'=>true],['body'=>'入力が異なれば出力も必ず異なる','is_correct'=>false],['body'=>'鍵を使って変換する','is_correct'=>false]]]],
            ['name'=>'ブルートフォース攻撃','definition'=>'パスワードなどを総当たりで試す攻撃手法。計算資源の増大により短いパスワードは脆弱になっている。','example'=>'4桁数字のPINを0000〜9999まで全試行する。アカウントロックがない場合は自動化ツールで数秒で突破できる。','difficulty'=>2,'quiz'=>['question'=>'ブルートフォース攻撃の対策として最も効果的なものはどれか？','explanation'=>'アカウントロック（複数回失敗でアカウントを一時停止）により、自動化されたブルートフォース攻撃を防げる。','choices'=>[['body'=>'HTMLエスケープする','is_correct'=>false],['body'=>'ログイン失敗回数でアカウントをロックする','is_correct'=>true],['body'=>'HTTPSを使用する','is_correct'=>false],['body'=>'ファイアウォールを設置する','is_correct'=>false]]]],
            ['name'=>'DDoS攻撃','definition'=>'分散したホスト（ボットネット等）から標的サーバーに大量リクエストを送り、サービスを停止させる攻撃。','example'=>'数万台のボットを使ってECサイトに秒間100万リクエストを送りつけ、サーバーをダウンさせる。','difficulty'=>3,'quiz'=>['question'=>'DDoS攻撃とDoS攻撃の主な違いはどれか？','explanation'=>'DDoSは複数（Distributed）の攻撃元から行うため、送信元IPブロックによる防御が難しい。DoSは単一ホストから。','choices'=>[['body'=>'DDoSはHTTPを使わない','is_correct'=>false],['body'=>'DDoSは複数ホストから分散して攻撃する','is_correct'=>true],['body'=>'DDoSはデータを盗む攻撃','is_correct'=>false],['body'=>'DDoSはSQLを使う攻撃','is_correct'=>false]]]],
            ['name'=>'フィッシング','definition'=>'正規機関を装った偽メールやWebサイトで個人情報・認証情報を詐取するソーシャルエンジニアリング攻撃。','example'=>'銀行からのメールに見せかけ、偽ログインページのURLをクリックさせてIDとパスワードを盗む。','difficulty'=>1,'quiz'=>['question'=>'フィッシング攻撃の特徴として正しいものはどれか？','explanation'=>'フィッシングは正規組織になりすましたメール・Webサイトで認証情報等を詐取するソーシャルエンジニアリングの一種。','choices'=>[['body'=>'システムの脆弱性を直接攻撃する','is_correct'=>false],['body'=>'正規機関になりすまして情報を騙し取る','is_correct'=>true],['body'=>'大量リクエストでサービスを停止させる','is_correct'=>false],['body'=>'DBに不正なSQLを実行させる','is_correct'=>false]]]],
            ['name'=>'ソーシャルエンジニアリング','definition'=>'技術的手段ではなく人間の心理や行動を利用して機密情報を取得する攻撃手法。','example'=>'電話で情報システム部員になりすまし「パスワードを教えてください」と社員に依頼して情報を入手する。','difficulty'=>2,'quiz'=>['question'=>'ソーシャルエンジニアリング攻撃への対策として適切なものはどれか？','explanation'=>'ソーシャルエンジニアリングは人を騙す攻撃のため、セキュリティ教育や情報開示ルールの徹底が最も効果的。','choices'=>[['body'=>'ファイアウォールを強化する','is_correct'=>false],['body'=>'セキュリティ教育と情報開示ルールの徹底','is_correct'=>true],['body'=>'暗号化を強化する','is_correct'=>false],['body'=>'IDS/IPSを導入する','is_correct'=>false]]]],
            ['name'=>'ゼロデイ攻撃','definition'=>'ベンダーがまだ把握していない（または修正パッチ未公開の）脆弱性を悪用した攻撃。発見から対策まで時間がかかる。','example'=>'OSの未知のバッファオーバーフロー脆弱性を悪用したマルウェアがパッチ公開前に世界中で拡散する。','difficulty'=>4,'quiz'=>['question'=>'ゼロデイ攻撃の「ゼロデイ」が意味するものはどれか？','explanation'=>'パッチが公開されてから0日（まだ存在しない）の状態の脆弱性を突く攻撃であることからゼロデイと呼ばれる。','choices'=>[['body'=>'0時（深夜）に実行される攻撃','is_correct'=>false],['body'=>'修正パッチが公開される前の脆弱性を突く攻撃','is_correct'=>true],['body'=>'0円のツールで実行できる攻撃','is_correct'=>false],['body'=>'検知が0秒の攻撃','is_correct'=>false]]]],
            ['name'=>'マルウェア','definition'=>'悪意を持って作成されたソフトウェアの総称。ウイルス・ワーム・トロイの木馬・スパイウェアなどを含む。','example'=>'メール添付ファイルを開くとマルウェアが実行され、PCの情報が盗まれる。','difficulty'=>1,'quiz'=>['question'=>'マルウェアの説明として正しいものはどれか？','explanation'=>'マルウェアはウイルス・ワーム・ランサムウェア等を含む悪意あるソフトウェアの総称であり、ウイルスはその一種。','choices'=>[['body'=>'コンピュータウイルスの別名','is_correct'=>false],['body'=>'悪意あるソフトウェアの総称（ウイルスはその一種）','is_correct'=>true],['body'=>'スパムメールのこと','is_correct'=>false],['body'=>'フィッシングサイトのこと','is_correct'=>false]]]],
            ['name'=>'ランサムウェア','definition'=>'感染したPCのファイルを暗号化し、復号の代わりに身代金（Ransom）を要求するマルウェア。','example'=>'病院のシステムがランサムウェアに感染し電子カルテが使えなくなり、攻撃者からBitcoinでの支払いを要求された。','difficulty'=>2,'quiz'=>['question'=>'ランサムウェア感染時に最も有効な事前対策はどれか？','explanation'=>'オフラインまたは隔離されたバックアップを定期的に取ることで、暗号化されても復旧できる。','choices'=>[['body'=>'高性能なCPUを使う','is_correct'=>false],['body'=>'定期的にオフラインバックアップを取得する','is_correct'=>true],['body'=>'パスワードを長くする','is_correct'=>false],['body'=>'HTTPSを使用する','is_correct'=>false]]]],
            ['name'=>'JWT（JSON Web Token）','definition'=>'JSON形式のペイロードを電子署名したトークン。ヘッダー・ペイロード・署名の3部構成でBase64URLエンコードされる。','example'=>'ログイン後にJWTを発行しクライアントに渡し、以降のAPIリクエストでAuthorization: Bearerヘッダーに付与する。','difficulty'=>3,'quiz'=>['question'=>'JWTの構造として正しいものはどれか？','explanation'=>'JWTはヘッダー（アルゴリズム情報）.ペイロード（クレーム）.署名の3パートをドット区切りで並べたもの。','choices'=>[['body'=>'ユーザー名とパスワードのBase64エンコード','is_correct'=>false],['body'=>'ヘッダー・ペイロード・署名の3部構成','is_correct'=>true],['body'=>'AES暗号化されたセッション情報','is_correct'=>false],['body'=>'ランダムな256ビット文字列','is_correct'=>false]]]],
            ['name'=>'OAuth 2.0','definition'=>'サードパーティアプリがユーザーの代わりにリソースにアクセスするための認可フレームワーク。パスワードを渡さずにアクセス委譲できる。','example'=>'「Googleでログイン」ボタンを押すと、OAuthでGoogleがアクセストークンを発行し、アプリに返す。','difficulty'=>3,'quiz'=>['question'=>'OAuth 2.0が解決する主な課題はどれか？','explanation'=>'OAuth 2.0によりユーザーはサードパーティアプリにパスワードを渡すことなく、特定リソースへのアクセス権を委譲できる。','choices'=>[['body'=>'通信の暗号化','is_correct'=>false],['body'=>'パスワードを渡さずにアクセス権を委譲する','is_correct'=>true],['body'=>'SQLインジェクションの防止','is_correct'=>false],['body'=>'DDoS攻撃の防御','is_correct'=>false]]]],
            ['name'=>'ペネトレーションテスト','definition'=>'実際の攻撃手法を用いてシステムの脆弱性を発見する侵入テスト。事前に許可を得て行うホワイトハット的な活動。','example'=>'セキュリティ専門企業が企業のWebアプリにSQLインジェクションやXSSを試みて脆弱性を報告書にまとめる。','difficulty'=>4,'quiz'=>['question'=>'ペネトレーションテストの説明として正しいものはどれか？','explanation'=>'ペネトレーションテストは許可された環境で実際の攻撃手法を使い、脆弱性を発見する合法的なセキュリティ評価手法。','choices'=>[['body'=>'不正アクセスの一種','is_correct'=>false],['body'=>'許可を得た上でシステムに侵入を試みる脆弱性評価','is_correct'=>true],['body'=>'マルウェアの解析手法','is_correct'=>false],['body'=>'ネットワーク監視の手法','is_correct'=>false]]]],
            ['name'=>'デジタル署名','definition'=>'送信者が秘密鍵でデータのハッシュを暗号化したもの。受信者は公開鍵で検証し、改ざん検出と送信者認証を行う。','example'=>'電子契約書にデジタル署名を付与し、法的有効性を持つ証明として相手に送付する。','difficulty'=>4,'quiz'=>['question'=>'デジタル署名の目的として誤っているものはどれか？','explanation'=>'デジタル署名はデータの改ざん検出と送信者の認証を行うが、データの暗号化（秘密保持）は目的に含まれない。','choices'=>[['body'=>'改ざんの検出','is_correct'=>false],['body'=>'送信者の認証','is_correct'=>false],['body'=>'データの暗号化（秘密保持）','is_correct'=>true],['body'=>'否認防止','is_correct'=>false]]]],
            ['name'=>'PKI（公開鍵基盤）','definition'=>'公開鍵暗号方式を安全に運用するためのフレームワーク。CA（認証局）がデジタル証明書を発行して信頼を確立する。','example'=>'WebサーバーがCAから証明書を取得してHTTPSを有効化し、ブラウザが証明書を検証することで安全な通信が確立される。','difficulty'=>4,'quiz'=>['question'=>'PKIにおけるCA（認証局）の役割はどれか？','explanation'=>'CAはデジタル証明書を発行・管理する機関。証明書により公開鍵の正当性（所有者情報）を保証する。','choices'=>[['body'=>'パスワードを管理する','is_correct'=>false],['body'=>'デジタル証明書を発行して公開鍵の正当性を保証する','is_correct'=>true],['body'=>'暗号化アルゴリズムを開発する','is_correct'=>false],['body'=>'ネットワーク監視を行う','is_correct'=>false]]]],
            ['name'=>'WAF（Web Application Firewall）','definition'=>'WebアプリへのHTTP/HTTPSトラフィックを監視・フィルタリングし、SQLインジェクションやXSS等を防ぐセキュリティ装置。','example'=>'CloudflareのWAFがSQLインジェクション特有のパターンを検出し、悪意あるリクエストを自動ブロックする。','difficulty'=>3,'quiz'=>['question'=>'WAFが防御できる攻撃として最も適切なものはどれか？','explanation'=>'WAFはアプリケーション層（HTTP/HTTPS）で動作し、SQLインジェクション・XSSなどOWASP Top 10の攻撃を検出・防御する。','choices'=>[['body'=>'DDoS攻撃（大量パケット）','is_correct'=>false],['body'=>'SQLインジェクションやXSSなどのWebアプリ攻撃','is_correct'=>true],['body'=>'フィッシングメール','is_correct'=>false],['body'=>'ブルートフォース攻撃','is_correct'=>false]]]],
            ['name'=>'IDS（侵入検知システム）','definition'=>'ネットワークやシステムへの不正アクセスを検知して管理者に通知するシステム。検知のみで自動遮断は行わない。','example'=>'IDSが社内ネットワークへの異常なポートスキャンを検知し、セキュリティ担当者にアラートを送信する。','difficulty'=>3,'quiz'=>['question'=>'IDSとIPSの主な違いはどれか？','explanation'=>'IDSは検知・通知のみ行い、IPSは検知後に自動的に通信を遮断（インライン配置）する点が異なる。','choices'=>[['body'=>'IDSはハードウェア、IPSはソフトウェア','is_correct'=>false],['body'=>'IDSは検知・通知のみ、IPSは自動遮断も行う','is_correct'=>true],['body'=>'IDSはWebアプリ専用、IPSはネットワーク専用','is_correct'=>false],['body'=>'IDSはより高性能','is_correct'=>false]]]],
            ['name'=>'共通鍵暗号方式（AES）','definition'=>'暗号化と復号に同じ鍵を使う暗号方式。処理が高速で大量データの暗号化に適する。AESが現在の標準。','example'=>'ファイルを暗号化する際、同じ鍵（パスワード）で暗号化・復号する。HTTPSでも最終的に共通鍵暗号が使われる。','difficulty'=>3,'quiz'=>['question'=>'AES-256の「256」が示すものはどれか？','explanation'=>'AES-256は鍵長が256ビットであることを示す。128・192・256ビットの3種類があり、256ビットが最も安全。','choices'=>[['body'=>'ブロックサイズ（ビット）','is_correct'=>false],['body'=>'鍵長（ビット）','is_correct'=>true],['body'=>'ラウンド数','is_correct'=>false],['body'=>'処理速度（Mbps）','is_correct'=>false]]]],
            ['name'=>'脆弱性（セキュリティホール）','definition'=>'ソフトウェアやシステムに存在するセキュリティ上の欠陥。攻撃者に悪用されるとシステム侵害につながる。','example'=>'Webフレームワークのバージョンアップにより既知の脆弱性CVE-2024-XXXXが修正された。','difficulty'=>2,'quiz'=>['question'=>'脆弱性への対応として最も基本的なものはどれか？','explanation'=>'セキュリティパッチやソフトウェアのアップデートを適時適用することが最も基本的な脆弱性対策。','choices'=>[['body'=>'ファイアウォールを設置する','is_correct'=>false],['body'=>'セキュリティパッチを適時適用する','is_correct'=>true],['body'=>'パスワードを変更する','is_correct'=>false],['body'=>'監視カメラを設置する','is_correct'=>false]]]],
            ['name'=>'OWASP Top 10','definition'=>'Webアプリケーションのセキュリティにおける最も重大なリスクトップ10をOWASPが定期的に公開するリスト。','example'=>'A01:アクセス制御の不備、A02:暗号化の失敗、A03:インジェクションなどが含まれる。','difficulty'=>3,'quiz'=>['question'=>'OWASPが示すものはどれか？','explanation'=>'OWASPはWebセキュリティの非営利組織で、OWASP Top 10はWebアプリの重大リスクを開発者に啓発するためのリスト。','choices'=>[['body'=>'Webフレームワークのランキング','is_correct'=>false],['body'=>'Webアプリの重大セキュリティリスクトップ10','is_correct'=>true],['body'=>'暗号化アルゴリズムの比較リスト','is_correct'=>false],['body'=>'ネットワーク機器のベンチマーク','is_correct'=>false]]]],
            ['name'=>'最小権限の原則','definition'=>'ユーザー・プロセス・システムに対し、必要最低限の権限のみを付与するセキュリティ原則。侵害時の被害を最小化する。','example'=>'アプリのDBユーザーにはSELECT・INSERT・UPDATEのみ付与し、DROP・TRUNCATE権限は与えない。','difficulty'=>3,'quiz'=>['question'=>'最小権限の原則を適用する主な目的はどれか？','explanation'=>'最小権限により、アカウントやシステムが侵害された場合でも攻撃者が行える操作を最小化し被害を限定できる。','choices'=>[['body'=>'システムのパフォーマンスを向上させる','is_correct'=>false],['body'=>'侵害時の被害を最小化する','is_correct'=>true],['body'=>'ログイン速度を上げる','is_correct'=>false],['body'=>'パスワードを不要にする','is_correct'=>false]]]],
            ['name'=>'インシデントレスポンス','definition'=>'セキュリティインシデント（侵害・感染・漏洩等）発生時に行う対応プロセス。準備・検知・封じ込め・根絶・復旧・教訓の6フェーズ。','example'=>'ランサムウェア感染を検知後、感染端末をネットワークから隔離（封じ込め）し、被害範囲を調査して復旧する。','difficulty'=>4,'quiz'=>['question'=>'インシデントレスポンスにおける「封じ込め」の目的はどれか？','explanation'=>'封じ込めは被害の拡大を防ぐため、感染端末のネットワーク切断や該当サービスの停止など即時措置を行うフェーズ。','choices'=>[['body'=>'根本原因を特定する','is_correct'=>false],['body'=>'被害の拡大を防止する','is_correct'=>true],['body'=>'システムを復旧する','is_correct'=>false],['body'=>'再発防止策を策定する','is_correct'=>false]]]],
            ['name'=>'サンドボックス','definition'=>'外部環境から隔離された安全な実行環境。不審なプログラムの動作を安全に分析したり、未知マルウェアを検知するために使う。','example'=>'セキュリティソフトが受信メールの添付ファイルをサンドボックスで自動実行し、マルウェアか判定する。','difficulty'=>3,'quiz'=>['question'=>'セキュリティにおけるサンドボックスの主な用途はどれか？','explanation'=>'サンドボックスは隔離環境でプログラムを実行し、実際のシステムに影響を与えずにマルウェアかどうかを分析できる。','choices'=>[['body'=>'パスワードを安全に保管する','is_correct'=>false],['body'=>'隔離環境で不審なプログラムを安全に実行・分析する','is_correct'=>true],['body'=>'通信を暗号化する','is_correct'=>false],['body'=>'ファイアウォールのルールを管理する','is_correct'=>false]]]],
            ['name'=>'SSL証明書（TLS証明書）','definition'=>'Webサイトの身元を証明し、HTTPS通信を可能にするデジタル証明書。CAが発行し、有効期限がある。','example'=>'ブラウザのアドレスバーの鍵マークをクリックすると、そのサイトのSSL証明書の発行者や有効期限を確認できる。','difficulty'=>2,'quiz'=>['question'=>'SSL証明書の有効期限が切れたWebサイトにアクセスするとどうなるか？','explanation'=>'証明書の有効期限切れはブラウザが警告を表示する。証明書の有効性を確認できないためHTTPS通信の信頼性が失われる。','choices'=>[['body'=>'自動更新される','is_correct'=>false],['body'=>'ブラウザが警告を表示する','is_correct'=>true],['body'=>'HTTP通信に自動切替される','is_correct'=>false],['body'=>'接続が完全に不可能になる','is_correct'=>false]]]],
            ['name'=>'SAML（Security Assertion Markup Language）','definition'=>'ID プロバイダーとサービスプロバイダー間でユーザー認証情報をXMLで交換するシングルサインオン（SSO）の標準プロトコル。','example'=>'会社のAD（Active Directory）をIdPとしてSAMLを使い、G SuiteやSalesforceにSSOでアクセスする。','difficulty'=>4,'quiz'=>['question'=>'SAMLの主な用途はどれか？','explanation'=>'SAMLはエンタープライズ環境でのシングルサインオン（SSO）に広く使われ、IDプロバイダーとサービス間で認証アサーションを交換する。','choices'=>[['body'=>'APIの認可管理','is_correct'=>false],['body'=>'エンタープライズSSOのための認証情報交換','is_correct'=>true],['body'=>'パスワードのハッシュ化','is_correct'=>false],['body'=>'ネットワーク暗号化','is_correct'=>false]]]],
            ['name'=>'CSIRT（Computer Security Incident Response Team）','definition'=>'セキュリティインシデントへの対応を専門に行う組織またはチーム。社内CSIRTと国家CSIRTがある。','example'=>'企業がCSIRTを設置し、マルウェア感染やサイバー攻撃発生時に迅速な対応・復旧・情報共有を行う。','difficulty'=>3,'quiz'=>['question'=>'CSIRTの主な役割はどれか？','explanation'=>'CSIRTはインシデントの検知・トリアージ・対応・復旧を行い、再発防止や関係機関との情報共有も担う。','choices'=>[['body'=>'新機能の開発','is_correct'=>false],['body'=>'セキュリティインシデントへの対応と復旧','is_correct'=>true],['body'=>'ネットワークの設計','is_correct'=>false],['body'=>'ユーザー管理','is_correct'=>false]]]],
        ]];
    }

    private function databaseTerms(): array
    {
        return ['database' => [
            ['name'=>'FOREIGN KEY（外部キー）','definition'=>'他テーブルのPRIMARY KEYを参照する制約。参照整合性を保ち、孤立レコードの発生を防ぐ。','example'=>'ordersテーブルのuser_id列にFOREIGN KEY制約を設け、usersテーブルに存在しないuser_idを登録不可にする。','difficulty'=>2,'quiz'=>['question'=>'FOREIGN KEY制約の主な目的はどれか？','explanation'=>'外部キー制約により参照先に存在しないデータの挿入や、参照中データの削除を防ぎ参照整合性を維持する。','choices'=>[['body'=>'検索速度を向上させる','is_correct'=>false],['body'=>'参照整合性を維持する','is_correct'=>true],['body'=>'値を一意にする','is_correct'=>false],['body'=>'NULLを禁止する','is_correct'=>false]]]],
            ['name'=>'JOIN（テーブル結合）','definition'=>'複数テーブルの行を関連する列で結合して1つの結果セットを作る操作。INNER・LEFT・RIGHT・FULL JOINがある。','example'=>'SELECT u.name, o.amount FROM users u INNER JOIN orders o ON u.id = o.user_id;','difficulty'=>2,'quiz'=>['question'=>'INNER JOINの特徴として正しいものはどれか？','explanation'=>'INNER JOINは両方のテーブルで結合条件を満たす行のみを返す。どちらかにしか存在しない行は含まれない。','choices'=>[['body'=>'左テーブルの全行を返す','is_correct'=>false],['body'=>'両テーブルで結合条件を満たす行のみ返す','is_correct'=>true],['body'=>'両テーブルの全行を返す','is_correct'=>false],['body'=>'右テーブルの全行を返す','is_correct'=>false]]]],
            ['name'=>'VIEW（ビュー）','definition'=>'SELECT文を名前付きで保存した仮想テーブル。実データは持たないが通常テーブルのように参照できる。','example'=>'頻繁に使う複雑な結合クエリをVIEWとして定義し、以降は「SELECT * FROM v_active_users」で取得する。','difficulty'=>2,'quiz'=>['question'=>'VIEWに関する説明として正しいものはどれか？','explanation'=>'VIEWは実データを持たず、参照時にベースクエリが実行される仮想テーブル。クエリの再利用やアクセス制御に利用される。','choices'=>[['body'=>'独自のデータを物理的に保持する','is_correct'=>false],['body'=>'実データを持たない仮想テーブル','is_correct'=>true],['body'=>'インデックスを使えない','is_correct'=>false],['body'=>'更新操作ができない','is_correct'=>false]]]],
            ['name'=>'ストアドプロシージャ','definition'=>'DBサーバー上に保存・実行できるプログラムの塊。複数SQL操作をひとまとめにしてアプリから呼び出せる。','example'=>'発注処理（在庫減算→発注レコード挿入→通知）をストアドプロシージャにまとめ、CALL place_order(user_id, item_id)で実行する。','difficulty'=>3,'quiz'=>['question'=>'ストアドプロシージャのメリットとして正しいものはどれか？','explanation'=>'ストアドプロシージャはDB側で事前コンパイルされ、ネットワーク往復を減らし複数SQL操作をまとめて高速実行できる。','choices'=>[['body'=>'テーブルを物理的に結合できる','is_correct'=>false],['body'=>'複数のSQL処理をまとめてDB側で実行できる','is_correct'=>true],['body'=>'データを暗号化できる','is_correct'=>false],['body'=>'自動的にバックアップを取る','is_correct'=>false]]]],
            ['name'=>'トリガー','definition'=>'テーブルへのINSERT・UPDATE・DELETE操作時に自動実行されるプログラム。データ整合性の維持や監査ログに使う。','example'=>'ordersテーブルにINSERTされると自動でAFTER INSERTトリガーが起動し、inventoryの在庫数を自動更新する。','difficulty'=>3,'quiz'=>['question'=>'トリガーが自動実行されるのはどのような時か？','explanation'=>'トリガーはテーブルに対するDML操作（INSERT・UPDATE・DELETE）の前後に自動的に実行されるDB側のプログラム。','choices'=>[['body'=>'定時スケジュールで実行される','is_correct'=>false],['body'=>'テーブルへのDML操作（INSERT/UPDATE/DELETE）時','is_correct'=>true],['body'=>'クライアント接続時','is_correct'=>false],['body'=>'バックアップ実行時','is_correct'=>false]]]],
            ['name'=>'デッドロック','definition'=>'2つ以上のトランザクションがお互いのロック解放を待って永遠に待機し合う状態。DBMSが検知してどちらかをロールバックする。','example'=>'Txn1がAをロックしBを待ち、Txn2がBをロックしAを待つ状態がデッドロック。DBが一方を強制ロールバックして解消する。','difficulty'=>4,'quiz'=>['question'=>'デッドロック発生時にDBMSが取る対応として正しいものはどれか？','explanation'=>'DBMSはデッドロックを検知すると関係するトランザクションのうち1つを強制的にロールバックし、ロックを解放する。','choices'=>[['body'=>'全トランザクションをコミットする','is_correct'=>false],['body'=>'いずれかのトランザクションを強制ロールバックする','is_correct'=>true],['body'=>'データベースを再起動する','is_correct'=>false],['body'=>'ロックを全て解放する','is_correct'=>false]]]],
            ['name'=>'MVCC（多版型同時実行制御）','definition'=>'読み取り操作のたびにデータのスナップショットを提供し、読み書きが互いにブロックしないようにする同時実行制御方式。','example'=>'PostgreSQLとMySQLのInnoDBがMVCCを採用。長時間トランザクションでも読み取りがロックされない。','difficulty'=>5,'quiz'=>['question'=>'MVCCの主なメリットはどれか？','explanation'=>'MVCCにより読み取りが書き込みをブロックしないため、読み書きが高い同時実行性で処理できる。','choices'=>[['body'=>'ディスク使用量を削減する','is_correct'=>false],['body'=>'読み取りと書き込みが互いにブロックしない','is_correct'=>true],['body'=>'データを暗号化する','is_correct'=>false],['body'=>'自動的にインデックスを最適化する','is_correct'=>false]]]],
            ['name'=>'レプリケーション','definition'=>'DBのデータを複数サーバーにリアルタイムで複製する技術。読み取り負荷分散・高可用性・バックアップ目的で使われる。','example'=>'プライマリDBへの書き込みが自動的に2台のレプリカDBに同期され、読み取りクエリはレプリカに振り分ける。','difficulty'=>3,'quiz'=>['question'=>'DBレプリケーションの主な目的はどれか？','explanation'=>'レプリケーションはデータを複数サーバーに複製することで、読み取り負荷分散・フェイルオーバー対応・データ保護を実現する。','choices'=>[['body'=>'クエリを高速化する専用機能','is_correct'=>false],['body'=>'高可用性と読み取り負荷分散のためのデータ複製','is_correct'=>true],['body'=>'不要データを自動削除する','is_correct'=>false],['body'=>'テーブルを自動正規化する','is_correct'=>false]]]],
            ['name'=>'シャーディング','definition'=>'大量データを複数DBに水平分割して格納・管理する手法。1台のDBに収まらないスケールアウトに使われる。','example'=>'ユーザーIDのmod 4でDBを4台に分散し、user_id=101はDB1、user_id=102はDB2という具合に分割する。','difficulty'=>4,'quiz'=>['question'=>'シャーディングの主な目的はどれか？','explanation'=>'シャーディングはデータを複数DBに水平分割することで、1台に収まらない大量データを分散処理・管理するスケーリング手法。','choices'=>[['body'=>'データを暗号化する','is_correct'=>false],['body'=>'大量データを複数DBに水平分割してスケールアウト','is_correct'=>true],['body'=>'バックアップを自動化する','is_correct'=>false],['body'=>'クエリ文を最適化する','is_correct'=>false]]]],
            ['name'=>'NoSQL','definition'=>'リレーショナルDBとは異なるデータモデルを持つDB群の総称。ドキュメント型・KV型・グラフ型・列指向型などがある。','example'=>'MongoDBはドキュメント型NoSQL。JSONに似た柔軟なスキーマでデータを格納し、スケールアウトに強い。','difficulty'=>3,'quiz'=>['question'=>'NoSQLデータベースの特徴として正しいものはどれか？','explanation'=>'多くのNoSQLはスキーマが固定されていない（スキーマレス）ため、データ構造を柔軟に変更できる。','choices'=>[['body'=>'必ずSQLで操作する','is_correct'=>false],['body'=>'スキーマレスで柔軟なデータ構造を持てる','is_correct'=>true],['body'=>'ACID特性を必ず保証する','is_correct'=>false],['body'=>'テーブルと行で構成される','is_correct'=>false]]]],
            ['name'=>'Redis','definition'=>'インメモリのKVS（Key-Value Store）型NoSQL。高速なキャッシュ・セッション管理・Pub/Subメッセージングなどに使われる。','example'=>'LaravelでRedisをセッションドライバーとして使い、セッションデータをメモリ上で高速に読み書きする。','difficulty'=>3,'quiz'=>['question'=>'Redisの特徴として正しいものはどれか？','explanation'=>'RedisはデータをRAM上に保持するインメモリDBのため、ディスクベースのDBと比べて読み書き速度が非常に高速。','choices'=>[['body'=>'データをディスクに保存するRDB','is_correct'=>false],['body'=>'データをメモリ上に保持し高速処理するKVS','is_correct'=>true],['body'=>'グラフ構造専用のDB','is_correct'=>false],['body'=>'XML形式のみ格納できるDB','is_correct'=>false]]]],
            ['name'=>'ウィンドウ関数（Window Function）','definition'=>'現在行に関連する行のグループ（ウィンドウ）に対して集計を行う関数。GROUP BYと異なり行を集約せずに結果を返す。','example'=>'RANK() OVER (PARTITION BY dept ORDER BY salary DESC) で部署ごとの給与ランキングを付けられる。','difficulty'=>4,'quiz'=>['question'=>'ウィンドウ関数の特徴として正しいものはどれか？','explanation'=>'ウィンドウ関数はGROUP BYと違い行を集約せず、各行の結果と集計値を同時に取得できる。','choices'=>[['body'=>'GROUP BYと同様に行をまとめる','is_correct'=>false],['body'=>'行を集約せずに集計値を各行に付与できる','is_correct'=>true],['body'=>'JOINの代替として使う','is_correct'=>false],['body'=>'テーブルの行を削除する','is_correct'=>false]]]],
            ['name'=>'EXPLAIN（実行計画）','definition'=>'クエリがどのようにデータを取得するかをDBが示す実行計画。インデックスの使用有無・スキャン方式を確認してチューニングに使う。','example'=>'EXPLAIN SELECT * FROM users WHERE email = \'test@example.com\'; でインデックスが使われているか確認する。','difficulty'=>3,'quiz'=>['question'=>'EXPLAINコマンドの主な用途はどれか？','explanation'=>'EXPLAINはSQLの実行計画を表示し、フルテーブルスキャンやインデックス利用の有無を確認してパフォーマンスチューニングに活用する。','choices'=>[['body'=>'SQLを自動最適化する','is_correct'=>false],['body'=>'SQLの実行計画を表示してチューニングに活用する','is_correct'=>true],['body'=>'インデックスを自動作成する','is_correct'=>false],['body'=>'クエリを実行してデータを返す','is_correct'=>false]]]],
            ['name'=>'ORM（Object-Relational Mapping）','definition'=>'オブジェクト指向言語とRDBのデータ構造の差異を吸収し、SQLを書かずにオブジェクトでDB操作できるフレームワーク。','example'=>'LaravelのEloquentでUser::find(1)とするだけで、SELECT * FROM users WHERE id=1 が実行される。','difficulty'=>2,'quiz'=>['question'=>'ORMの主なメリットはどれか？','explanation'=>'ORMによりSQL文を直接書かずにオブジェクト操作でDBアクセスでき、コードの可読性が向上しRDBMSの差異も吸収できる。','choices'=>[['body'=>'データベースへのアクセス速度を向上させる','is_correct'=>false],['body'=>'SQLを書かずにオブジェクトでDB操作できる','is_correct'=>true],['body'=>'データを自動的に暗号化する','is_correct'=>false],['body'=>'テーブル設計を自動化する','is_correct'=>false]]]],
            ['name'=>'マイグレーション（DB）','definition'=>'データベーススキーマの変更履歴をコードで管理する仕組み。バージョン管理によりチーム間でスキーマを同期できる。','example'=>'LaravelでCreateUsersTableマイグレーションを実行するとusersテーブルが作成され、rollbackで元に戻せる。','difficulty'=>2,'quiz'=>['question'=>'DBマイグレーションの主な目的はどれか？','explanation'=>'マイグレーションはスキーマ変更をコードで管理することで、チーム全員が同じスキーマを再現でき、バージョン管理・ロールバックが可能になる。','choices'=>[['body'=>'データを別DBに移行する','is_correct'=>false],['body'=>'スキーマ変更をコードで管理し再現・ロールバックを可能にする','is_correct'=>true],['body'=>'データをCSVに出力する','is_correct'=>false],['body'=>'クエリを高速化する','is_correct'=>false]]]],
            ['name'=>'データウェアハウス（DWH）','definition'=>'BI・分析目的に特化した大規模データ格納システム。ETLでデータを取り込み、OLAP分析に最適化された構造で格納する。','example'=>'BigQueryやRedshiftに各システムのデータを集約し、経営ダッシュボードの集計クエリを高速実行する。','difficulty'=>4,'quiz'=>['question'=>'データウェアハウスとOLTPデータベースの主な違いはどれか？','explanation'=>'DWHは大量データへの複雑な分析クエリ（OLAP）に最適化。OLTPは個々のトランザクション処理（読み書き）に最適化。','choices'=>[['body'=>'DWHはリアルタイム更新に特化している','is_correct'=>false],['body'=>'DWHは分析クエリ（OLAP）に最適化された大規模ストレージ','is_correct'=>true],['body'=>'DWHはNoSQLの一種','is_correct'=>false],['body'=>'DWHはキャッシュ専用のDB','is_correct'=>false]]]],
            ['name'=>'WAL（Write-Ahead Logging）','definition'=>'データの変更をデータファイルに書く前にまずログ（WAL）に記録する手法。クラッシュリカバリとデータ整合性に不可欠。','example'=>'PostgreSQLはWALを利用し、クラッシュ後もWALログを再生することでデータを復旧する。','difficulty'=>5,'quiz'=>['question'=>'WALの主な目的はどれか？','explanation'=>'WALはデータ変更前にログを先行書き込みすることで、クラッシュが発生しても未コミットデータを正しくロールバック/再適用できる。','choices'=>[['body'=>'クエリを高速化する','is_correct'=>false],['body'=>'クラッシュ時のデータ整合性とリカバリを保証する','is_correct'=>true],['body'=>'データを圧縮する','is_correct'=>false],['body'=>'バックアップを自動化する','is_correct'=>false]]]],
            ['name'=>'集計関数','definition'=>'複数行のデータに対して計算を行いひとつの結果を返す関数。COUNT・SUM・AVG・MAX・MINなどがある。','example'=>'SELECT COUNT(*), AVG(price) FROM products WHERE category_id = 1; でカテゴリ別の件数と平均価格を取得。','difficulty'=>1,'quiz'=>['question'=>'集計関数AVG()の役割はどれか？','explanation'=>'AVGはAverage（平均）の略で、指定列のNULLを除いた値の平均を計算して返す集計関数。','choices'=>[['body'=>'最大値を返す','is_correct'=>false],['body'=>'指定列の平均値を返す','is_correct'=>true],['body'=>'行数を返す','is_correct'=>false],['body'=>'合計値を返す','is_correct'=>false]]]],
            ['name'=>'サブクエリ','definition'=>'別のSQL文の中に入れ子にして書くSELECT文。WHERE句・FROM句・SELECT句など様々な場所で使える。','example'=>'SELECT * FROM users WHERE id IN (SELECT user_id FROM orders WHERE amount > 10000); で高額注文ユーザーを取得。','difficulty'=>3,'quiz'=>['question'=>'相関サブクエリの特徴として正しいものはどれか？','explanation'=>'相関サブクエリは外側クエリの各行に対してサブクエリが実行されるため、外側クエリの列を参照できる。','choices'=>[['body'=>'一度だけ実行される','is_correct'=>false],['body'=>'外側クエリの各行に対して実行され外側の列を参照できる','is_correct'=>true],['body'=>'常にINNER JOINより遅い','is_correct'=>false],['body'=>'FROM句にしか書けない','is_correct'=>false]]]],
            ['name'=>'パーティショニング','definition'=>'大きなテーブルを論理的または物理的に分割してパフォーマンスや管理性を向上させる技術。レンジ・リスト・ハッシュ等の方式がある。','example'=>'売上データをパーティショニングして2024年分は同一パーティション内に収め、古いデータの削除が高速になる。','difficulty'=>4,'quiz'=>['question'=>'テーブルパーティショニングの主なメリットはどれか？','explanation'=>'パーティショニングにより特定パーティションのみをスキャンすることで、大テーブルでのクエリ性能向上とデータ管理が容易になる。','choices'=>[['body'=>'テーブルを複数DBに自動分散する','is_correct'=>false],['body'=>'特定範囲のスキャンを高速化しデータ管理を容易にする','is_correct'=>true],['body'=>'テーブルを結合する','is_correct'=>false],['body'=>'データを暗号化する','is_correct'=>false]]]],
            ['name'=>'コネクションプール','definition'=>'DB接続を事前に確立してプールしておき、リクエストのたびに使い回す仕組み。接続確立のオーバーヘッドを削減する。','example'=>'LaravelのEloquentがコネクションプールを使い、毎回DB接続確立をせず再利用してレスポンスを高速化する。','difficulty'=>3,'quiz'=>['question'=>'コネクションプールを使う主な目的はどれか？','explanation'=>'DB接続の確立にはコストがかかるため、プールで接続を再利用することでオーバーヘッドを減らしスループットを上げる。','choices'=>[['body'=>'データを自動バックアップする','is_correct'=>false],['body'=>'DB接続の再利用でオーバーヘッドを削減する','is_correct'=>true],['body'=>'クエリを最適化する','is_correct'=>false],['body'=>'インデックスを自動生成する','is_correct'=>false]]]],
            ['name'=>'UNIQUE制約','definition'=>'列の値がテーブル内で一意であることを保証する制約。NULLは複数含められる場合もある（DBMSにより異なる）。','example'=>'usersテーブルのemail列にUNIQUE制約を付けることで、同じメールアドレスの重複登録を防ぐ。','difficulty'=>1,'quiz'=>['question'=>'UNIQUE制約が保証することはどれか？','explanation'=>'UNIQUE制約はその列（または列の組み合わせ）に同一の値が2行以上存在しないことを保証する。','choices'=>[['body'=>'値がNULLにならない','is_correct'=>false],['body'=>'列の値がテーブル内で一意である','is_correct'=>true],['body'=>'外部テーブルの行が存在する','is_correct'=>false],['body'=>'値が自動採番される','is_correct'=>false]]]],
            ['name'=>'GROUP BY','definition'=>'指定した列の値でレコードをグループ化し、集計関数と組み合わせて各グループの集計値を求める句。','example'=>'SELECT category_id, COUNT(*) FROM products GROUP BY category_id; でカテゴリ別の商品数を集計する。','difficulty'=>2,'quiz'=>['question'=>'GROUP BYと組み合わせて使うのはどれか？','explanation'=>'GROUP BYで行をグループ化した後、COUNT・SUM・AVGなどの集計関数で各グループの値を集計する。','choices'=>[['body'=>'WHERE句のみ','is_correct'=>false],['body'=>'COUNT・SUMなどの集計関数','is_correct'=>true],['body'=>'JOIN句のみ','is_correct'=>false],['body'=>'ORDER BY句のみ','is_correct'=>false]]]],
            ['name'=>'ETL（Extract Transform Load）','definition'=>'異なるシステムからデータを抽出（E）・変換（T）・ロード（L）してデータウェアハウスに投入するプロセス。','example'=>'夜間バッチでOLTPのMySQLからデータを抽出→日付フォーマット統一・欠損値処理→BigQueryへロードするETLパイプライン。','difficulty'=>4,'quiz'=>['question'=>'ETLのTが示す処理はどれか？','explanation'=>'TransformはETLの中間工程で、抽出したデータを目的のフォーマットや品質に変換する処理。','choices'=>[['body'=>'データを転送する（Transfer）','is_correct'=>false],['body'=>'データを変換する（Transform）','is_correct'=>true],['body'=>'データをテスト（Test）する','is_correct'=>false],['body'=>'データを削除する（Truncate）','is_correct'=>false]]]],
        ]];
    }

    private function algorithmTerms(): array
    {
        return ['algorithm' => [
            ['name'=>'キュー（Queue）','definition'=>'FIFO（先入れ先出し）で動作するデータ構造。先に追加した要素が先に取り出される。BFSや印刷スプールに使われる。','example'=>'タスクキューに仕事を積み、ワーカーが先着順に処理するシステム。','difficulty'=>1,'quiz'=>['question'=>'キューのデータアクセス方式はどれか？','explanation'=>'キューはFIFO（First In First Out：先入れ先出し）方式。スタックはLIFO（後入れ先出し）と対比して覚える。','choices'=>[['body'=>'LIFO（後入れ先出し）','is_correct'=>false],['body'=>'FIFO（先入れ先出し）','is_correct'=>true],['body'=>'ランダムアクセス','is_correct'=>false],['body'=>'優先度順','is_correct'=>false]]]],
            ['name'=>'スタック（Stack）','definition'=>'LIFO（後入れ先出し）で動作するデータ構造。最後に積んだ要素が最初に取り出される。関数呼び出しの管理に利用される。','example'=>'Webブラウザの「戻る」機能は、訪問ページをスタックに積んで管理する。','difficulty'=>1,'quiz'=>['question'=>'スタックのアクセス方式として正しいものはどれか？','explanation'=>'スタックはLIFO（Last In First Out：後入れ先出し）方式。push（積む）とpop（取り出す）操作がある。','choices'=>[['body'=>'FIFO（先入れ先出し）','is_correct'=>false],['body'=>'LIFO（後入れ先出し）','is_correct'=>true],['body'=>'ランダムアクセス','is_correct'=>false],['body'=>'二分探索','is_correct'=>false]]]],
            ['name'=>'二分木（Binary Tree）','definition'=>'各ノードが最大2つの子ノード（左・右）を持つ木構造のデータ構造。二分探索木・ヒープ・構文木などに使われる。','example'=>'数式「(1+2)*3」を二分木で表すと、ルートが「*」、左が「+」（子に1と2）、右が「3」となる。','difficulty'=>3,'quiz'=>['question'=>'二分探索木（BST）の特性として正しいものはどれか？','explanation'=>'BSTでは各ノードについて「左の子孫の値<自分の値<右の子孫の値」が成り立つ。これにより2分探索と同様のO(log n)探索が可能。','choices'=>[['body'=>'全ノードの値が同じ','is_correct'=>false],['body'=>'左の子孫<自分<右の子孫の順序が成り立つ','is_correct'=>true],['body'=>'必ず完全二分木になる','is_correct'=>false],['body'=>'子ノードは1つ以下','is_correct'=>false]]]],
            ['name'=>'ヒープ（Heap）','definition'=>'親ノードの値が常に子ノード以上（最大ヒープ）または以下（最小ヒープ）の完全二分木。優先度キューの実装に使われる。','example'=>'最小ヒープを使った優先度キューでダイクストラ法の「最短距離のノードを取り出す」操作をO(log n)で実現する。','difficulty'=>4,'quiz'=>['question'=>'最小ヒープにおける根（ルート）の値はどれか？','explanation'=>'最小ヒープでは親が常に子以下の値を持つため、ルートには常にヒープ全体の最小値が位置する。','choices'=>[['body'=>'ヒープの中央値','is_correct'=>false],['body'=>'ヒープの最小値','is_correct'=>true],['body'=>'ヒープの最大値','is_correct'=>false],['body'=>'最後に挿入した値','is_correct'=>false]]]],
            ['name'=>'ハッシュテーブル','definition'=>'キーをハッシュ関数でインデックスに変換し、配列に格納するデータ構造。平均O(1)で挿入・検索・削除が可能。','example'=>'Pythonの辞書型（dict）はハッシュテーブルで実装され、d[\'key\']でO(1)アクセスができる。','difficulty'=>3,'quiz'=>['question'=>'ハッシュテーブルの平均的な検索の時間計算量はどれか？','explanation'=>'ハッシュテーブルはキーのハッシュ値でインデックスを直接計算するため、平均O(1)の定数時間でアクセスできる。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'O(1)','is_correct'=>true],['body'=>'O(log n)','is_correct'=>false],['body'=>'O(n²)','is_correct'=>false]]]],
            ['name'=>'深さ優先探索（DFS）','definition'=>'グラフ・木をできる限り深く進んでからバックトラックする探索アルゴリズム。スタックまたは再帰で実装する。','example'=>'迷路の経路探索でDFSを使うと、1つの道を行き止まりまで進んでから別の分岐を試す。','difficulty'=>3,'quiz'=>['question'=>'DFSの実装で使われるデータ構造はどれか？','explanation'=>'DFSは再帰呼び出し（暗黙のコールスタック）またはスタック（明示的）を使って実装する。','choices'=>[['body'=>'キュー','is_correct'=>false],['body'=>'スタック（または再帰）','is_correct'=>true],['body'=>'ヒープ','is_correct'=>false],['body'=>'ハッシュテーブル','is_correct'=>false]]]],
            ['name'=>'幅優先探索（BFS）','definition'=>'グラフ・木を現在ノードから近い（隣接）ノードから順に探索するアルゴリズム。キューで実装し最短経路探索に使われる。','example'=>'SNSで友人の友人を「つながり距離1→2→3」の順に探索するのはBFSの応用。','difficulty'=>3,'quiz'=>['question'=>'BFSが最短経路探索に適している理由はどれか？','explanation'=>'BFSは各エッジのコストが均一なグラフでスタートから近い順に探索するため、最初に目的地に到達した時がすなわち最短経路。','choices'=>[['body'=>'メモリ使用量が少ない','is_correct'=>false],['body'=>'近い順に探索するため最初の到達が最短経路','is_correct'=>true],['body'=>'再帰で実装できる','is_correct'=>false],['body'=>'スタックを使うから','is_correct'=>false]]]],
            ['name'=>'ダイクストラ法','definition'=>'重み付きグラフの単一始点最短経路を求めるアルゴリズム。優先度キュー（最小ヒープ）を使いO((V+E)log V)で動作する。','example'=>'カーナビがダイクストラ法を使い出発地から目的地まで最短時間（重み付き）ルートを計算する。','difficulty'=>4,'quiz'=>['question'=>'ダイクストラ法の前提条件として正しいものはどれか？','explanation'=>'ダイクストラ法はエッジの重みが負になると正しく動作しない。負の重みがある場合はベルマン-フォード法を使う。','choices'=>[['body'=>'グラフが有向である','is_correct'=>false],['body'=>'エッジの重みが非負である','is_correct'=>true],['body'=>'グラフが木構造である','is_correct'=>false],['body'=>'ノード数が偶数である','is_correct'=>false]]]],
            ['name'=>'マージソート','definition'=>'配列を半分に分割し再帰的にソートしてからマージする分割統治型ソートアルゴリズム。時間計算量は常にO(n log n)。','example'=>'n=8の配列をn=4→2→1に分割してソート済みにし、逆順にマージして全体をソートする。','difficulty'=>3,'quiz'=>['question'=>'マージソートの時間計算量はどれか？','explanation'=>'マージソートは最良・平均・最悪のいずれの場合もO(n log n)の時間計算量を保証する安定ソート。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'O(n log n)','is_correct'=>true],['body'=>'O(n²)','is_correct'=>false],['body'=>'O(log n)','is_correct'=>false]]]],
            ['name'=>'クイックソート','definition'=>'ピボットを選んで左右に分割する分割統治型ソート。平均O(n log n)だが最悪O(n²)。実用上は最速クラス。','example'=>'Pythonのlist.sort()やCのqsort()の内部でクイックソートの変形（Timsortなど）が使われる。','difficulty'=>3,'quiz'=>['question'=>'クイックソートの最悪時間計算量はどれか？','explanation'=>'クイックソートは既にソート済みの配列などで毎回最小/最大値をピボットに選ぶと、分割が偏りO(n²)になる。','choices'=>[['body'=>'O(n)','is_correct'=>false],['body'=>'O(n log n)','is_correct'=>false],['body'=>'O(n²)','is_correct'=>true],['body'=>'O(log n)','is_correct'=>false]]]],
            ['name'=>'動的計画法（DP）','definition'=>'問題を部分問題に分割し、その解をメモしながら大きな問題を解くアルゴリズム設計技法。重複計算を排除して効率化する。','example'=>'フィボナッチ数列をDPで解くと各計算を1度のみ行いO(n)で完了する（再帰だとO(2^n)）。','difficulty'=>4,'quiz'=>['question'=>'動的計画法が有効な問題の条件はどれか？','explanation'=>'DPは「最適部分構造（部分問題の最適解が全体の最適解を構成）」と「重複する部分問題」の2条件が成り立つ問題に適用できる。','choices'=>[['body'=>'グラフが有向非巡回グラフ（DAG）のみ','is_correct'=>false],['body'=>'重複する部分問題と最適部分構造を持つ問題','is_correct'=>true],['body'=>'入力データがソート済みの問題のみ','is_correct'=>false],['body'=>'問題サイズが小さい場合のみ','is_correct'=>false]]]],
            ['name'=>'貪欲法（Greedy Algorithm）','definition'=>'各ステップで局所的に最適な選択をすることで全体の最適解を求めるアルゴリズム技法。','example'=>'コイン問題（500→100→50→10円の順）や最小全域木のクラスカル法に貪欲法が使われる。','difficulty'=>3,'quiz'=>['question'=>'貪欲法が常に最適解を得られない問題の例はどれか？','explanation'=>'貪欲法は局所最適を積み重ねるが、ナップサック問題（0-1型）では局所最適が全体最適を保証しないためDPが必要。','choices'=>[['body'=>'活動選択問題','is_correct'=>false],['body'=>'0-1ナップサック問題','is_correct'=>true],['body'=>'クラスカル法の最小全域木','is_correct'=>false],['body'=>'ダイクストラ法の最短経路','is_correct'=>false]]]],
            ['name'=>'時間計算量（Big-O記法）','definition'=>'アルゴリズムの入力サイズnに対する処理時間の増加傾向を表す記法。O(1)・O(log n)・O(n)・O(n log n)・O(n²)など。','example'=>'線形探索はO(n)、二分探索はO(log n)、バブルソートはO(n²)で表される。','difficulty'=>2,'quiz'=>['question'=>'O(log n)の時間計算量を持つアルゴリズムはどれか？','explanation'=>'二分探索は毎回探索範囲を半分に絞るため、n=100万でも約20回の比較で済む。これがO(log n)の特性。','choices'=>[['body'=>'線形探索','is_correct'=>false],['body'=>'二分探索','is_correct'=>true],['body'=>'バブルソート','is_correct'=>false],['body'=>'行列積','is_correct'=>false]]]],
            ['name'=>'再帰（Recursion）','definition'=>'関数が自分自身を呼び出す手法。基底ケース（終了条件）と再帰ケースで構成される。木やグラフの処理に自然に表現できる。','example'=>'factorial(n) = n * factorial(n-1)、factorial(0) = 1 と再帰で階乗を定義する。','difficulty'=>2,'quiz'=>['question'=>'再帰関数で必ず必要なものはどれか？','explanation'=>'再帰は無限に呼び出されないよう、必ず再帰を停止させる基底ケース（ベースケース）が必要。ないと無限ループしスタックオーバーフローになる。','choices'=>[['body'=>'グローバル変数','is_correct'=>false],['body'=>'再帰を停止させる基底ケース','is_correct'=>true],['body'=>'ループ文','is_correct'=>false],['body'=>'配列','is_correct'=>false]]]],
            ['name'=>'二分探索（Binary Search）','definition'=>'ソート済み配列の中央値と比較して探索範囲を半分に絞る探索アルゴリズム。O(log n)の高速探索が可能。','example'=>'1〜100の数当てゲームで「50より大きい？小さい？」と毎回半分に絞るのが二分探索の考え方。','difficulty'=>2,'quiz'=>['question'=>'二分探索を適用するための前提条件はどれか？','explanation'=>'二分探索は「中央値と比較して大小で半分に絞る」ため、対象の配列がソート済みであることが必須条件。','choices'=>[['body'=>'データが連結リストである','is_correct'=>false],['body'=>'配列がソート済みである','is_correct'=>true],['body'=>'データが均等に分布している','is_correct'=>false],['body'=>'配列のサイズが偶数である','is_correct'=>false]]]],
            ['name'=>'メモ化（Memoization）','definition'=>'関数の計算結果をキャッシュしておき、同じ引数で再度呼ばれたときはキャッシュを返す最適化手法。再帰＋DPの実装手法。','example'=>'fib(n)を再帰で実装する際、計算済みのfib(k)をdictに保存して重複計算を防ぐ。','difficulty'=>3,'quiz'=>['question'=>'メモ化が最も効果的な場面はどれか？','explanation'=>'メモ化は同じ引数での重複呼び出しが多い再帰関数（例：フィボナッチ・DP）で劇的な性能向上をもたらす。','choices'=>[['body'=>'ソートアルゴリズムの高速化','is_correct'=>false],['body'=>'同じ引数で重複呼び出しされる再帰関数','is_correct'=>true],['body'=>'線形探索の高速化','is_correct'=>false],['body'=>'グラフの辺のコスト削減','is_correct'=>false]]]],
            ['name'=>'バックトラッキング','definition'=>'解候補を試し、条件を満たさない場合は直前の状態に戻って別の候補を試す解探索技法。N Queen問題や数独に適用される。','example'=>'数独の空マスに1〜9を仮入力して矛盾したら戻り、別の数字を試す、を繰り返して解を求める。','difficulty'=>4,'quiz'=>['question'=>'バックトラッキングの特徴として正しいものはどれか？','explanation'=>'バックトラッキングは枝刈りを組み合わせることで、全解の候補すべてを列挙せずに効率的に解を探索できる。','choices'=>[['body'=>'常に最短経路を求める','is_correct'=>false],['body'=>'条件不満足時に直前の状態に戻って別候補を試す','is_correct'=>true],['body'=>'配列のソートに使う','is_correct'=>false],['body'=>'グリーディ法とも呼ばれる','is_correct'=>false]]]],
            ['name'=>'トポロジカルソート','definition'=>'有向非巡回グラフ（DAG）の頂点を、辺の向きを壊さないよう線形に並べるアルゴリズム。依存関係の解決に使われる。','example'=>'ビルドシステムでA→B→Cの依存関係を解析し、コンパイル順序を決定するのにトポロジカルソートを使う。','difficulty'=>4,'quiz'=>['question'=>'トポロジカルソートが適用できるグラフの条件はどれか？','explanation'=>'トポロジカルソートは閉路（サイクル）がない有向非巡回グラフ（DAG）にのみ適用できる。循環依存があると不可能。','choices'=>[['body'=>'無向グラフ','is_correct'=>false],['body'=>'有向非巡回グラフ（DAG）','is_correct'=>true],['body'=>'重み付きグラフ','is_correct'=>false],['body'=>'完全グラフ','is_correct'=>false]]]],
            ['name'=>'分割統治法','definition'=>'問題を小さな部分問題に「分割」し、各部分を「統治（解決）」してから結果を「統合」するアルゴリズム設計技法。','example'=>'マージソートは配列を半分に分割（分割）→各半分をソート（統治）→ソート済み配列をマージ（統合）する。','difficulty'=>3,'quiz'=>['question'=>'分割統治法の3ステップとして正しいものはどれか？','explanation'=>'分割統治法は「分割（Divide）→統治/再帰（Conquer）→統合（Combine）」の3ステップで問題を解く技法。','choices'=>[['body'=>'探索→ソート→出力','is_correct'=>false],['body'=>'分割→統治（再帰）→統合','is_correct'=>true],['body'=>'ハッシュ→格納→取得','is_correct'=>false],['body'=>'比較→交換→繰り返し','is_correct'=>false]]]],
            ['name'=>'連結リスト（Linked List）','definition'=>'各要素（ノード）がデータと次のノードへのポインタを持つデータ構造。配列と違い先頭・中間への挿入削除がO(1)。','example'=>'音楽プレイヤーのプレイリストを連結リストで実装すると、曲の挿入・削除を効率的に行える。','difficulty'=>2,'quiz'=>['question'=>'連結リストが配列より優れている操作はどれか？','explanation'=>'連結リストは要素の前後ポインタを付け替えるだけで先頭・中間への挿入・削除をO(1)で行える（配列はO(n)）。','choices'=>[['body'=>'インデックスによるランダムアクセス','is_correct'=>false],['body'=>'先頭・中間への挿入・削除','is_correct'=>true],['body'=>'キャッシュ効率の高い反復処理','is_correct'=>false],['body'=>'メモリ使用量の削減','is_correct'=>false]]]],
        ]];
    }

    private function cloudTerms(): array
    {
        return ['cloud' => [
            ['name'=>'PaaS（Platform as a Service）','definition'=>'OS・ミドルウェア・実行環境を含むプラットフォームをクラウドで提供するサービス形態。アプリ開発に集中できる。','example'=>'Herokuへデプロイするだけでサーバー管理なしにWebアプリを公開できる。','difficulty'=>2,'quiz'=>['question'=>'PaaSの特徴として正しいものはどれか？','explanation'=>'PaaSはOSやミドルウェア管理が不要で開発者はアプリとデータに集中できる。IaaSはインフラも自己管理、SaaSはアプリも提供済み。','choices'=>[['body'=>'OSの管理もユーザーが行う','is_correct'=>false],['body'=>'OS・実行環境はクラウドが管理しアプリ開発に集中できる','is_correct'=>true],['body'=>'アプリケーションもクラウドが提供する','is_correct'=>false],['body'=>'ハードウェアのみ提供される','is_correct'=>false]]]],
            ['name'=>'SaaS（Software as a Service）','definition'=>'ソフトウェアをインターネット経由でサービスとして提供する形態。インストール不要でブラウザで利用できる。','example'=>'Google Workspace・Salesforce・SlackなどがSaaSの代表例。ユーザーはアプリを使うだけ。','difficulty'=>1,'quiz'=>['question'=>'SaaSの説明として正しいものはどれか？','explanation'=>'SaaSはソフトウェアをインターネット経由でサービス提供する形態。ユーザーはインフラ・プラットフォーム・アプリすべてを管理不要。','choices'=>[['body'=>'仮想マシンをクラウドで提供する','is_correct'=>false],['body'=>'完成したソフトウェアをインターネット経由でサービス提供する','is_correct'=>true],['body'=>'開発環境を提供する','is_correct'=>false],['body'=>'物理サーバーをレンタルする','is_correct'=>false]]]],
            ['name'=>'サーバーレス（FaaS）','definition'=>'サーバー管理なしに関数単位でコードを実行するクラウド形態。実行時間のみ課金でスケールは自動。','example'=>'AWS Lambdaに画像リサイズ関数を登録し、S3にアップロードされるたびに自動実行する。','difficulty'=>3,'quiz'=>['question'=>'サーバーレス（FaaS）のメリットとして正しいものはどれか？','explanation'=>'FaaSは実行した分だけ課金・サーバー管理不要・自動スケールが主な利点。ただしコールドスタートのレイテンシが課題。','choices'=>[['body'=>'常時稼働で最速のレスポンスを保証する','is_correct'=>false],['body'=>'サーバー管理不要で実行時間のみ課金される','is_correct'=>true],['body'=>'スケールは手動で行う','is_correct'=>false],['body'=>'ステートフルな処理に最適','is_correct'=>false]]]],
            ['name'=>'Kubernetes（K8s）','definition'=>'コンテナのデプロイ・スケーリング・管理を自動化するオーケストレーションツール。Googleが開発しOSSとして公開。','example'=>'KubernetesのDeploymentで「Podを常に3台維持」と宣言すると、障害時に自動で再起動・再スケジュールされる。','difficulty'=>4,'quiz'=>['question'=>'Kubernetesの主な機能はどれか？','explanation'=>'KubernetesはコンテナをPod単位でスケジュール・管理し、自動スケーリング・自己修復・ローリングアップデートを提供する。','choices'=>[['body'=>'コンテナイメージをビルドする','is_correct'=>false],['body'=>'コンテナのデプロイ・スケーリング・管理を自動化する','is_correct'=>true],['body'=>'ソースコードのバージョン管理','is_correct'=>false],['body'=>'データベースのバックアップ','is_correct'=>false]]]],
            ['name'=>'マイクロサービス','definition'=>'アプリを独立してデプロイ可能な小さなサービス群に分割するアーキテクチャ。各サービスが疎結合で独立スケール可能。','example'=>'ECサイトを「注文サービス・在庫サービス・決済サービス・通知サービス」の独立したマイクロサービスに分割する。','difficulty'=>3,'quiz'=>['question'=>'マイクロサービスのメリットとして最も正しいものはどれか？','explanation'=>'マイクロサービスにより各サービスを独立してデプロイ・スケール・障害分離できるが、サービス間通信の複雑さが増す。','choices'=>[['body'=>'全体のコード量が減少する','is_correct'=>false],['body'=>'各サービスを独立してデプロイ・スケールできる','is_correct'=>true],['body'=>'ネットワーク通信が不要になる','is_correct'=>false],['body'=>'データベースを1つに集約できる','is_correct'=>false]]]],
            ['name'=>'CI/CD（継続的インテグレーション/デリバリー）','definition'=>'コードの変更を自動でビルド・テスト・デプロイするプロセス。GitHub ActionsやCircleCIなどで実装する。','example'=>'GitHubにプッシュするとCIがテストを自動実行し、全テスト通過後にCDが本番環境に自動デプロイする。','difficulty'=>2,'quiz'=>['question'=>'CIの主な目的はどれか？','explanation'=>'CI（継続的インテグレーション）はコードのマージごとに自動ビルド・テストを実行し、不具合を早期発見することが目的。','choices'=>[['body'=>'本番環境への自動デプロイ','is_correct'=>false],['body'=>'コードの自動ビルド・テストで不具合を早期発見','is_correct'=>true],['body'=>'コードレビューの自動化','is_correct'=>false],['body'=>'セキュリティスキャンのみ','is_correct'=>false]]]],
            ['name'=>'IaC（Infrastructure as Code）','definition'=>'インフラの構成をコードで定義・管理する考え方。TerraformやAWS CloudFormationが代表的なツール。','example'=>'Terraformのコードでクラウドリソースを定義し、git管理することでインフラ変更を追跡・レビュー可能にする。','difficulty'=>3,'quiz'=>['question'=>'IaCの主なメリットはどれか？','explanation'=>'IaCによりインフラをコードで管理することで再現性・バージョン管理・自動化が実現し、ヒューマンエラーも減少する。','choices'=>[['body'=>'クラウド料金が安くなる','is_correct'=>false],['body'=>'インフラの再現性・バージョン管理・自動化が実現できる','is_correct'=>true],['body'=>'コンテナが不要になる','is_correct'=>false],['body'=>'データベースのバックアップを自動化する','is_correct'=>false]]]],
            ['name'=>'IAM（Identity and Access Management）','definition'=>'クラウドリソースへのアクセス権限をユーザー・グループ・ロールに細かく管理するサービス。最小権限の原則を実現する。','example'=>'AWS IAMでEC2専用のロールを作成し、S3バケットへのReadのみを許可するポリシーをアタッチする。','difficulty'=>3,'quiz'=>['question'=>'IAMにおける「ロール」の説明として正しいものはどれか？','explanation'=>'IAMロールはユーザーやサービスに一時的に引き受けさせる権限セット。恒久的なユーザー権限とは異なり、AssumeRoleで取得する。','choices'=>[['body'=>'ユーザーの個人情報を管理する','is_correct'=>false],['body'=>'ユーザー/サービスが引き受け可能な権限セット','is_correct'=>true],['body'=>'クラウドのネットワーク設定','is_correct'=>false],['body'=>'データの暗号化キー','is_correct'=>false]]]],
            ['name'=>'VPC（Virtual Private Cloud）','definition'=>'パブリッククラウド内に作る論理的に隔離されたプライベートネットワーク。サブネット・ルーティング・セキュリティを制御できる。','example'=>'AWSでVPCを作り、Webサーバー用パブリックサブネットとDB用プライベートサブネットを分離して配置する。','difficulty'=>3,'quiz'=>['question'=>'VPCのプライベートサブネットに配置すべきリソースはどれか？','explanation'=>'プライベートサブネットはインターネットから直接アクセスできないため、DBサーバーなど外部に公開しないリソースを配置するのが適切。','choices'=>[['body'=>'公開WebサーバーやCDNエッジ','is_correct'=>false],['body'=>'DBサーバーなど外部に公開しないリソース','is_correct'=>true],['body'=>'Webブラウザ','is_correct'=>false],['body'=>'インターネットゲートウェイ','is_correct'=>false]]]],
            ['name'=>'オートスケーリング','definition'=>'負荷に応じてサーバーインスタンスを自動で増減させる仕組み。コスト最適化と可用性向上を同時に実現する。','example'=>'昼間はEC2を10台に自動増設、深夜は2台に縮小することで負荷変動に対応しコストを削減する。','difficulty'=>2,'quiz'=>['question'=>'オートスケーリングの主な目的はどれか？','explanation'=>'オートスケーリングは負荷変動に応じてリソースを自動増減し、過剰プロビジョニングのコスト削減と高負荷時の可用性を両立する。','choices'=>[['body'=>'データを自動バックアップする','is_correct'=>false],['body'=>'負荷に応じてリソースを自動増減しコストと可用性を最適化','is_correct'=>true],['body'=>'セキュリティパッチを自動適用する','is_correct'=>false],['body'=>'ネットワーク帯域を自動拡張する','is_correct'=>false]]]],
            ['name'=>'APIゲートウェイ','definition'=>'クライアントとバックエンドサービスの間に立ち、認証・レート制限・ルーティング・ログ収集を一元管理するサービス。','example'=>'AWS API Gatewayがリクエストを受け、認証後に適切なLambda関数やマイクロサービスにルーティングする。','difficulty'=>3,'quiz'=>['question'=>'APIゲートウェイが担う機能として正しいものはどれか？','explanation'=>'APIゲートウェイは認証・認可・レート制限・ルーティング・ロギングなどを一元管理するマイクロサービスアーキテクチャの入口。','choices'=>[['body'=>'データベースのCRUD操作','is_correct'=>false],['body'=>'認証・レート制限・ルーティングの一元管理','is_correct'=>true],['body'=>'コンテナのビルド','is_correct'=>false],['body'=>'静的ファイルのホスティング','is_correct'=>false]]]],
            ['name'=>'Blue-Greenデプロイメント','definition'=>'同一の本番環境を2つ（Blue・Green）用意し、新バージョンをGreenにデプロイしてロードバランサーを切り替える手法。','example'=>'現在のv1がBlue、新v2をGreenにデプロイしてテスト後、トラフィックをGreenに切り替え。問題時はBlueに即戻し。','difficulty'=>3,'quiz'=>['question'=>'Blue-Greenデプロイメントの主なメリットはどれか？','explanation'=>'Blue-Greenは新旧環境が同時に存在するため、問題発生時にトラフィックを旧環境に即時切り戻し（ロールバック）できる。','choices'=>[['body'=>'デプロイコストが半分になる','is_correct'=>false],['body'=>'問題発生時に旧環境へ即時切り戻しができる','is_correct'=>true],['body'=>'コンテナが不要になる','is_correct'=>false],['body'=>'データベースの移行が不要になる','is_correct'=>false]]]],
            ['name'=>'カナリアリリース','definition'=>'新バージョンを一部のユーザーにだけ段階的に公開し、問題がないことを確認してから全体に展開するデプロイ戦略。','example'=>'新機能を全ユーザーの5%に公開してエラー率を監視し、問題なければ10%→50%→100%と段階的に展開する。','difficulty'=>3,'quiz'=>['question'=>'カナリアリリースの目的はどれか？','explanation'=>'少数のユーザーで新バージョンを試験的に公開し、問題を早期発見しながら全体影響を最小化して安全にリリースする戦略。','choices'=>[['body'=>'デプロイ速度を最大化する','is_correct'=>false],['body'=>'少数ユーザーで段階検証しながら安全に全体展開する','is_correct'=>true],['body'=>'本番データをバックアップする','is_correct'=>false],['body'=>'古いコードを完全削除する','is_correct'=>false]]]],
            ['name'=>'エッジコンピューティング','definition'=>'データ処理をクラウドの中央サーバーでなくユーザーに近いエッジ（端末・基地局）で行う分散処理の形態。レイテンシを削減する。','example'=>'自動運転車がクラウドに送信せず車内でリアルタイム障害物検知を行うのがエッジコンピューティングの例。','difficulty'=>4,'quiz'=>['question'=>'エッジコンピューティングの主なメリットはどれか？','explanation'=>'データ処理をユーザー近くで行うことで、クラウドへの往復時間がなくなりレイテンシが大幅に削減される。帯域節約にも貢献。','choices'=>[['body'=>'処理コストが増加する','is_correct'=>false],['body'=>'ユーザー近くで処理しレイテンシを大幅削減する','is_correct'=>true],['body'=>'データを常にクラウドに送信する','is_correct'=>false],['body'=>'クラウドより高いセキュリティを保証する','is_correct'=>false]]]],
            ['name'=>'オブザーバビリティ（可観測性）','definition'=>'システムの内部状態を外部の出力（メトリクス・ログ・トレース）から推測できる性質。SREの重要概念。','example'=>'PrometheusでメトリクスをGrafanaで可視化し、Jaegerで分散トレーシングを実装することでオブザーバビリティを高める。','difficulty'=>4,'quiz'=>['question'=>'オブザーバビリティの3本柱として正しいものはどれか？','explanation'=>'オブザーバビリティはメトリクス（数値）・ログ（テキスト記録）・トレース（処理の追跡）の3要素で構成される。','choices'=>[['body'=>'CPU・メモリ・ディスク','is_correct'=>false],['body'=>'メトリクス・ログ・トレース','is_correct'=>true],['body'=>'開発・テスト・本番','is_correct'=>false],['body'=>'コンテナ・サーバー・データベース','is_correct'=>false]]]],
            ['name'=>'SLA（Service Level Agreement）','definition'=>'サービス提供者とユーザー間で合意するサービスレベルの契約。稼働率・応答時間・サポート対応時間などを明記する。','example'=>'AWS EC2のSLAは月間稼働率99.99%を保証。未達の場合はサービスクレジットが払い戻される。','difficulty'=>3,'quiz'=>['question'=>'SLA99.9%の場合、月の最大許容ダウンタイムはどれか？','explanation'=>'月720時間×0.1%=0.72時間=約43分。SLAの稼働率は年・月単位で計算される。','choices'=>[['body'=>'約7.2時間','is_correct'=>false],['body'=>'約43分','is_correct'=>true],['body'=>'約4.3時間','is_correct'=>false],['body'=>'約7.2分','is_correct'=>false]]]],
            ['name'=>'マルチテナント','definition'=>'1つのシステムインスタンスを複数の顧客（テナント）が共有するアーキテクチャ。SaaSの基本的な提供形態。','example'=>'Salesforceは1つのプラットフォームを何万社もの企業テナントが共有して利用するマルチテナント型SaaS。','difficulty'=>3,'quiz'=>['question'=>'マルチテナントアーキテクチャの主なメリットはどれか？','explanation'=>'マルチテナントはリソース共有によりインフラコストが削減でき、アップデートも一括で行えるため運用効率が高い。','choices'=>[['body'=>'テナントごとに独立したサーバーが確保される','is_correct'=>false],['body'=>'リソース共有でコスト削減・運用効率化が実現できる','is_correct'=>true],['body'=>'セキュリティが最高水準になる','is_correct'=>false],['body'=>'カスタマイズが最も自由にできる','is_correct'=>false]]]],
            ['name'=>'コールドスタート（サーバーレス）','definition'=>'サーバーレス関数が一定時間後に初めて起動される際にかかる初期化の遅延。コンテナ起動やランタイム初期化が原因。','example'=>'しばらく呼ばれなかったLambda関数が次のリクエストで500ms以上の遅延（コールドスタート）を起こす。','difficulty'=>3,'quiz'=>['question'=>'サーバーレスのコールドスタートを軽減する方法はどれか？','explanation'=>'プロビジョニングされたコンカレンシー（AWS）やKeep-Warm（定期実行）でコンテナを温めておくことでコールドスタートを軽減できる。','choices'=>[['body'=>'関数コードを増やす','is_correct'=>false],['body'=>'定期的にウォームアップリクエストを送る（Keep-Warm）','is_correct'=>true],['body'=>'HTTPSを使わない','is_correct'=>false],['body'=>'より大きなメモリを割り当てる','is_correct'=>false]]]],
            ['name'=>'スケールアップ / スケールアウト','definition'=>'スケールアップは1台のスペックを向上させる垂直スケーリング。スケールアウトは台数を増やす水平スケーリング。','example'=>'DBサーバーのメモリを32GB→128GBにするのがスケールアップ。Webサーバーを2台から10台に増やすのがスケールアウト。','difficulty'=>2,'quiz'=>['question'=>'クラウドネイティブなシステムが一般に推奨するスケーリング戦略はどれか？','explanation'=>'クラウドではスケールアウト（水平スケーリング）が推奨される。垂直スケーリングには物理的な上限があるため。','choices'=>[['body'=>'スケールアップ（垂直スケーリング）','is_correct'=>false],['body'=>'スケールアウト（水平スケーリング）','is_correct'=>true],['body'=>'どちらも同等に使われる','is_correct'=>false],['body'=>'スケーリングは不要','is_correct'=>false]]]],
            ['name'=>'メッセージキュー','definition'=>'サービス間で非同期にメッセージを送受信するための仲介コンポーネント。RabbitMQ・AWS SQS・Apache Kafkaが代表的。','example'=>'注文APIがSQSキューにメッセージを積み、在庫サービスが非同期でキューを監視して処理する。','difficulty'=>3,'quiz'=>['question'=>'メッセージキューを使う主な目的はどれか？','explanation'=>'メッセージキューによりサービスを非同期・疎結合にでき、送信側と受信側の処理速度の差や一時的な障害を吸収できる。','choices'=>[['body'=>'サービス間の同期通信を高速化する','is_correct'=>false],['body'=>'サービスを非同期・疎結合にして負荷変動と障害を吸収する','is_correct'=>true],['body'=>'データを暗号化して転送する','is_correct'=>false],['body'=>'APIの認証を管理する','is_correct'=>false]]]],
            ['name'=>'Terraform','definition'=>'HashiCorpが開発したIaCツール。HCL（HashiCorp Configuration Language）でマルチクラウドのインフラを宣言的に管理する。','example'=>'main.tfにAWS EC2・RDS・VPCを記述し「terraform apply」でインフラを一括構築・管理する。','difficulty'=>3,'quiz'=>['question'=>'Terraformの「terraform plan」コマンドの役割はどれか？','explanation'=>'terraform planは実際の変更を加えず、適用するとどのリソースが作成・変更・削除されるかのプレビューを表示する。','choices'=>[['body'=>'インフラの変更を実際に適用する','is_correct'=>false],['body'=>'変更内容のプレビューを表示する（実際には変更しない）','is_correct'=>true],['body'=>'インフラを全て削除する','is_correct'=>false],['body'=>'コードの文法チェックのみ行う','is_correct'=>false]]]],
        ]];
    }

    private function webTerms(): array
    {
        return ['web' => [
            ['name'=>'GraphQL','definition'=>'Facebookが開発したAPIクエリ言語。クライアントが必要なデータのみ指定して取得でき、アンダーフェッチ・オーバーフェッチを解消する。','example'=>'REST APIでは/users・/posts・/commentsと3回叩く処理を、GraphQLでは1クエリで必要フィールドだけ取得できる。','difficulty'=>3,'quiz'=>['question'=>'GraphQLがRESTに対して持つ主なメリットはどれか？','explanation'=>'GraphQLはクライアントが必要なデータ構造を指定するため、過剰・不足なくデータを1リクエストで取得できる。','choices'=>[['body'=>'通信を暗号化できる','is_correct'=>false],['body'=>'クライアントが必要なフィールドのみ指定して取得できる','is_correct'=>true],['body'=>'サーバーが不要になる','is_correct'=>false],['body'=>'データベースに直接アクセスできる','is_correct'=>false]]]],
            ['name'=>'SPA（シングルページアプリケーション）','definition'=>'ページ遷移時にHTMLを丸ごと再読み込みせず、JavaScriptで動的にコンテンツを書き換えるWebアプリ。','example'=>'GmailやGoogle MapsはSPA。ページ遷移してもブラウザのリロードなしにコンテンツが切り替わる。','difficulty'=>2,'quiz'=>['question'=>'SPAのデメリットとして正しいものはどれか？','explanation'=>'SPAはJavaScriptで描画するため、クローラーがJSを実行できない場合にSEO対策が難しくなる。SSRやSSGで解決することが多い。','choices'=>[['body'=>'ページ遷移が遅い','is_correct'=>false],['body'=>'SEO対策が難しい場合がある','is_correct'=>true],['body'=>'ユーザー体験が悪い','is_correct'=>false],['body'=>'JavaScriptが不要','is_correct'=>false]]]],
            ['name'=>'SSR（サーバーサイドレンダリング）','definition'=>'HTMLをサーバー側で生成してクライアントに返す手法。SEO対策や初期表示速度の向上に有効。','example'=>'Next.jsのSSRでリクエスト時にReactコンポーネントをサーバーで描画してHTMLを返し、クローラーがコンテンツを取得できる。','difficulty'=>3,'quiz'=>['question'=>'SSRのメリットとして正しいものはどれか？','explanation'=>'SSRはサーバーで生成されたHTMLを返すため、クローラーがJavaScript実行なしにコンテンツを取得でき、SEO向上に有効。','choices'=>[['body'=>'サーバー負荷がゼロになる','is_correct'=>false],['body'=>'クローラーがコンテンツを取得しやすくSEOに有利','is_correct'=>true],['body'=>'クライアントのJSが不要になる','is_correct'=>false],['body'=>'データベースが不要になる','is_correct'=>false]]]],
            ['name'=>'PWA（Progressive Web App）','definition'=>'Webアプリをネイティブアプリに近い体験で提供する技術。オフライン対応・プッシュ通知・ホーム画面追加が可能。','example'=>'TwitterのPWA版はオフラインでもキャッシュしたツイートを表示し、ホーム画面にアイコンを追加できる。','difficulty'=>3,'quiz'=>['question'=>'PWAが実現する機能として正しいものはどれか？','explanation'=>'PWAはService WorkerとCache APIによりオフライン動作を実現し、Web Push APIでプッシュ通知も可能にする。','choices'=>[['body'=>'ネイティブコードのコンパイル','is_correct'=>false],['body'=>'オフライン対応・プッシュ通知・ホーム画面追加','is_correct'=>true],['body'=>'データベースの直接操作','is_correct'=>false],['body'=>'カメラ・マイクの使用（Webは不可）','is_correct'=>false]]]],
            ['name'=>'CORS（Cross-Origin Resource Sharing）','definition'=>'ブラウザが異なるオリジン（ドメイン・ポート・スキーム）へのリクエストを制限する仕組み。サーバーがヘッダーで許可オリジンを指定する。','example'=>'localhost:5173のVueアプリがlocalhost:8000のLaravel APIにアクセスするとき、CORSを適切に設定しないとブラウザがブロックする。','difficulty'=>3,'quiz'=>['question'=>'CORSはどこで制御されるか？','explanation'=>'CORSのポリシー適用はブラウザ側で行われる。サーバーはAccess-Control-Allow-Originヘッダーでどのオリジンからのリクエストを許可するかを指定する。','choices'=>[['body'=>'ファイアウォールで制御される','is_correct'=>false],['body'=>'ブラウザ側で制御され、サーバーがヘッダーで許可オリジンを指定する','is_correct'=>true],['body'=>'DNSで制御される','is_correct'=>false],['body'=>'クライアントJSでのみ制御できる','is_correct'=>false]]]],
            ['name'=>'TypeScript','definition'=>'JavaScriptに静的型付けを追加したMicrosoftが開発する言語。大規模開発での型安全性とIDEサポートを提供する。','example'=>'TypeScriptの型定義により、存在しないプロパティへのアクセスをコンパイル時にエラーとして検出できる。','difficulty'=>2,'quiz'=>['question'=>'TypeScriptの主なメリットはどれか？','explanation'=>'TypeScriptの静的型チェックにより実行前にバグを発見でき、IDEの補完・リファクタリングサポートも強化される。','choices'=>[['body'=>'実行速度がJavaScriptより速い','is_correct'=>false],['body'=>'静的型チェックで実行前にバグを検出できる','is_correct'=>true],['body'=>'ブラウザがネイティブに実行できる','is_correct'=>false],['body'=>'サーバーサイドでのみ動作する','is_correct'=>false]]]],
            ['name'=>'REST API','definition'=>'HTTPメソッド（GET・POST・PUT・DELETE）とURIを用いてリソースを操作するWebAPIの設計スタイル。ステートレスが原則。','example'=>'GET /api/users で一覧取得、POST /api/users で作成、PUT /api/users/1 で更新するRESTful API。','difficulty'=>2,'quiz'=>['question'=>'RESTful APIにおけるHTTPメソッドの正しい使い分けはどれか？','explanation'=>'RESTではGET=取得、POST=作成、PUT/PATCH=更新、DELETE=削除とHTTPメソッドにリソース操作の意味を対応させる。','choices'=>[['body'=>'全操作にGETを使う','is_correct'=>false],['body'=>'GET=取得、POST=作成、PUT=更新、DELETE=削除','is_correct'=>true],['body'=>'全操作にPOSTを使う','is_correct'=>false],['body'=>'POSTのみサーバーにデータを送れる','is_correct'=>false]]]],
            ['name'=>'Service Worker','definition'=>'Webページとは独立してバックグラウンドで動作するJavaScriptのWorker。キャッシュ制御・プッシュ通知・オフライン対応を実現する。','example'=>'Service Workerが静的ファイルをキャッシュし、ネットワーク不通時でもWebアプリをオフラインで動作させる。','difficulty'=>4,'quiz'=>['question'=>'Service Workerが動作する環境として正しいものはどれか？','explanation'=>'Service WorkerはHTTPSまたはlocalhost限定で動作する。プロキシのようにWebページのリクエストをインターセプトする。','choices'=>[['body'=>'HTTP環境でも動作する','is_correct'=>false],['body'=>'HTTPSまたはlocalhostのみで動作する','is_correct'=>true],['body'=>'DOMに直接アクセスできる','is_correct'=>false],['body'=>'iOSのSafariでは使用不可','is_correct'=>false]]]],
            ['name'=>'Virtual DOM','definition'=>'実際のDOMの仮想コピーをJavaScriptオブジェクトとして持ち、差分のみ実DOMに反映する手法。ReactやVueが採用。','example'=>'Reactがstate更新のたびにVirtual DOM同士の差分（Diff）を計算し、変更部分のみ実DOMを更新して高速描画する。','difficulty'=>3,'quiz'=>['question'=>'Virtual DOMを使う主な目的はどれか？','explanation'=>'Virtual DOMにより差分計算で変更箇所を絞ってDOMを更新できる。直接DOM操作より一般に効率的でコードも書きやすい。','choices'=>[['body'=>'CSSを自動生成する','is_correct'=>false],['body'=>'差分のみDOM更新することで描画を効率化する','is_correct'=>true],['body'=>'サーバーサイドレンダリングを実現する','is_correct'=>false],['body'=>'HTTPリクエストを自動でキャッシュする','is_correct'=>false]]]],
            ['name'=>'レスポンシブデザイン','definition'=>'デバイスの画面サイズに合わせてレイアウトを自動調整するWebデザイン手法。CSSのメディアクエリを活用する。','example'=>'@media (max-width: 768px) { ... } でスマートフォン向けに1カラムレイアウトに切り替える。','difficulty'=>1,'quiz'=>['question'=>'レスポンシブデザインで主に使うCSSの機能はどれか？','explanation'=>'メディアクエリ（@media）でデバイスの幅・高さ・解像度などを条件に、異なるCSSを適用してレイアウトを調整する。','choices'=>[['body'=>'Flexboxのみ','is_correct'=>false],['body'=>'メディアクエリ（@media）','is_correct'=>true],['body'=>'CSS Grid専用機能','is_correct'=>false],['body'=>'JavaScriptのみ','is_correct'=>false]]]],
            ['name'=>'HTTP/3','definition'=>'TCPの代わりにQUIC（UDP上の新プロトコル）を使うHTTPの第3世代。接続確立の高速化と0-RTT再接続を実現する。','example'=>'HTTP/3はモバイル環境でのパケットロス時もTCPのHOLブロッキングなしに通信を継続できる。','difficulty'=>4,'quiz'=>['question'=>'HTTP/3がHTTP/2と異なるトランスポート層のプロトコルはどれか？','explanation'=>'HTTP/3はTCPではなくUDP上に実装されたQUICを使用する。QUICにより接続確立の短縮と0-RTTの実現が可能になった。','choices'=>[['body'=>'TCP','is_correct'=>false],['body'=>'QUIC（UDP上のプロトコル）','is_correct'=>true],['body'=>'WebSocket','is_correct'=>false],['body'=>'SCTP','is_correct'=>false]]]],
            ['name'=>'CSP（Content Security Policy）','definition'=>'Webサイトが読み込めるリソースのソースをHTTPヘッダーで制限するセキュリティ機能。XSS攻撃を緩和する。','example'=>'Content-Security-Policy: script-src \'self\' と設定し、外部スクリプトの読み込みをブロックしてXSSリスクを軽減する。','difficulty'=>3,'quiz'=>['question'=>'CSPの主な目的はどれか？','explanation'=>'CSPは許可されたソースからのリソースのみ読み込みを許可することで、XSSや不正スクリプト注入を防ぐセキュリティ機構。','choices'=>[['body'=>'HTTPS通信を強制する','is_correct'=>false],['body'=>'不正スクリプトのロードを防ぎXSSを緩和する','is_correct'=>true],['body'=>'SQLインジェクションを防ぐ','is_correct'=>false],['body'=>'CORSを制御する','is_correct'=>false]]]],
            ['name'=>'WebAssembly（WASM）','definition'=>'ブラウザ上でC/C++・Rustなどをバイナリ形式で高速実行できる技術。JavaScriptより高速な数値演算に使われる。','example'=>'Figmaはレンダリングエンジンの主要部分をWebAssemblyで実装し、ブラウザ上でネイティブに近い描画速度を実現している。','difficulty'=>4,'quiz'=>['question'=>'WebAssemblyの主な特徴として正しいものはどれか？','explanation'=>'WASMはバイナリ形式でブラウザが直接実行できるため、JavaScriptより高速な実行が可能で、C/C++/Rustなどの言語からコンパイルできる。','choices'=>[['body'=>'JavaScriptのサブセット','is_correct'=>false],['body'=>'バイナリ形式でJSより高速実行できる低レベル仮想マシン','is_correct'=>true],['body'=>'サーバーサイドでのみ動作する','is_correct'=>false],['body'=>'DOMを操作できないのでUIには使えない','is_correct'=>false]]]],
            ['name'=>'Core Web Vitals','definition'=>'Googleが定めるWebパフォーマンスの主要指標。LCP（最大コンテンツ描画）・INP（インタラクション）・CLS（レイアウトシフト）の3指標。','example'=>'LCPが2.5秒以下・INPが200ms以下・CLSが0.1以下を達成するとCore Web Vitals「良好」とみなされSEOにも好影響。','difficulty'=>3,'quiz'=>['question'=>'Core Web VitalsのLCPが計測するものはどれか？','explanation'=>'LCP（Largest Contentful Paint）はページ内の最大のコンテンツ要素（画像やテキスト）が描画されるまでの時間を計測する。','choices'=>[['body'=>'最初のバイトが届くまでの時間','is_correct'=>false],['body'=>'ページ最大コンテンツ要素が描画されるまでの時間','is_correct'=>true],['body'=>'レイアウトのずれ量','is_correct'=>false],['body'=>'インタラクションの応答時間','is_correct'=>false]]]],
            ['name'=>'localStorage','definition'=>'ブラウザにキーと値のペアを永続的に保存するWeb API。ページを閉じても残り、オリジンごとに独立している。','example'=>'ユーザー設定（ダークモードON/OFFなど）をlocalStorageに保存し、次回訪問時に設定を復元する。','difficulty'=>2,'quiz'=>['question'=>'localStorageとsessionStorageの違いはどれか？','explanation'=>'localStorageはタブ・ウィンドウを閉じても残る。sessionStorageはタブを閉じると削除される。どちらもオリジンスコープ。','choices'=>[['body'=>'localStorageはHTTPSのみ使用可','is_correct'=>false],['body'=>'localStorageはタブを閉じても保持、sessionStorageは削除される','is_correct'=>true],['body'=>'sessionStorageの方が容量が大きい','is_correct'=>false],['body'=>'localStorageはサーバーに自動送信される','is_correct'=>false]]]],
            ['name'=>'Flexbox','definition'=>'CSS3のレイアウトモジュール。コンテナ内の要素を1次元（行または列）で柔軟に配置・整列・分配できる。','example'=>'display:flex; justify-content:space-between; align-items:center; でナビゲーションバーを簡単に作れる。','difficulty'=>1,'quiz'=>['question'=>'Flexboxで主軸方向の要素配置を指定するプロパティはどれか？','explanation'=>'justify-contentは主軸（flex-direction）に沿った要素の配置を制御し、flex-start・center・space-betweenなどが指定できる。','choices'=>[['body'=>'align-items','is_correct'=>false],['body'=>'justify-content','is_correct'=>true],['body'=>'flex-wrap','is_correct'=>false],['body'=>'align-self','is_correct'=>false]]]],
            ['name'=>'CSS Grid','definition'=>'CSSの2次元グリッドレイアウトシステム。行と列を定義してコンテンツを自由に配置できる。Flexboxより複雑なレイアウトに適する。','example'=>'grid-template-columns: repeat(3, 1fr) でカード3列レイアウトを1行で定義できる。','difficulty'=>2,'quiz'=>['question'=>'CSS GridとFlexboxの主な使い分けとして正しいものはどれか？','explanation'=>'Flexboxは1次元（行または列）の配置に適し、CSS Gridは行・列両方を同時に制御する2次元レイアウトに適する。','choices'=>[['body'=>'GridはモバイルのみFlexboxはPCのみ','is_correct'=>false],['body'=>'Gridは2次元レイアウト、Flexboxは1次元レイアウトに適する','is_correct'=>true],['body'=>'両者は全く同じ用途','is_correct'=>false],['body'=>'FlexboxはIEでのみ動作する','is_correct'=>false]]]],
            ['name'=>'OpenAPI仕様（Swagger）','definition'=>'RESTful APIをYAML/JSONで記述する標準仕様。API定義からドキュメント生成・コード生成・テストが可能になる。','example'=>'openapi.yamlにエンドポイント・パラメータ・レスポンス型を定義し、Swagger UIで対話的なAPIドキュメントを生成する。','difficulty'=>3,'quiz'=>['question'=>'OpenAPI仕様の主なメリットはどれか？','explanation'=>'OpenAPI仕様によりAPIを機械可読な形で定義でき、ドキュメント自動生成・クライアントSDK生成・バリデーションが可能になる。','choices'=>[['body'=>'データベース設計を自動化する','is_correct'=>false],['body'=>'API定義からドキュメント・SDKを自動生成できる','is_correct'=>true],['body'=>'セキュリティを自動的に強化する','is_correct'=>false],['body'=>'サーバーレスアーキテクチャ専用の仕様','is_correct'=>false]]]],
            ['name'=>'SSG（静的サイト生成）','definition'=>'ビルド時にHTMLを事前生成してCDNに配置する手法。実行時にサーバー処理が不要で最高速かつセキュリティが高い。','example'=>'Next.jsのSSGでブログ記事をビルド時にHTMLとして生成し、Vercelに配置することでサーバー不要で高速配信する。','difficulty'=>3,'quiz'=>['question'=>'SSGが最も向いているコンテンツはどれか？','explanation'=>'SSGはビルド時に全ページを生成するため、更新頻度が低く内容が静的なブログ・ドキュメントサイトに最適。リアルタイム更新が必要なコンテンツには不向き。','choices'=>[['body'=>'リアルタイムな株価情報ページ','is_correct'=>false],['body'=>'更新頻度が低いブログや技術ドキュメント','is_correct'=>true],['body'=>'SNSのタイムライン','is_correct'=>false],['body'=>'ユーザーごとにパーソナライズされたダッシュボード','is_correct'=>false]]]],
            ['name'=>'アクセシビリティ（a11y）','definition'=>'障害のある人も含む全てのユーザーがWebサービスを利用できるよう設計する考え方。WAI-ARIAやセマンティックHTMLが手段。','example'=>'img要素にalt属性を付けてスクリーンリーダー対応にする。ボタンにaria-labelを付けてスクリーンリーダーに操作を説明する。','difficulty'=>2,'quiz'=>['question'=>'Webアクセシビリティの「a11y」の意味はどれか？','explanation'=>'a11yは"accessibility"の省略形（aとyの間に11文字）。世界標準のガイドラインとしてW3CのWCAGが参照される。','choices'=>[['body'=>'アルゴリズム（algorithm）の省略','is_correct'=>false],['body'=>'accessibility（アクセシビリティ）の省略形','is_correct'=>true],['body'=>'自動化（automation）の略称','is_correct'=>false],['body'=>'分析ツール（analytics）の略称','is_correct'=>false]]]],
        ]];
    }

    private function programmingTerms(): array
    {
        return ['programming' => [
            ['name'=>'クロージャ（Closure）','definition'=>'関数がその定義時の環境（スコープ）を記憶して保持する仕組み。関数が外側のスコープの変数を「閉じ込める」。','example'=>'const add = (x) => (y) => x + y; // add(3)(4)=7。内部関数がxを記憶するクロージャ。','difficulty'=>3,'quiz'=>['question'=>'クロージャの説明として正しいものはどれか？','explanation'=>'クロージャは関数が定義された時点のスコープを記憶し、外側の変数を関数実行後も参照し続けることができる仕組み。','choices'=>[['body'=>'クラスのコンストラクタの別名','is_correct'=>false],['body'=>'関数が定義時のスコープを記憶して参照できる仕組み','is_correct'=>true],['body'=>'例外処理の一種','is_correct'=>false],['body'=>'ループを最適化する技法','is_correct'=>false]]]],
            ['name'=>'高階関数（Higher-Order Function）','definition'=>'関数を引数として受け取ったり、戻り値として返す関数。map・filter・reduceが代表的。関数型プログラミングの中心概念。','example'=>'[1,2,3].map(x => x * 2) はmapという高階関数に無名関数を渡して[2,4,6]を得る。','difficulty'=>3,'quiz'=>['question'=>'高階関数の特徴として正しいものはどれか？','explanation'=>'高階関数は「関数を引数に取る」または「関数を戻り値として返す」どちらかまたは両方を満たす関数。','choices'=>[['body'=>'再帰呼び出しを行う関数','is_correct'=>false],['body'=>'関数を引数にとったり戻り値として返す関数','is_correct'=>true],['body'=>'クラスのメソッドの別名','is_correct'=>false],['body'=>'非同期で実行される関数','is_correct'=>false]]]],
            ['name'=>'例外処理（try/catch）','definition'=>'プログラム実行中のエラー（例外）を補足して適切に処理する仕組み。try-catch-finallyブロックで記述する。','example'=>'try { await api.get(\'/data\') } catch (e) { console.error(e) } finally { loading = false }','difficulty'=>1,'quiz'=>['question'=>'finallyブロックの特徴として正しいものはどれか？','explanation'=>'finallyブロックはtry・catchのどちらが実行されても必ず最後に実行される。リソース解放などの後処理に使う。','choices'=>[['body'=>'エラーが発生した時のみ実行される','is_correct'=>false],['body'=>'例外の有無に関わらず必ず実行される','is_correct'=>true],['body'=>'例外が発生しなかった時のみ実行される','is_correct'=>false],['body'=>'再帰呼び出しの終了条件','is_correct'=>false]]]],
            ['name'=>'インターフェース（Interface）','definition'=>'クラスが実装すべきメソッドやプロパティの仕様を定義する抽象的な型。実装を持たず、型契約として機能する。','example'=>'TypeScriptのinterface User { id: number; name: string; } を定義し、実装クラスが規約を満たすことを強制する。','difficulty'=>3,'quiz'=>['question'=>'インターフェースの役割として正しいものはどれか？','explanation'=>'インターフェースは実装を持たず、クラスが持つべきメソッドやプロパティの型契約を定義する。型安全性と疎結合を促進する。','choices'=>[['body'=>'具体的なメソッドの実装を持つ','is_correct'=>false],['body'=>'クラスが実装すべき型契約を定義する','is_correct'=>true],['body'=>'オブジェクトをコピーする','is_correct'=>false],['body'=>'ループを制御する','is_correct'=>false]]]],
            ['name'=>'SOLID原則','definition'=>'オブジェクト指向設計の5原則。単一責任（S）・開放閉鎖（O）・リスコフ置換（L）・インターフェース分離（I）・依存性逆転（D）。','example'=>'単一責任原則：UserクラスはユーザーデータのみでDB保存はRepositoryクラスに委譲し、責務を1つに絞る。','difficulty'=>4,'quiz'=>['question'=>'SOLID原則の「O」が示す開放閉鎖原則の内容はどれか？','explanation'=>'開放閉鎖原則（Open/Closed Principle）は「拡張に対して開いており、修正に対して閉じている」設計を求める。新機能は既存コード変更なく追加できるべき。','choices'=>[['body'=>'全てのメソッドをpublicにする','is_correct'=>false],['body'=>'拡張に対して開いており修正に対して閉じている','is_correct'=>true],['body'=>'1クラスに1メソッドのみ持つ','is_correct'=>false],['body'=>'継承を使わない','is_correct'=>false]]]],
            ['name'=>'TDD（テスト駆動開発）','definition'=>'テストを先に書いてから実装するソフトウェア開発手法。Red（失敗テスト）→Green（実装）→Refactor のサイクルで開発する。','example'=>'isEven(n)関数を実装する前にexpect(isEven(2)).toBe(true)のテストを書き、通過するよう実装する。','difficulty'=>3,'quiz'=>['question'=>'TDDの開発サイクルとして正しいものはどれか？','explanation'=>'TDDはRed（失敗するテストを書く）→Green（テストを通す最小実装）→Refactor（コードを整える）の繰り返し。','choices'=>[['body'=>'実装→テスト→リファクタリング','is_correct'=>false],['body'=>'テスト（Red）→実装（Green）→リファクタリング','is_correct'=>true],['body'=>'設計→実装→テスト','is_correct'=>false],['body'=>'リファクタリング→テスト→実装','is_correct'=>false]]]],
            ['name'=>'async/await','definition'=>'Promiseベースの非同期処理を同期的な構文で記述できるJavaScriptの構文糖衣。コードの可読性を大幅に向上させる。','example'=>'const data = await api.get(\'/users\'); とPromiseのthenチェーン不要で非同期処理が書ける。','difficulty'=>2,'quiz'=>['question'=>'async/awaitについて正しいものはどれか？','explanation'=>'async/awaitはPromiseを基盤としており、awaitはPromiseが解決されるまで非同期に待機する。同期的に見えるがブロッキングではない。','choices'=>[['body'=>'同期的にブロッキングしてデータを待つ','is_correct'=>false],['body'=>'Promiseを基盤とし非同期処理を同期的な構文で書ける','is_correct'=>true],['body'=>'マルチスレッドで並行処理する','is_correct'=>false],['body'=>'コールバック関数の別名','is_correct'=>false]]]],
            ['name'=>'ガベージコレクション（GC）','definition'=>'使用されなくなったメモリを自動的に解放するメモリ管理機能。PythonやJava・JavaScriptが採用。C/C++は手動管理。','example'=>'JavaScript上でオブジェクトへの参照がなくなると、GCが不要なメモリを自動回収するため手動freeが不要。','difficulty'=>3,'quiz'=>['question'=>'ガベージコレクションのデメリットとして正しいものはどれか？','explanation'=>'GCは任意のタイミングで動作しメモリを回収するため、GC実行中に処理が一時停止（STW:Stop The World）することがある。','choices'=>[['body'=>'メモリリークが必ず起きる','is_correct'=>false],['body'=>'GC実行時に処理が一時停止することがある','is_correct'=>true],['body'=>'メモリが永遠に増加する','is_correct'=>false],['body'=>'手動メモリ管理より速い','is_correct'=>false]]]],
            ['name'=>'依存性注入（DI：Dependency Injection）','definition'=>'クラスが依存するオブジェクトを外部から注入するデザインパターン。テスト容易性・疎結合・保守性を向上させる。','example'=>'UserServiceのコンストラクタにUserRepositoryを引数で渡す。テスト時はモックリポジトリを注入できる。','difficulty'=>3,'quiz'=>['question'=>'依存性注入のメリットとして正しいものはどれか？','explanation'=>'DIにより依存関係が外部化されるため、テスト時にモックを注入できる。また実装の変更が依存側に影響しにくくなり疎結合が実現できる。','choices'=>[['body'=>'コード量が削減される','is_correct'=>false],['body'=>'テスト時にモックを注入でき疎結合を実現できる','is_correct'=>true],['body'=>'実行速度が向上する','is_correct'=>false],['body'=>'グローバル変数が不要になる','is_correct'=>false]]]],
            ['name'=>'デザインパターン','definition'=>'ソフトウェア設計でよく発生する問題に対する再利用可能な解決策のカタログ。GoFの23パターンが有名。','example'=>'Singletonパターン：アプリ内で1つのインスタンスのみを持つDBコネクション管理クラスを実装する。','difficulty'=>3,'quiz'=>['question'=>'Observerパターンの説明として正しいものはどれか？','explanation'=>'Observerパターンはオブジェクトの状態変化を複数のオブザーバー（リスナー）に自動通知する仕組み。イベントシステムの基礎。','choices'=>[['body'=>'1つのインスタンスのみを作る','is_correct'=>false],['body'=>'状態変化を複数のオブザーバーに自動通知する','is_correct'=>true],['body'=>'インターフェースを変換して互換性を持たせる','is_correct'=>false],['body'=>'オブジェクトを生成するファクトリーを提供する','is_correct'=>false]]]],
            ['name'=>'継承（Inheritance）','definition'=>'既存クラス（親クラス/スーパークラス）の属性・メソッドを新クラス（子クラス/サブクラス）が引き継ぐOOPの機能。','example'=>'Animalクラスのeat()メソッドをDogクラスが継承し、Dogクラス独自のbark()を追加する。','difficulty'=>2,'quiz'=>['question'=>'継承の「is-a」関係の例として正しいものはどれか？','explanation'=>'「Dog is an Animal（犬は動物である）」のような上位分類に属する関係が継承の「is-a」関係。「Car has a Engine」はhas-aで合成。','choices'=>[['body'=>'車（Car）はエンジン（Engine）を持つ','is_correct'=>false],['body'=>'犬（Dog）は動物（Animal）である','is_correct'=>true],['body'=>'ユーザーはアドレスを持つ','is_correct'=>false],['body'=>'注文は商品のリストを持つ','is_correct'=>false]]]],
            ['name'=>'カプセル化','definition'=>'データと操作を1つの単位（クラス）にまとめ、内部実装を外部から隠蔽するOOPの原則。アクセス修飾子で制御する。','example'=>'privateフィールドのageをgetAge()・setAge()メソッドでのみアクセスさせることで、不正な値設定を防ぐ。','difficulty'=>2,'quiz'=>['question'=>'カプセル化のメリットとして正しいものはどれか？','explanation'=>'カプセル化により内部実装の詳細が隠蔽されるため、外部コードへの影響なく内部実装を変更でき、不正アクセスも防止できる。','choices'=>[['body'=>'コードの実行速度が上がる','is_correct'=>false],['body'=>'内部実装を隠蔽し変更の影響を最小化する','is_correct'=>true],['body'=>'クラスの継承ができるようになる','is_correct'=>false],['body'=>'グローバル変数の使用が不要になる','is_correct'=>false]]]],
            ['name'=>'ポリモーフィズム（多態性）','definition'=>'同じメソッド名・インターフェースで異なるクラスの異なる動作を呼び出せるOOPの機能。継承やインターフェースで実現する。','example'=>'Shape.draw()をCircleはpixel描画・RectangleはSVG描画で実装し、同じdraw()呼び出しで異なる描画が実行される。','difficulty'=>3,'quiz'=>['question'=>'ポリモーフィズムが実現することはどれか？','explanation'=>'ポリモーフィズムにより、同じメソッド名の呼び出しでオブジェクトの実際の型に応じた異なる処理が自動的に実行される（動的ディスパッチ）。','choices'=>[['body'=>'全クラスが同じ処理を実行する','is_correct'=>false],['body'=>'同じメソッド名で型に応じた異なる処理が実行される','is_correct'=>true],['body'=>'クラスを複数のクラスから継承できる','is_correct'=>false],['body'=>'プライベートメンバーへのアクセス','is_correct'=>false]]]],
            ['name'=>'イミュータブル（Immutable）','definition'=>'一度作成したら値を変更できないオブジェクト・変数のこと。スレッドセーフで副作用がなく関数型プログラミングで重視される。','example'=>'Rustのデフォルト変数・JavaのStringクラス・JavaScriptのconstなど。Reactのstateは直接変更せずに新オブジェクトを生成する。','difficulty'=>3,'quiz'=>['question'=>'イミュータブルなオブジェクトのメリットはどれか？','explanation'=>'イミュータブルオブジェクトは変更不可なのでスレッドセーフで副作用がなく、デバッグや予測可能な動作に有利。','choices'=>[['body'=>'メモリ使用量が削減できる','is_correct'=>false],['body'=>'変更不可によりスレッドセーフで副作用を防げる','is_correct'=>true],['body'=>'実行速度が向上する','is_correct'=>false],['body'=>'コレクション操作が容易になる','is_correct'=>false]]]],
            ['name'=>'型推論','definition'=>'変数や関数の型を明示的に宣言しなくても、コンパイラが文脈から自動で推論する機能。TypeScript・Rust・Swiftなどが持つ。','example'=>'TypeScriptで「const x = 42;」と書くだけでxがnumber型と推論され、型注釈なしに型チェックが有効になる。','difficulty'=>2,'quiz'=>['question'=>'型推論の説明として正しいものはどれか？','explanation'=>'型推論はコンパイラが代入される値や使われ方から変数の型を自動で決定する機能。明示的な型注釈を省けるがコンパイル時の型チェックは維持される。','choices'=>[['body'=>'型を実行時に動的に決める機能','is_correct'=>false],['body'=>'コンパイラが文脈から変数の型を自動決定する機能','is_correct'=>true],['body'=>'型を明示的に宣言しなければならない制約','is_correct'=>false],['body'=>'型変換を自動で行う機能','is_correct'=>false]]]],
            ['name'=>'関数型プログラミング','definition'=>'副作用を避けイミュータブルなデータ・純粋関数を使うプログラミングパラダイム。Haskell・Scala・Elixirや、JS・Pythonも対応。','example'=>'副作用なしのmap・filter・reduceを連鎖してデータ変換を表現する。ループで状態を変更するより予測しやすい。','difficulty'=>4,'quiz'=>['question'=>'関数型プログラミングにおける「純粋関数」の条件はどれか？','explanation'=>'純粋関数は（1）同じ引数なら常に同じ結果を返す（参照透明性）、（2）副作用（グローバル変数変更・I/Oなど）を持たない、の2条件を満たす。','choices'=>[['body'=>'classメソッドとして定義された関数','is_correct'=>false],['body'=>'同じ入力で常に同じ出力を返し副作用を持たない関数','is_correct'=>true],['body'=>'非同期で実行される関数','is_correct'=>false],['body'=>'引数がない関数','is_correct'=>false]]]],
            ['name'=>'MVC（Model-View-Controller）','definition'=>'アプリをModel（データ）・View（表示）・Controller（制御）の3層に分離するアーキテクチャパターン。LaravelやRailsが採用。','example'=>'LaravelでController（UserController）がModelを呼んでデータ取得し、View（blade）に渡して表示する。','difficulty'=>2,'quiz'=>['question'=>'MVCのControllerの役割として正しいものはどれか？','explanation'=>'ControllerはViewからのユーザー入力を受け取り、Modelのビジネスロジックを呼び出し、結果をViewに渡す調整役。','choices'=>[['body'=>'データを永続化する','is_correct'=>false],['body'=>'ユーザー入力を受けModelとViewを調整する','is_correct'=>true],['body'=>'HTMLを表示する','is_correct'=>false],['body'=>'データベースのSQLを実行する','is_correct'=>false]]]],
            ['name'=>'リファクタリング','definition'=>'プログラムの外部から見た動作を変えずにコードの内部構造を整理・改善すること。可読性・保守性・テスト容易性の向上が目的。','example'=>'長すぎるメソッドを複数の小メソッドに分割し、わかりにくい変数名をわかりやすいものに変更する。テストはすべて通るまま。','difficulty'=>2,'quiz'=>['question'=>'リファクタリングの定義として正しいものはどれか？','explanation'=>'リファクタリングは外部から見た動作を変えずにコードを改善する作業。新機能追加やバグ修正はリファクタリングに含まれない。','choices'=>[['body'=>'新機能を追加してコードを改善する','is_correct'=>false],['body'=>'外部動作を変えずにコードの内部構造を改善する','is_correct'=>true],['body'=>'バグを修正する','is_correct'=>false],['body'=>'コードのコメントを削除する','is_correct'=>false]]]],
            ['name'=>'スコープ','definition'=>'変数・関数が参照可能なコード上の範囲。グローバルスコープ・ローカルスコープ・ブロックスコープなどがある。','example'=>'JSでletをブロック{}内で宣言するとブロックスコープ。varは関数スコープで{}外からも参照できる。','difficulty'=>2,'quiz'=>['question'=>'JavaScriptのletとvarのスコープの違いはどれか？','explanation'=>'letはブロックスコープ（{}内）、varは関数スコープ（関数全体）。letはfor文の{}内にスコープが限られるがvarはそうでない。','choices'=>[['body'=>'letはグローバル、varはローカルスコープ','is_correct'=>false],['body'=>'letはブロックスコープ、varは関数スコープ','is_correct'=>true],['body'=>'両者のスコープは同じ','is_correct'=>false],['body'=>'varはES6以降使用できない','is_correct'=>false]]]],
            ['name'=>'イベントループ','definition'=>'JavaScriptの非同期処理を実現する仕組み。コールスタック・タスクキュー・マイクロタスクキューを使い、シングルスレッドで非同期を扱う。','example'=>'setTimeout(fn, 0)はコールスタックが空になった後にコールバックが実行される。Promiseのthenはマイクロタスクで優先実行される。','difficulty'=>4,'quiz'=>['question'=>'JavaScriptのイベントループについて正しいものはどれか？','explanation'=>'JavaScriptはシングルスレッドだが、イベントループにより非同期処理を効率的に扱う。コールスタックが空になるとタスクキューの処理を実行する。','choices'=>[['body'=>'マルチスレッドで非同期処理を行う','is_correct'=>false],['body'=>'シングルスレッドでコールスタックが空になるとキューの処理を実行','is_correct'=>true],['body'=>'OSの割り込みで非同期を実現する','is_correct'=>false],['body'=>'Promise使用時のみイベントループが機能する','is_correct'=>false]]]],
        ]];
    }

    private function osLinuxTerms(): array
    {
        return ['os-linux' => [
            ['name'=>'カーネル（Kernel）','definition'=>'OSの中核部分。プロセス管理・メモリ管理・デバイス管理・システムコール処理を担当し、ハードウェアを抽象化する。','example'=>'Linuxカーネルはモノリシックカーネル。デバイスドライバがカーネル空間で動作し、高い効率を発揮する。','difficulty'=>3,'quiz'=>['question'=>'Linuxカーネルの主な役割として正しいものはどれか？','explanation'=>'カーネルはプロセス・メモリ・ファイルシステム・デバイスを管理し、アプリとハードウェア間の橋渡しをする。','choices'=>[['body'=>'WebブラウザのJavaScriptを実行する','is_correct'=>false],['body'=>'プロセス・メモリ・デバイスを管理しハードウェアを抽象化する','is_correct'=>true],['body'=>'アプリケーションのUIを描画する','is_correct'=>false],['body'=>'ネットワーク設定のGUIを提供する','is_correct'=>false]]]],
            ['name'=>'システムコール（System Call）','definition'=>'ユーザー空間のプログラムがカーネルの機能（ファイル操作・ネットワーク・プロセス生成など）を利用するためのインターフェース。','example'=>'open()・read()・write()・fork()・execve()などがLinuxの代表的なシステムコール。straceで呼び出しを観察できる。','difficulty'=>3,'quiz'=>['question'=>'システムコールの説明として正しいものはどれか？','explanation'=>'システムコールはユーザー空間プログラムがカーネル機能を安全に呼び出す唯一の方法。直接ハードウェアアクセスは禁止されている。','choices'=>[['body'=>'ユーザーがコマンドを入力する操作','is_correct'=>false],['body'=>'ユーザー空間からカーネル機能を呼び出すインターフェース','is_correct'=>true],['body'=>'カーネル同士の通信プロトコル','is_correct'=>false],['body'=>'Bashのビルトインコマンド','is_correct'=>false]]]],
            ['name'=>'inode','definition'=>'Linuxファイルシステムでファイルのメタデータ（権限・所有者・タイムスタンプ・ブロックアドレス）を格納するデータ構造。ファイル名は別管理。','example'=>'ls -i でinode番号を確認できる。ハードリンクは同一inodeを複数ファイル名で参照する仕組み。','difficulty'=>4,'quiz'=>['question'=>'Linuxのinodeに格納されない情報はどれか？','explanation'=>'inodeはメタデータ（権限・サイズ・タイムスタンプ等）を持つがファイル名は格納しない。ファイル名はディレクトリエントリで管理される。','choices'=>[['body'=>'ファイルのアクセス権限','is_correct'=>false],['body'=>'ファイル名','is_correct'=>true],['body'=>'ファイルサイズ','is_correct'=>false],['body'=>'ファイルの最終更新時刻','is_correct'=>false]]]],
            ['name'=>'シンボリックリンク（symlink）','definition'=>'別のファイル・ディレクトリへのショートカットとなるファイル。ハードリンクと異なり別ファイルシステムやディレクトリも指せる。','example'=>'ln -s /etc/nginx/sites-available/mysite /etc/nginx/sites-enabled/mysite でシンボリックリンクを作成。','difficulty'=>3,'quiz'=>['question'=>'シンボリックリンクとハードリンクの違いとして正しいものはどれか？','explanation'=>'シンボリックリンクはパスを参照する別ファイルなのでファイルシステムを越えられるが、ハードリンクは同一inodeを共有するためFS内のみ。','choices'=>[['body'=>'シンボリックリンクは同一inodeを共有する','is_correct'=>false],['body'=>'シンボリックリンクは異なるファイルシステムも参照できる','is_correct'=>true],['body'=>'ハードリンクはディレクトリにも作成できる','is_correct'=>false],['body'=>'両者に機能上の違いはない','is_correct'=>false]]]],
            ['name'=>'sudo（Superuser Do）','definition'=>'一般ユーザーが特定のコマンドを管理者（root）権限で実行するコマンド。/etc/sudoersファイルで権限を細かく制御できる。','example'=>'sudo apt install nginx でnginxをroot権限でインストールする。sudo -l で自分のsudo権限を確認できる。','difficulty'=>1,'quiz'=>['question'=>'sudoers設定でユーザーの実行可能コマンドを制限する目的はどれか？','explanation'=>'最小権限の原則に基づき、ユーザーごとに必要なコマンドのみsudo許可することで、誤操作や侵害時のリスクを最小化する。','choices'=>[['body'=>'sudo使用の高速化','is_correct'=>false],['body'=>'最小権限の原則によりリスクを最小化する','is_correct'=>true],['body'=>'パスワードを省略する','is_correct'=>false],['body'=>'ログ記録を省略する','is_correct'=>false]]]],
            ['name'=>'シェルスクリプト','definition'=>'Bashなどのシェルで実行できるスクリプト。コマンドを組み合わせてバッチ処理・自動化・設定管理を行う。','example'=>'#!/bin/bash で始まるスクリプトファイルにバックアップ処理を記述し、cronで毎日自動実行する。','difficulty'=>2,'quiz'=>['question'=>'シェルスクリプトのshebang行（#!/bin/bash）の役割はどれか？','explanation'=>'shebangはスクリプトの1行目に記述しどのインタープリタで実行するかをOSに伝える。#!/bin/bashはBashで実行することを指示する。','choices'=>[['body'=>'コメントアウト行','is_correct'=>false],['body'=>'スクリプトを実行するインタープリタを指定する','is_correct'=>true],['body'=>'管理者権限でスクリプトを実行させる','is_correct'=>false],['body'=>'文字コードを指定する','is_correct'=>false]]]],
            ['name'=>'環境変数','definition'=>'OSが管理するプロセスに渡される名前と値のペア。設定値・パス・認証情報などをプログラムに渡すために使われる。','example'=>'export DATABASE_URL=mysql://user:pass@host/db でLaravelの.envの代わりに環境変数でDB設定を渡す。','difficulty'=>2,'quiz'=>['question'=>'Linuxで環境変数PATHの役割はどれか？','explanation'=>'PATHはコマンド実行時に検索するディレクトリのリスト。PATHにディレクトリを追加すると、そのディレクトリのコマンドをフルパスなしに実行できる。','choices'=>[['body'=>'ホームディレクトリのパス','is_correct'=>false],['body'=>'コマンドを検索するディレクトリのリスト','is_correct'=>true],['body'=>'カレントディレクトリのパス','is_correct'=>false],['body'=>'ログファイルの保存先','is_correct'=>false]]]],
            ['name'=>'パイプ（|）','definition'=>'あるコマンドの標準出力を別のコマンドの標準入力に渡す仕組み。複数コマンドを組み合わせて強力なデータ処理が可能。','example'=>'ps aux | grep nginx | awk \'{print $1}\' でnginxプロセスのユーザー名のみを抽出する。','difficulty'=>2,'quiz'=>['question'=>'Linuxのパイプ（|）の機能はどれか？','explanation'=>'パイプは左側コマンドの標準出力を右側コマンドの標準入力として渡すことで、コマンドを連結してデータ処理を行う。','choices'=>[['body'=>'コマンドを並列実行する','is_correct'=>false],['body'=>'左コマンドの出力を右コマンドの入力として渡す','is_correct'=>true],['body'=>'コマンドをバックグラウンド実行する','is_correct'=>false],['body'=>'ファイルに出力を保存する','is_correct'=>false]]]],
            ['name'=>'リダイレクト（>・>>・<）','definition'=>'コマンドの入出力先を変更する仕組み。>は上書き、>>は追記、<はファイルを入力として使う。2>でエラー出力を制御。','example'=>'ls -la > list.txt でlsの出力をファイルに保存。command >> log.txt でログを追記。','difficulty'=>2,'quiz'=>['question'=>'コマンドの標準エラー出力をファイルにリダイレクトするのはどれか？','explanation'=>'標準出力はfd1（>）、標準エラー出力はfd2（2>）でリダイレクト。2>&1で標準エラーを標準出力にマージできる。','choices'=>[['body'=>'command > file','is_correct'=>false],['body'=>'command 2> file','is_correct'=>true],['body'=>'command < file','is_correct'=>false],['body'=>'command >> file','is_correct'=>false]]]],
            ['name'=>'grep（Global Regular Expression Print）','definition'=>'テキストの中から正規表現に一致する行を検索・表示するコマンド。ログ解析やファイル内検索に多用する。','example'=>'grep -r "ERROR" /var/log/ で/var/log/以下の全ファイルから"ERROR"を含む行を再帰的に検索する。','difficulty'=>1,'quiz'=>['question'=>'grep -v オプションの動作はどれか？','explanation'=>'grep -vは「invert match」で指定パターンに一致しない行のみを表示する。条件を反転させる。','choices'=>[['body'=>'大文字小文字を無視して検索','is_correct'=>false],['body'=>'一致しない行を表示する（反転マッチ）','is_correct'=>true],['body'=>'行番号を表示する','is_correct'=>false],['body'=>'再帰的に検索する','is_correct'=>false]]]],
            ['name'=>'cron（ジョブスケジューラ）','definition'=>'Linuxで定期的なコマンド実行を設定するスケジューラ。crontabファイルに実行時刻と実行コマンドを記述する。','example'=>'0 2 * * * /usr/bin/backup.sh でcrontabに設定すると、毎日午前2時にbackup.shを実行する。','difficulty'=>2,'quiz'=>['question'=>'crontabエントリ「30 8 * * 1」が示す実行タイミングはどれか？','explanation'=>'crontabは「分 時 日 月 曜日」の順で指定。「30 8 * * 1」は毎週月曜（1）の8時30分を意味する。','choices'=>[['body'=>'毎日8:30に実行','is_correct'=>false],['body'=>'毎週月曜日の8:30に実行','is_correct'=>true],['body'=>'毎月1日の8:30に実行','is_correct'=>false],['body'=>'30分おきに8時間実行','is_correct'=>false]]]],
            ['name'=>'systemd','definition'=>'Linuxの初期化システム（init）とサービスマネージャー。サービスの起動・停止・有効化・ログ管理をsystemctlコマンドで行う。','example'=>'systemctl start nginx でnginxを起動し、systemctl enable nginx でOS起動時の自動起動を有効にする。','difficulty'=>2,'quiz'=>['question'=>'systemctl enable <service>の効果はどれか？','explanation'=>'systemctl enableはサービスをOS起動時に自動起動するよう有効化する。startは即時起動のみで再起動後は無効になる。','choices'=>[['body'=>'サービスを今すぐ起動する','is_correct'=>false],['body'=>'OS起動時にサービスを自動起動するよう設定する','is_correct'=>true],['body'=>'サービスを永久停止する','is_correct'=>false],['body'=>'サービスの設定ファイルを編集する','is_correct'=>false]]]],
            ['name'=>'シグナル（Signal）','definition'=>'Linuxでプロセスに非同期的に送る通知の仕組み。SIGKILL（強制終了）・SIGTERM（終了要求）・SIGHUP（再読込）などがある。','example'=>'kill -9 <PID> でSIGKILLを送り強制終了。kill -HUP <PID> でnginxに設定再読込を指示する。','difficulty'=>3,'quiz'=>['question'=>'SIGKILL（-9）とSIGTERM（-15）の違いはどれか？','explanation'=>'SIGTERMはプロセスが捕捉してクリーンアップ処理を行える。SIGKILLはカーネルが直接プロセスを強制終了しプロセスは処理できない。','choices'=>[['body'=>'SIGKILLはより丁寧な終了要求','is_correct'=>false],['body'=>'SIGKILLは捕捉不可の強制終了、SIGTERMはプロセスが処理できる終了要求','is_correct'=>true],['body'=>'両者に違いはない','is_correct'=>false],['body'=>'SIGTERMのみrootが送信できる','is_correct'=>false]]]],
            ['name'=>'仮想メモリ','definition'=>'物理RAMより大きなアドレス空間をプロセスに見せるOS機能。ページングによりRAMとスワップ領域を透過的に管理する。','example'=>'物理RAM 8GBのシステムでも、仮想メモリにより各プロセスは独立した大きなアドレス空間を利用できる。','difficulty'=>4,'quiz'=>['question'=>'仮想メモリのメリットとして正しいものはどれか？','explanation'=>'仮想メモリにより各プロセスは独立した連続アドレス空間を持てる。物理メモリより大きな領域を使えプロセス間の隔離も実現できる。','choices'=>[['body'=>'CPUの速度が向上する','is_correct'=>false],['body'=>'プロセスに物理メモリより大きな独立アドレス空間を提供する','is_correct'=>true],['body'=>'ディスクI/Oが高速化される','is_correct'=>false],['body'=>'マルチコアを活用できる','is_correct'=>false]]]],
            ['name'=>'スワップ（Swap）','definition'=>'物理RAMが不足したとき、使用頻度の低いメモリページをディスクの専用領域（スワップ領域）に退避させる仕組み。','example'=>'RAM 4GBのサーバーにスワップ4GBを設定すると、メモリ使用量が4GBを超えてもプロセスが起動できる（ただし低速）。','difficulty'=>3,'quiz'=>['question'=>'スワップの使用量が増加するとどうなるか？','explanation'=>'スワップはSSD/HDDのI/Oを伴うためRAMより数十〜数百倍低速。スワップが多用されるとシステムが著しく遅くなる（スラッシング）。','choices'=>[['body'=>'システムが高速になる','is_correct'=>false],['body'=>'ディスクI/Oが増えシステムが著しく遅くなる','is_correct'=>true],['body'=>'メモリエラーが自動修復される','is_correct'=>false],['body'=>'CPUの使用率が下がる','is_correct'=>false]]]],
            ['name'=>'ファイルパーミッション','definition'=>'Linuxのファイル・ディレクトリのアクセス権。所有者・グループ・その他（other）それぞれに読み（r）・書き（w）・実行（x）を設定。','example'=>'chmod 755 script.sh で所有者=rwx、グループ=r-x、その他=r-xに設定し、全員が実行できるようにする。','difficulty'=>2,'quiz'=>['question'=>'chmod 644 ファイルのパーミッションとして正しいものはどれか？','explanation'=>'8進数644は所有者=110（rw-）・グループ=100（r--）・その他=100（r--）。所有者は読み書き可、他は読み取りのみ。','choices'=>[['body'=>'全員が読み書き実行可能','is_correct'=>false],['body'=>'所有者は読み書き可、グループ・その他は読み取りのみ','is_correct'=>true],['body'=>'所有者のみ全権限、他は権限なし','is_correct'=>false],['body'=>'全員が読み取りのみ','is_correct'=>false]]]],
            ['name'=>'パッケージマネージャー','definition'=>'ソフトウェアのインストール・更新・削除を管理するツール。Debian系はapt、Red Hat系はyum/dnf、Ubuntuはsnap等がある。','example'=>'sudo apt update && sudo apt install nginx でパッケージリストを更新してnginxをインストールする。','difficulty'=>1,'quiz'=>['question'=>'Ubuntu/Debianで標準的に使うパッケージマネージャーはどれか？','explanation'=>'Ubuntu/Debian系ではapt（Advanced Package Tool）が標準。yum/dnfはRHEL/CentOS/Fedora系で使われる。','choices'=>[['body'=>'yum','is_correct'=>false],['body'=>'apt','is_correct'=>true],['body'=>'pacman','is_correct'=>false],['body'=>'brew','is_correct'=>false]]]],
            ['name'=>'プロセス','definition'=>'実行中のプログラムのインスタンス。プロセスIDとPID）・メモリ空間・状態などを持ち、OSが管理する。','example'=>'ps aux でシステムの全プロセスを表示。top/htopでリアルタイムにCPU・メモリ使用率とプロセスを監視する。','difficulty'=>2,'quiz'=>['question'=>'Linuxでプロセスの一覧を確認するコマンドはどれか？','explanation'=>'ps（Process Status）はプロセスのスナップショットを表示。ps aux で全ユーザーの全プロセスを表示できる。','choices'=>[['body'=>'ls -al','is_correct'=>false],['body'=>'ps aux','is_correct'=>true],['body'=>'netstat','is_correct'=>false],['body'=>'df -h','is_correct'=>false]]]],
            ['name'=>'iptables','definition'=>'LinuxカーネルのNetfilterを制御するファイアウォール設定コマンド。パケットフィルタリング・NATルールを設定する。','example'=>'iptables -A INPUT -p tcp --dport 22 -j ACCEPT でSSHポート22の着信を許可するルールを追加する。','difficulty'=>4,'quiz'=>['question'=>'iptablesでSSHポート以外の着信を全てブロックする場合のデフォルトポリシーはどれか？','explanation'=>'iptables -P INPUT DROPでデフォルトポリシーをDROPにし、必要なポートのみACCEPTルールを追加するホワイトリスト方式が安全。','choices'=>[['body'=>'ACCEPT','is_correct'=>false],['body'=>'DROP','is_correct'=>true],['body'=>'REJECT','is_correct'=>false],['body'=>'LOG','is_correct'=>false]]]],
            ['name'=>'デーモン（Daemon）','definition'=>'バックグラウンドで常時稼働するプロセス。Webサーバー・DBサーバー・cronなど。名前は慣習的に「d」で終わる（httpd, mysqld）。','example'=>'nginxはWebデーモンとしてバックグラウンドで常時稼働し、HTTPリクエストを待ち受ける。','difficulty'=>2,'quiz'=>['question'=>'デーモンプロセスの特徴として正しいものはどれか？','explanation'=>'デーモンは端末（tty）から切り離されてバックグラウンドで常時稼働するプロセス。ユーザーセッションと無関係に動き続ける。','choices'=>[['body'=>'ユーザーがログインしている間のみ動作する','is_correct'=>false],['body'=>'端末と切り離されてバックグラウンドで常時稼働する','is_correct'=>true],['body'=>'CPUを100%使用し続ける','is_correct'=>false],['body'=>'rootユーザーのみが起動できる','is_correct'=>false]]]],
            ['name'=>'ログファイル','definition'=>'システムやアプリの動作記録をテキストで残したファイル。Linuxでは主に/var/logディレクトリ以下に保存される。','example'=>'/var/log/nginx/access.log にWebアクセスログが記録される。journalctl -u nginx でsystemdのnginxログを確認できる。','difficulty'=>1,'quiz'=>['question'=>'Linuxの主要なシステムログが格納されるディレクトリはどれか？','explanation'=>'Linuxでは慣例的に/var/logにシステム・アプリのログが格納される。/var/log/syslog・/var/log/auth.log等が代表的。','choices'=>[['body'=>'/etc/logs','is_correct'=>false],['body'=>'/var/log','is_correct'=>true],['body'=>'/usr/log','is_correct'=>false],['body'=>'/home/log','is_correct'=>false]]]],
            ['name'=>'SELinux（Security-Enhanced Linux）','definition'=>'Linuxカーネルに組み込まれた強制アクセス制御（MAC）フレームワーク。通常のパーミッション（DAC）より細かくアクセスを制御する。','example'=>'SELinuxのポリシーでhttpdプロセスが読み取れるファイルを制限し、Webサーバー経由の横断攻撃を防ぐ。','difficulty'=>5,'quiz'=>['question'=>'SELinuxのモードのうち、違反を検知するがブロックしないモードはどれか？','explanation'=>'PermissiveモードはSELinuxのポリシー違反をログに記録するが通信をブロックしない。テストや移行期間中に使う。Enforcingは実際にブロックする。','choices'=>[['body'=>'Disabled','is_correct'=>false],['body'=>'Permissive','is_correct'=>true],['body'=>'Enforcing','is_correct'=>false],['body'=>'Monitor','is_correct'=>false]]]],
            ['name'=>'CPUスケジューリング','definition'=>'複数プロセスをCPUに割り当てる順序・時間を決めるOS機能。ラウンドロビン・優先度スケジューリング等のアルゴリズムがある。','example'=>'LinuxはCFS（Completely Fair Scheduler）を採用し、各プロセスに公平なCPU時間を配分する。','difficulty'=>4,'quiz'=>['question'=>'プリエンプティブスケジューリングの特徴はどれか？','explanation'=>'プリエンプティブスケジューリングはOSが強制的にCPUを横取り（プリエンプト）して別プロセスに切り替えられる。応答性の良いマルチタスクを実現する。','choices'=>[['body'=>'プロセスが自発的にCPUを譲渡するまで待つ','is_correct'=>false],['body'=>'OSが強制的にCPUを取り上げて別プロセスに割り当てる','is_correct'=>true],['body'=>'1プロセスが完了するまで他を待たせる','is_correct'=>false],['body'=>'プロセス優先度を無視して順番に実行する','is_correct'=>false]]]],
        ]];
    }
}
